### PR TITLE
Reset button for config forms

### PR DESCRIPTION
**Pull request by brockfanning**
In the config forms, after filtering the list of settings, it is impossible to get back to the full list. This adds a reset button for this purpose.

### CODE REVIEW

**Comment by jwestw** [comment]
Any advice on how to test this. If I create a feature branch, how do I get to the config form?

**Comment by LucyGwilliamAdmin** [comment]
@jwestw to get the config you will need to use [this setting in the site config](https://open-sdg.readthedocs.io/en/latest/configuration/#create_config_forms):

```
create_config_forms:
    layout: config-builder
```

**Comment by jwestw** [comment]
[Feature branch repo](https://github.com/ONSdigital/sdg-indicators/tree/config-form-reset-button) 

**Works as expected.**

image


@LucyGwilliamAdmin I note that in the [Docs on Site configuration](https://open-sdg.readthedocs.io/en/latest/configuration/#create_config_forms), it says:
"After setting this, you will have a site configuration form available through a link in the footer, as well as indicator configuration forms available in the "Edit" tab." However I couldn't seem to find a link to the site config in the footer. Where should that be?

**Review by jwestw — APPROVED** [review]
Reset button works as expected

**Comment by brockfanning** [comment]
@jwestw FYI, I believe the UK is overriding the footer.html include file, which might explain why the link did not show up.

**Pull request merged**
