### PR TITLE
Remove disaggregation control percentage bars

### LINKED ISSUE #1050: Remove disaggregation percentage bars from filters
Within usability testing conducted October 2020, no participants naturally noticed the disaggregation percentage bars displayed in the filters. When shown their function none said it was of any use to them.

Recommendation: Remove the disaggregation percentage bars from the filter options.

Screenshot (96)_LI

### PR DESCRIPTION
**Pull request by brockfanning**
Q | A
--- | ---
Feature branch/test site URL | [Link (temp)](https://lucygwilliamadmin.github.io/sandpit-site/1-2-1/)
Fixed issues | Fixes #1050 
Related version | 1.4.0-dev
Bugfix, feature or docs? | Feature
Keeps backward-compatibility? |❌ (removes unneeded feature)
Includes tests? |NA
Updated docs? |NA
Updated config forms? |NA
Added CHANGELOG entry? | ✔️

### CODE REVIEW

**Comment by LucyGwilliamAdmin** [comment]
@phillipgardiner I've just added a link to the description but also adding a screenshot for reference:

image

My only comment is that I'm not sure if the spacing between the dropdowns is different to the spacing between the "Clear selections" button and the Age dropdown is on purpose

**Comment by LucyGwilliamAdmin** [comment]
Thanks @brockfanning! @phillipgardiner i've just updated the preview with the latest changes - I've also checked a few indicators and can't see any issues

**Comment by phillipgardiner** [comment]
@brockfanning @LucyGwilliamAdmin When I follow the link and click the filter I get an overlap occurring
Screenshot (196)
...

**Comment by phillipgardiner** [comment]
@LucyGwilliamAdmin @brockfanning I still get the overlapping, but it seems to be intermittent. No pattern to when it occurs.

**Comment by LucyGwilliamAdmin** [comment]
@phillipgardiner that's strange - I can't seem to replicate that

**Comment by phillipgardiner** [comment]
@LucyGwilliamAdmin ummm I still get it occur, but like I say there doesn't seem to be a pattern to it for me to be able to say do this, then that, to recreate it unfortunately.

**Comment by brockfanning** [comment]
@phillipgardiner When you see the issue can you try a hard refresh? (SHIFT + F5)

I'm hoping that it's just the browser holding onto the old CSS.

**Comment by brockfanning** [comment]
@phillipgardiner Or maybe it's CTRL + F5, sorry.

**Comment by phillipgardiner** [comment]
@brockfanning nope still getting it afraid (just to confirm o'm using chrome when it occurs). I just tired it in IE and I dont get it, however another thing occurred, the chevrons went missing form the filters.
Screenshot (197).

Perhaps its all just something weird to do with my computer.

**Comment by LucyGwilliamAdmin** [comment]
@phillipgardiner are you still getting it today?
Also the chevron's disappearing is an ONS laptop thing - some sort of security feature I think

**Comment by phillipgardiner** [comment]
@LucyGwilliamAdmin Yep afraid so.

**Comment by LucyGwilliamAdmin** [comment]
@brockfanning so I've just had a discussion with Phill about this and ended up rebuilding. The first time I refreshed I experienced the same issue as him. Could you take a look here and expand Sex first and see if you get same issue? https://lucygwilliamadmin.github.io/sandpit-site/1-2-1/

It seems to maybe me something to do with:
image

**Comment by brockfanning** [comment]
@LucyGwilliamAdmin @phillipgardiner I can't recreate it yet, but I will see if it's possible to to change that CSS to use something other than the aria-expanded attribute. My guess is that in some scenarios the aria-expanded attribute is failing to get added.

**Comment by LucyGwilliamAdmin** [comment]
@brockfanning I've just been able to create again and got this error in console:

**Comment by brockfanning** [comment]
@LucyGwilliamAdmin Great clue, thanks much - that would definitely cause it.

**Comment by brockfanning** [comment]
@LucyGwilliamAdmin @phillipgardiner I think I see the pattern - the the problem only happen when the chevron is clicked? (as opposed to clicking another part of the dropdown?)

**Comment by phillipgardiner** [comment]
@brockfanning Yes it does look like that is the case :)

**Comment by brockfanning** [comment]
@LucyGwilliamAdmin Just pushed up a fix for when you have time to refresh.

**Comment by LucyGwilliamAdmin** [comment]
It's rebuilt and seems to be working now

**Comment by brockfanning** [comment]
@LucyGwilliamAdmin Sounds good! @phillipgardiner Are we OK to merge this?

**Comment by phillipgardiner** [comment]
@brockfanning Yes from me :)

**Pull request merged**
