### PR TITLE
Color adjustments for chart grids

### LINKED ISSUE #1094: Increase contrast of graph grids in high contrast mode
Graph grid lines are quite faint - may not even pass contrast guidelines:
image

### PR DESCRIPTION
**Pull request by brockfanning**
Fixes #1094 

EDIT: [feature branch](http://sdgdev-813006012.eu-west-1.elb.amazonaws.com/more-contrast-chart-grid-lines-1)

### CODE REVIEW

**Comment by LucyGwilliamAdmin** [comment]
@brockfanning @phillipgardiner feature branch created - link in description above

**Review by LucyGwilliamAdmin — APPROVED** [review]
Points raised by Phill for this ticket
Point|done
---|---
Change the main x-axis and the y-axis lines to a dark grey (#757575). This grey would work for both the default and high contrast graphs.|✔️
Remove the y-axis grid lines. Display only x-axis grid lines. These x-axis will remain their current colour|✔️
Update the default data line Blue colour to (#004466)|✔️
Update the mouse hoover line to dark grey (#757575) on both default and high contrast.|✔️
Update the mouse hover line to a dashed line|✔️
Keep the high contrast default data line yellow (#FFFF00). However this will change once #1099 is implemented.|✔️

**Comment by LucyGwilliamAdmin** [comment]
@phillipgardiner I've used the points you've made to approve this ticket but is there anything you want to add?

**Comment by phillipgardiner** [comment]
@LucyGwilliamAdmin No all good thanks

**Pull request merged**
