### PR TITLE
Back-to-top component and styling

### LINKED ISSUE #1055: Style 'back to top' links
The UK service currently has back to top links on two pages FAQ and Publications. These have been styled using markdown only.

Work is required to add a consistent style to back to top links for all countrys. The standard to follow can be found here: https://government-frontend.herokuapp.com/component-guide/back-to-top

image

An active example of this can be found here: https://www.gov.uk/government/publications/financial-sanctions-consolidated-list-of-targets/consolidated-list-of-targets#contents

Original UK ticket can be found here: [https://github.com/ONSdigital/sdg-indicators/issues/3393](url)

### PR DESCRIPTION
**Pull request by brockfanning**
Q | A
--- | ---
Feature branch/test site URL | [Link](https://lucygwilliamadmin.github.io/sdg-indicators/publications/) (with component) and [Link](https://lucygwilliamadmin.github.io/sdg-indicators/faq/) (with #top link) - see bottom of pages
Fixed issues | Fixes #1055 
Related version | 1.4.0-dev
Bugfix, feature or docs? | Feature
Keeps backward-compatibility? |✔️ (technically a change but minor)
Includes tests? |NA
Updated docs? |✔️
Updated config forms? |NA
Added CHANGELOG entry? |❌

### CODE REVIEW

**Comment by LucyGwilliamAdmin** [comment]
@brockfanning @phillipgardiner I've added some links to description - I wasn't sure if it was mean to be standalone or next to text so I've done one page with and one without

**Comment by brockfanning** [comment]
@LucyGwilliamAdmin It was meant to include the text automatically - I think this depends on the latest translations - sorry I forgot to mention that. It uses a translation key of "general.back_to_top" which I only just added [recently](https://github.com/open-sdg/sdg-translations/commit/5f1120b6ca52f972e60b54a2f2c3d8e2ec3dee91#diff-ad2de29ccfb8d1360f6f7f9a5b587203e71d88b1f9b4f48e8267a414010805a7).

**Comment by phillipgardiner** [comment]
@LucyGwilliamAdmin @brockfanning Thanks. Definitely with text. These seem to look a bit different to what was suggested: [https://government-frontend.herokuapp.com/component-guide/back-to-top ](url)though?

**Comment by LucyGwilliamAdmin** [comment]
@brockfanning @phillipgardiner I've just updates that link so that the text is included in the component

**Comment by brockfanning** [comment]
@LucyGwilliamAdmin @phillipgardiner Cool. Regarding the look of the up-arrow icon, I started by using an icon provided by the Font Awesome library that we already use in Open SDG. The gov.uk approach uses a custom SVG image instead. If needed I could copy that SVG image code into Open SDG, but thought I would start simple and get feedback.

**Comment by phillipgardiner** [comment]
@brockfanning @LucyGwilliamAdmin No that's fine the arrow head is a bit by the by (as long as its accessible etc, if thats what we have used elsewhere). I guess i was was meaning more that it didn't have the expected behaviour (e.g. the link changing colour as you hover over it etc), but that all seems to be correct now.

The only thing I would change though is I would left align it with the rest of the text for now (remove margin left?) and increase the white space between the last sentence and it (margin top 15px?). thanks

**Comment by brockfanning** [comment]
@LucyGwilliamAdmin I just made that suggested margin tweak, so it's ready for a refresh.

**Comment by LucyGwilliamAdmin** [comment]
Thanks @brockfanning! @phillipgardiner I've updated the link :)

**Comment by phillipgardiner** [comment]
@brockfanning @LucyGwilliamAdmin Thanks both. Margin and spacing looks good. ONe thing though when I click the link I get a yellow line / bar appear at the top of the page / browser window. 
Screenshot (198)

**Comment by LucyGwilliamAdmin** [comment]
@phillipgardiner @brockfanning I'm also getting the same. I think it might be `tabindex="-1" here that is causing an issue:
https://github.com/open-sdg/open-sdg/blob/master/_includes/components/page-top.html

Not sure if it was added for accessibility purposes though?

**Comment by LucyGwilliamAdmin** [comment]
@brockfanning @phillipgardiner links have been refreshed - one used the component and one uses the #top link

**Comment by phillipgardiner** [comment]
@brockfanning @LucyGwilliamAdmin Brill, works for me :)

**Review by LucyGwilliamAdmin — APPROVED** [review]

**Pull request merged**
