### PR TITLE
More precise image switching code

### LINKED ISSUE #1118: Only keep same image in high contrast if image is SVG
#1039 had some unintended side effects. When looking at the site in high contrast mode, if images are PNG and not SVG then they're also not swapped for high contrast version.
 
Instead expected behaviour would be that if image is not an SVG, then use high contrast version of image instead

### PR DESCRIPTION
**Pull request by brockfanning**
Q | A
--- | ---
Feature branch/test site URL | [Link](add link here)
Fixed issues | Fixes #1118
Related version | 1.3.0-dev
Bugfix, feature or docs? | Bugfix
Keeps backward-compatibility? |✔️
Updated docs/config-forms? | NA
Added CHANGELOG entry? | NA (because this fixes a bug in the same release)

### CODE REVIEW

**Comment by jwestw** [comment]
On the [feature branch]()http://sdgdev-813006012.eu-west-1.elb.amazonaws.com/svg-icon-image-fix/ this appears to be working. 

This is a png image in high contrast mode:

image

This is a underlying link to the image:

image

As you can see it is "high-contrast" png. 

@Lucy does this fix the issue #1118 ?

@phillipgardiner can you also confirm this is okay?

**Comment by phillipgardiner** [comment]
@jwestw Sorry I don't know anything about this one, one for @LucyGwilliamAdmin and @brockfanning

**Comment by LucyGwilliamAdmin** [comment]
Yes png images are now showing in high contrast when in high contrast mode

**Review by jwestw — APPROVED** [review]
Approving according my tests and Lucy's comment.

**Pull request merged**
