### PR TITLE
Composite breakdown label

### LINKED ISSUE #1019: Allow COMPOSITE_BREAKDOWN to have a configurable label per indicator
**Is your feature request related to a problem? Please describe.**

If the data source is SDMX-compatible then it likely uses COMPOSITE_BREAKDOWN for a number of disaggregations. Unfortunately the label "COMPOSITE_BREAKDOWN" does not tell the user much about the category of the disaggregations being used on a particular indicator.

**Describe the solution that you need**

Let's add the ability to specify a particular label, per indicator. This could be done with a metadata field called "composite_breakdown_label" or similar.

**Why do you need this feature?**

This would allow, for example, one indicator's COMPOSITE_BREAKDOWN to be labeled "Skill" while another indicator's COMPOSITE_BREAKDOWN to be labeled "Hazard type".

**Describe alternatives you've considered**

The only alternatives are
1. To not be SDMX-compatible
2. To display "Composite breakdown" (or "General category" or similar) and rely on the user to figure it out

Neither of these are ideal.

### PR DESCRIPTION
**Pull request by brockfanning**
Fixes #1019 

This adds support for a `composite_breakdown_label` metadata field. If this field is provided, then any disaggregation column with the name 'COMPOSITE_BREAKDOWN' will be renamed before being displayed in the left sidebar dropdowns. This is useful if the data source is SDMX, which often uses COMPOSITE_BREAKDOWN for a variety of purposes.

EDIT: This depends on the latest sdg-build code: 1.3.0-dev.

EDIT: [feature branch](http://sdgdev-813006012.eu-west-1.elb.amazonaws.com/composite-breakdown-label) - see 1.2.1 and 1.2.2

### CODE REVIEW

**Comment by LucyGwilliamAdmin** [comment]
@brockfanning I've made the following changes
Data repo:
- https://github.com/ONSdigital/sdg-data/commit/35256ed28efa0e40b6e56a97ad22ff10f3c3628b
- https://github.com/ONSdigital/sdg-data/commit/c02607b2d799dff84e16a99f8b9a3b679db481f3

Site repo:
- https://github.com/ONSdigital/sdg-indicators/blob/composite-breakdown-label/_config.yml#L149


However, COMPOSITE_BREAKDOWN doesn't display as what I set:
http://sdgdev-813006012.eu-west-1.elb.amazonaws.com/composite-breakdown-label/1-2-1/

**Comment by brockfanning** [comment]
@LucyGwilliamAdmin Sorry, I think this depends on the latest sdg-build code, so you would need to point to 1.3.0-dev on sdg-build.

**Comment by LucyGwilliamAdmin** [comment]
@brockfanning of course!

This worked when I used it on one indicator but doesn't seem to work when using on two:

See 1.2.1[http://sdgdev-813006012.eu-west-1.elb.amazonaws.com/datapreview_composite-breakdown-label/1-2-1/] and 1.2.2[http://sdgdev-813006012.eu-west-1.elb.amazonaws.com/datapreview_composite-breakdown-label/1-2-2/] on this feature branch

**Comment by brockfanning** [comment]
@LucyGwilliamAdmin Is it possible that the site feature branch needs to be rebuilt?

**Comment by LucyGwilliamAdmin** [comment]
I did rebuild the site feature branch earlier but maybe it was too soon as I've just rebuilt again and now both are working

**Review by LucyGwilliamAdmin — APPROVED** [review]
This works well and is a great way to be able to use the composite breakdown concept

**Pull request merged**
