### PR TITLE
Use buttons for the mobile menu/search drop-downs

### LINKED ISSUE #844: Mark up mobile "Menu" button accessibly
**Page 98 in DAC report**

**Issue from DAC report:**
The Menu is focusable, but not keyboard actionable. It has no role, and nothing to describe its expanded or collapsed status to screen reader users. It has been implemented as a <span> which has been assigned the role of ‘navigation’ region.

The search button is not focusable or keyboard actionable and has no role nor expanded or collapsed status. 

**Solution from DAC report:**
Buttons should be marked up as such to ensure that they have a properly associated role to expose their behaviour and purpose to assistive technology. The aria-expanded attribute should be associated with the button. The navigation role associated with the ‘menu’ should be associated with the navigational region it triggers.

**Example from DAC report:**

```
<ul class="top-level">
    <li id="menuToggle" aria-label="Menu toggle. Click to expand or collapse 
      the menu." aria-haspopup="true">
        <button data-target="menu" aria-expanded="true">Menu</button>
    </li>
    <li><button data-target="search" aria-expanded="false">Search</span> 
    </button>
</ul>
…
<div role="navigation" aria-label="Menu">
    <ul class="nav navbar-nav menu-target contrast-switcher" id="menu"
    style="display: block;">…/ul>
</div>
```

### PR DESCRIPTION
**Pull request by brockfanning**
Fixes #844

### CODE REVIEW

**Comment by jwestw** [comment]
Feature branch is here: http://sdgdev-813006012.eu-west-1.elb.amazonaws.com/ 

Have looked through this and #844 and I am unsure what I am trying to test here. Have checked for the code specified in the DAC report, e.g. `aria-haspopup="true"` but couldn't find it. Probably inspecting the wrong elements. Could do with a conversation to clarify.

**Comment by brockfanning** [comment]
@jwestw I may have forgotten that attribute - but here are some testing instructions so you can confirm:
1. In Chrome or Firefox view any page
2. Shrink the browser window until you see the "Menu" and "Search" items below the main logo. (These items only appear when the browser gets down to a certain width)
3. Right-click and "Inspect element" on those items

**Comment by jwestw** [comment]
Hey so on the search button on a narrow window I am seeing 
```
<li id="searchToggle" aria-label="Search toggle. Click to expand or collapse the search bar." aria-haspopup="true">
          <button data-target="search" aria-expanded="false">Search</button>
        </li>
<button data-target="search" aria-expanded="false">Search</button>
```

- [In the DAC report it said "The aria-expanded attribute should be associated with the button", I see that attribute.  ] 
- [In the DAC report it said "Buttons should be marked up as such to ensure that they have a properly associated role to expose their behaviour and purpose to assistive technology". Now we have an instruction to click to expand...] Seems good. 

Very similar attributes are seen in the Menu button code.

**Review by jwestw — APPROVED** [review]
All seems good on http://sdgdev-813006012.eu-west-1.elb.amazonaws.com/jw-test-search-drop-downs/

**Pull request merged**
