### PR TITLE
FAQ: mapping update

### PR DESCRIPTION
**Pull request by Norric1Admin**
@brockfanning are you happy with these example links and the reference to UK step-by-step guidance?

### CODE REVIEW

**Comment by brockfanning** [comment]
@Norric1Admin If urgent, I'm OK with that. But if there is time do you think we could try and get the step-by-step into the Open SDG docs? I've got a few notes about those docs, but I'll follow-up offline.

**Comment by Norric1Admin** [comment]
Yes certainly. Perhaps we could get this version online for now, and then follow it up next week with more details? We need to review our own guidance over April/May and are likely to have more suggestions.

**Comment by brockfanning** [comment]
My only concern is the Mapbox API token issue -- maybe that should be clarified/detailed in this update?

**Comment by Norric1Admin** [comment]
Thanks Brock. What is the issue with Mapbox API tokens - does each Country have to generate a new one, or do the token permissions need to be updated for each new location? Interested to know how this works.

**Comment by brockfanning** [comment]
Yes, each country needs their own token, if they want to use Mapbox.

**Pull request merged**
