### PR TITLE
Fix the mobile navigation tab order

### LINKED ISSUE #922: Ensure menu focus sequence is correct on mobile
**URL:** https://sdgdata.gov.uk/
**Device:** Mobile

**Screenshot:**

When the Menu is expanded, focus is taken into the menu, but once users reach the end of the menu (i.e. passed the ‘Updates’ link’), they are not navigated to ‘Search’, but bypass ‘Search’ directly to the main page content.

**Solution:**
Please ensure focusable elements appear in the desired tab sequence order within the HTML.

**Example:**

```
<nav class="navbar navbar-default" id="main-nav">
  <ul class="top-level">
    <li id="menuToggle" aria-label="Menu toggle. Click to expand or collapse the menu." aria-haspopup="true" class="active" aria-expanded="true">
      <button data-target="menu" aria-expanded="true">Menu</button>
      <ul class="nav navbar-nav menu-target contrast-switcher" id="menu" style="display: block;">[…]</ul>
    </li>
    <li id="searchToggle" aria-label="Search toggle. Click to expand or collapse the search bar." aria-haspopup="true"> 
      <button data-target="search" aria-expanded="false">Search</button>
      <div id="search" class="menu-target" style="display: none;">[…]</div>
    </li>
  </ul>
</nav>
```

instead of:

```
<nav class="navbar navbar-default" id="main-nav">
  <ul class="top-level">
    <li id="menuToggle" aria-label="Menu toggle. Click to expand or collapse the menu." aria-haspopup="true" class="active" aria-expanded="true">
      <button data-target="menu" aria-expanded="true">Menu</button>
    </li>
    <li id="searchToggle" aria-label="Search toggle. Click to expand or collapse the search bar." aria-haspopup="true">
      <button data-target="search" aria-expanded="false">Search</button>
    </li>
  </ul>
  <div id="search" class="menu-target" style="display: none;">[…]</div>
  <ul class="nav navbar-nav menu-target contrast-switcher" id="menu" style="display: block;">[…]</ul>
</nav>
```

### PR DESCRIPTION
**Pull request by brockfanning**
Fixes #922 

This is a fairly significant change of markup and style, which adds duplicate versions of the search and navigation specifically for mobile. Hopefully no visuals or functionality will change, except for the tab order of the mobile nav, as described in #922.

### CODE REVIEW

**Comment by brockfanning** [comment]
@LucyGwilliamAdmin @jwestw Sorry, I see there are test failures. Let me try and resolve that before you spend any time reviewing this.

**Comment by brockfanning** [comment]
@jwestw @LucyGwilliamAdmin Ok I think this is ready for review.

**Comment by jwestw** [comment]
Feature branch for 952: http://sdgdev-813006012.eu-west-1.elb.amazonaws.com/jw-test-952-mobile-nav-tab-order

**Review by LucyGwilliamAdmin — APPROVED** [review]
DAC don't have time to review this ahead of retest starting tomorrow but it looks good to me so marking as approved. Again I think we could merge this @brockfanning

**Pull request merged**
