### PR TITLE
Make the active tab panel focusable

### LINKED ISSUE #924: Make tab-panels focusable
**URL:** http://sdgdev-813006012.eu-west-1.elb.amazonaws.com/dac2020/1-2-1/

Tab-panels are not focusable and screen reader users are not able to navigate from the tabs using cursor keys, so in order to read the content within the tab it is necessary to tab to the next focusable element on the page, and then use the cursor keys to navigate back up the page.

**Current Code Ref(s):** #chartview

```
<div role="tabpanel" class="tabPanel" id="chartview" aria-hidden="false" aria-labelledby="tab-chartview" style="">[…]</div>
```

**Solution:**
Include the tabpanel in the page sequence when it is triggered so that it can be focused by screen reader users.

**Example:** 

```
<div role="tabpanel" class="tabPanel" id="chartview" aria-hidden="false" aria-labelledby="tab-chartview" style="" tabindex="0">[…]</div>
```

### PR DESCRIPTION
**Pull request by brockfanning**
Fixes #924

### CODE REVIEW

**Comment by jwestw** [comment]
Feature branch:  http://sdgdev-813006012.eu-west-1.elb.amazonaws.com/jw-test-focusable-tab-panels

**Comment by jwestw** [comment]
Currently trying to spot difference in behaviour between
https://sdgdata.gov.uk/1-2-1/
and 
http://sdgdev-813006012.eu-west-1.elb.amazonaws.com/jw-test-focusable-tab-panels/1-2-1/

**Comment by brockfanning** [comment]
@jwestw My impression from the ticket's description is that you should now be able to use the TAB key to get to the contents of a tab -- aka a "tab pane" (for example the Sources on an indicator page) and then use the down arrow to read the pane's contents.

**Comment by LucyGwilliamAdmin** [comment]
@brockfanning just checking does `accessible_tabs: true` need to be set for testing this?

**Comment by brockfanning** [comment]
Ah, good point - yes it does.

**Comment by LucyGwilliamAdmin** [comment]
@brockfanning thanks

@jwestw  Can you add `accessible_tabs` to the config file of the feature branch please?

**Comment by jwestw** [comment]
This is working very nicely! 

image

Hopefully my (unedited) screenshot shows the highlighted tab-pane.

**Review by jwestw — APPROVED** [review]
Approving according to the previous comments.

**Comment by LucyGwilliamAdmin** [comment]
@brockfanning @jwestw sent to DAC for sign-off and got the following reply:

> looks resolved but I wouldn’t do a yellow background as a focus, just a yellow border

**Pull request merged**
