### PR TITLE
Merge DAC updates

### PR DESCRIPTION
**Pull request by Norric1Admin**
0.7.2

### CODE REVIEW

**Comment by Norric1Admin** [comment]
@brockfanning Are there any recent changes you know of that might be overwritten? Seems OK to us.

**Comment by brockfanning** [comment]
Would it be possible to summarize what this PR does? (like what bugs it fixes or features it adds)

**Comment by LucyGwilliamAdmin** [comment]
@Norric1Admin @brockfanning I'm not sure what others think, but might it be worth creating a branch from master as it is now and then adding the changes in, while also making sure that commits are labelled properly. I can see that a lot of changes have been made to the same files from trial and error commits. 

As I'm trying to review I'm struggling to see what each thing is doing (so also might be worth having the main dac branch and then having branches coming off that for each individual feature?)

**Comment by Norric1Admin** [comment]
@LucyGwilliamAdmin @brockfanning Can I get an approval on these changes please?

**Pull request closed without merging**
