### PR TITLE
High-contrast consistency for buttons

### LINKED ISSUE #1114: Change colour of download buttons in high contrast mode
Currently the download buttons within the high contrast mode are white: #FFFFFF.

In order to align these with the rest of the page, could these buttons please be changed to: #EEEEEE in normal state. Then when a mouse hovers over it: #DBDAD9.

### PR DESCRIPTION
**Pull request by brockfanning**
Q | A
--- | ---
Feature branch/test site URL | [Link](https://lucygwilliamadmin.github.io/sdg-indicators)
Fixed issues | Fixes #1114 
Related version | 1.4.0-dev
Bugfix, feature or docs? | Feature
Keeps backward-compatibility? |✔️ (technically a change but minor)
Includes tests? |NA
Updated docs? |NA
Updated config forms? |NA
Added CHANGELOG entry? |❌

### CODE REVIEW

**Comment by LucyGwilliamAdmin** [comment]
@phillipgardiner @brockfanning I've just added a link for this.
It looks like the box shadow colour is remaining green:

image
image

**Comment by brockfanning** [comment]
Thanks @LucyGwilliamAdmin, it should be ready for a refresh now.

**Comment by LucyGwilliamAdmin** [comment]
@brockfanning thank you - I've updated and it looks good.

@phillipgardiner do you want to take a look at this one?

**Comment by phillipgardiner** [comment]
@LucyGwilliamAdmin Have done, looks good :)

**Review by LucyGwilliamAdmin — APPROVED** [review]

**Pull request merged**
