### PR TITLE
Translate 'Results found'

### LINKED ISSUE #236: Properly translate the result count in search results
The result count (eg, "26 indicators found") on the search page is not being translated. Example: [here](https://kazstat.github.io/sdg-site-kazstat/search/?q=%20%D0%BF%D0%B0%D0%B9%D1%8B%D0%B7)

### PR DESCRIPTION
**Pull request by brockfanning**
Fixes #236 

## Testing

Testing this in a non-English language is quite tricky and would involve a lot of extra steps. I would recommend only testing that this works in English. If it works in English, it will work in other languages (once they are translated).

To test, do any search and look for a "Results found: X" message.  If it does not appear, then it's not working right.

### CODE REVIEW

**Comment by jwestw** [comment]
After setting up the feature branch I searched for "testing" and then searched on the page for "Results found" it did not appear. As Brock says, "If it does not appear, then it's not working right" so I believe it is working. 

**Searching for "Results found" on the page**

image

**The top of the results display**

image

**Review by jwestw — APPROVED** [review]
If my logic is correct in the last comment, then this is done and should be merged.

**Comment by LucyGwilliamAdmin** [comment]
@jwestw "Results found" should actually be showing - I think you may need to point at 1.3.0-dev for translations

**Comment by jwestw** [comment]
Notes on this: 
Indicator feature branch: [site](http://sdgdev-813006012.eu-west-1.elb.amazonaws.com/translate-search-result-count/), [repo/branch](https://github.com/ONSdigital/sdg-indicators/tree/translate-search-result-count)
Data feature branch: [site](http://sdgdev-813006012.eu-west-1.elb.amazonaws.com/data/translate-search-result-count/), [repo/branch](https://github.com/ONSdigital/sdg-data/tree/translate-search-result-count)

- Site branch remote theme pointing at Brock's translate-search-result-count branch. 
- Site branch is pointing at data branch
- Data branch has translations pointing at tag/branch 1.3.0-dev

I think I have covered everything there. 

Testing so far is not showing desired behaviour. Comments welcome. Will come back to this.

**Comment by brockfanning** [comment]
@jwestw I'm stumped on this one. When I build that data branch locally I definitely get the "results_found" translation:

```
    "search": {
        "did_you_mean": "did you mean",
        "found_in": "found in",
        "indicator_search": "Indicator search",
        "keywords": "Keywords",
        "no_results": "No results",
        "results_found": "Results found",
        "search": "Search",
        "search_results_for": "Search results for"
    },
```

But clearly the build on the feature branch server does not have it: http://sdgdev-813006012.eu-west-1.elb.amazonaws.com/data/translate-search-result-count/en/translations/translations.json

I'm not sure what's going on there - it's like the data build is not working right on the feature branch server.

**Comment by LucyGwilliamAdmin** [comment]
@jwestw @brockfanning might it be worth forcing a rebuild of the data branch?

**Comment by brockfanning** [comment]
Sounds good.

**Comment by brockfanning** [comment]
@LucyGwilliamAdmin @jwestw Not sure if it's related, but I'm noticing today that your [geojson for local authorities](https://geoportal1-ons.opendata.arcgis.com/datasets/686603e943f948acaa13fb5d2b0f1275_4.geojson) is not downloading successfully. That would prevent a data build from completing, if it's happening for you as well.

**Comment by LucyGwilliamAdmin** [comment]
@brockfanning is that download working for you now? It seems to be working for me

However when I was building data earlier I did get an error to do with geojson connection but when I rerun the tests (without making any changes) they passed

**Comment by brockfanning** [comment]
@LucyGwilliamAdmin Yep the download is working for me now too.

**Comment by brockfanning** [comment]
@jwestw @LucyGwilliamAdmin Looks like this fixed itself, right?

**Comment by LucyGwilliamAdmin** [comment]
@brockfanning @jwestw agreed, looks to be working now - think it can be approved

**Review by jwestw — APPROVED** [review]
Appears to be working now. 

image

**Pull request merged**
