### PR TITLE
Another attempt to optimize getCombinationData

### LINKED ISSUE #1267: Handle large number of disaggregations
When a user attempts to add too many disaggregations the page freezes and becomes unresponsive

For example, see:

Go to http://uk-sdg-feature-branches.s3-website.eu-west-2.amazonaws.com/feature-site-1.4.0-beta2/11-6-2/
Click "Select all" from Local authority dropdown

And:

Go to: http://uk-sdg-feature-branches.s3-website.eu-west-2.amazonaws.com/feature-site-1.4.0-beta2/5-2-1
Click "Select all" from dropdowns Age, Country of birth, Disability status, Ethnicity,  Highest Qualification, Type of partner abuse and Abuse sub-category

### PR DESCRIPTION
**Pull request by brockfanning**
Q | A
--- | ---
Feature branch/test site URL | [Link](http://uk-sdg-feature-branches.s3-website.eu-west-2.amazonaws.com/feature-site-disagg-freeze-fix)
Fixed issues | Fixes #1267
Related version | 1.4.0-dev
Bugfix, feature or docs? | Bugfix
Keeps backward-compatibility? |✔️
Includes tests? |NA
Updated docs? |NA
Updated config forms? |NA
Added CHANGELOG entry? |NA (optimization only needed because of another change in this release)

### CODE REVIEW

**Comment by brockfanning** [comment]
@LucyGwilliamAdmin @MoBosse This is another bugfix for 1.4.0, fixing #1267. Any help in testing would be greatly appreciated, if possible. Here are the things that we need to confirm:
1. Indicators with large numbers (like 10, 20, 50+ items) of disaggregations perform well even when the "Select all" button as pressed.
2. Indicators with multiple multi-level disaggregations still work as expected. In particular, confirm that there are no combinations of disaggregation that appear to have no effect on the chart.
3. The chart legend items still display correctly and in the expected order.

**Comment by LucyGwilliamAdmin** [comment]
Re:
1. Clicking select all for Local Authority on [11.6.2](http://uk-sdg-feature-branches.s3-website.eu-west-2.amazonaws.com/feature-site-disagg-freeze-fix/11-6-2/) doesn't cause the site to freeze
2. [5.2.1](http://uk-sdg-feature-branches.s3-website.eu-west-2.amazonaws.com/feature-site-disagg-freeze-fix/5-2-1/) which has had problems in the past works as expected
3. Legend order seems to match the final result of #1177 
    
image

**Comment by LucyGwilliamAdmin** [comment]
@brockfanning actually - even though 11.6.2 works I'm getting an issue with 5.2.1 when selecting a lot of disaggregations e.g.
- go to [5.2.1](http://uk-sdg-feature-branches.s3-website.eu-west-2.amazonaws.com/feature-site-disagg-freeze-fix/5-2-1/) 
- go through all the disaggregation dropdowns clicking select 
- notice when you click Select all for Region, things start freezing - it eventually loads for Region and Type of partner abuse but then I get page unresponsive when I click select all for Abuse subcategory

**Comment by brockfanning** [comment]
@LucyGwilliamAdmin Yes it looks like a problematic use-case still is pressing "select all" in many different columns. Do you think this is something that users will do in practice? We do want to avoid "premature optimization" (ie, devoting efforts to improving something that doesn't affect real users). Also, if we do decide to support that use-case, we need to decide whether it needs to be resolved for 1.4.0 or it can be postponed till a future release.

**Comment by LucyGwilliamAdmin** [comment]
That's my thoughts - I don't think users are going to try and add that many things to a chart or table so I think what's been done so far (i.e. in this PR is enough)

**Comment by brockfanning** [comment]
@LucyGwilliamAdmin Ok, sounds good.

**Review by LucyGwilliamAdmin — APPROVED** [review]
Approving

**Pull request merged**
