### PR TITLE
Logo per language

### LINKED ISSUE #1031: Changing main logo based on current language
With @brockfanning's help, I managed to create this feature. Maybe it would be good to create a tutorial in open SDG documentation.

Steps:

1) Copy https://github.com/open-sdg/open-sdg/blob/master/_includes/header.html
2) Change line 12 src to: "{{ site.baseurl }}/assets/img/logo/{{ page.language }}/SDG_logo.png" alt="{{ page.t.general.sdg }} - {{ page.t.header.tag_line }}"
3) Override the header in your repo by placing a new version in your site repository, in the _includes folder.
4) Create a folder and place your logos in sdg-site repo: your_repo/assets/img/logo/en (and separate folders for other languages)
5) Create a folder and place your high-contrast logos in sdg-site repo: your_repo/assets/img/high-contrast/logo/en (and separate folders for other languages)
6) Commit and enjoy

### PR DESCRIPTION
**Pull request by brockfanning**
Q | A
--- | ---
Feature branch/test site URL | [Link](add link here)
Fixed issues | Fixes #1031 
Related version | 1.4.0-dev
Bugfix, feature or docs? | Feature
Keeps backward-compatibility? |✔️
Includes tests? |✔️
Updated docs? |✔️
Updated config forms? |✔️
Added CHANGELOG entry? |❌

Depends on https://github.com/open-sdg/jekyll-open-sdg-plugins/pull/86

EDIT:
Instructions for testing:

- Create feature branch with 2 languages
- Point feature branch at logo-per-language for open-sdg **and** jekyll-open-sdg-plugins (in Gemfile)
- Follow instructions in doc file in Files changed tab

### CODE REVIEW

**Comment by LucyGwilliamAdmin** [comment]
@brockfanning does the conflict need to be resolved before this is tested?

**Comment by jwestw** [comment]
I've created a [branch of a multi-language branch of the repo](https://github.com/ONSdigital/sdg-indicators/tree/logo-per-language). However because that's an old version of the code, I am trying to merge 1.3.0 Develop into it. 

If that doesn't work I will go the other route, i.e. starting with 1.3.0 Dev and making it into a multi-language site. I thought I would start with the other route though because I remember there being quite a few things to change to get it into a multi-language site. Now I write this though I am wondering if the process has become easier since then. @LucyGwilliamAdmin Could you confirm either way?

**Comment by brockfanning** [comment]
Just a note that the automated tests will fail here because it depends on a jekyll-open-sdg-plugins PR.

**Comment by LucyGwilliamAdmin** [comment]
@jwestw nothing has changed re. creating multlingual site

**Comment by jwestw** [comment]
Okay I have successfully (I think) managed to merge 1.3.0 into my [logo-per-language branch](https://github.com/ONSdigital/sdg-indicators/tree/logo-per-language).

@LucyGwilliamAdmin The feature branch server should have built feature branch but it hasn't come through yet. I don't have any visibility over its processes so I am just wondering if that's going to happen or if I have overlooked something that I need to change.

**Comment by LucyGwilliamAdmin** [comment]
@jwestw if feature branch doesn't display after a while, one avenue to check is Actions tab to see if checks passed: https://github.com/ONSdigital/sdg-indicators/actions

**Comment by jwestw** [comment]
The tests did indeed fail. But I am wondering if it is inevitable that they fail given the reasons Brock states in [his above comment.](https://github.com/open-sdg/open-sdg/pull/1140#issuecomment-800229886)

**Comment by jwestw** [comment]
@LucyGwilliamAdmin What's a good way to create a new data branch and indicator branch with lots of languages, while pointing at Brock's code? How about starting from a site and data starter and creating a site data branch that way? Then point the site at the new data branch and its remote theme at `brockfanning:logo-per-language` ?

**Comment by LucyGwilliamAdmin** [comment]
@jwestw yes, to test you need both a data branch and site branch for this, similar to what you did with that branch you found, and then that will become your remote_data_prefix.

**Comment by jwestw** [comment]
> @jwestw yes, to test you need both a data branch and site branch for this, similar to what you did with that branch you found, and then that will become your remote_data_prefix.

Thanks @LucyGwilliamAdmin . I already understood that though. 

There seems to be three ways to go on this. 
1) finding an old branch with lots of languages in, updating the code by merging a recent release in (1.3.0 in this case), and pointing at Brock's logo-per-language branch. 
2) starting afresh with site starters and data starters, opting not to remove any languages, adding some data in, and pointing at Brock's logo-per-language branch. 
3) branching from Develop (which only has English) adding more languages (which I think requires changes on both site and data repos, not clear) and pointing at Brock's logo-per-language branch. 

I have been taking the first option so far. I am guessing either 1 or 3 would be best. 

To be clear, these are my questions: (some new questions here)
- Is the approach I am taking (1) okay or should I start again from scratch (2 or 3)? 
- How many languages should the test site have? What are they? 
- How about starting from a site starter and data starter and creating a site data branch that way? (approach 2)
- If not, should I branch from Develop and add languages back in. (Approach 3)

**Comment by LucyGwilliamAdmin** [comment]
@jwestw thanks for clarifying

- Approach 1 is fine - I've just found this site branch which has the required language files if you want to make use of that (will need to be upgraded though): https://github.com/ONSdigital/sdg-indicators/tree/language-toggle-1
- As long as you have at least 2 languages, it doesn't matter how many or what ones you use. However the more you use, the more complex it will be. If you are going to make use of `language-toggle-1` then that's using french and russian so you would need to continue with those languages.
- Approach 2 and 3 would also work. Approach 2 has the most re-usability and approach 3 would be most long-winded.

**Comment by jwestw** [comment]
@LucyGwilliamAdmin thanks again for your input!

My repo, [logo-per-language](https://github.com/ONSdigital/sdg-indicators/tree/logo-per-language) is branched from [language-toggle-2](https://github.com/ONSdigital/sdg-indicators/tree/logo-per-language).  As I failed to express clearly in the [comment above](https://github.com/open-sdg/open-sdg/pull/1140#issuecomment-800923550) the data branch that `language-toggle-2` uses, i.e. "http://sdgdev-813006012.eu-west-1.elb.amazonaws.com/data/languages/", has now gone. You get a 404. I have tracked down the repo and have just sent it to rebuild and will work from there.

**Comment by LucyGwilliamAdmin** [comment]
@jwestw that feature branch probably would have got deleted when we had clear out as any branches that hadn't been changed within the last 100 days were deleted. Rebuilding the branch is the right thing to do!

**Comment by jwestw** [comment]
Good. :) 

After attempting to rebuild I found my logo-per-language data branch I found it was failing tests.  

So I decided to merge develop into , which I did locally to sort out the merge conflicts. 

I kept the languages in the config the same (this was one of the conflicts I chose not to accept). 

The tests are now passing so http://sdgdev-813006012.eu-west-1.elb.amazonaws.com/data/languages/ shows an overview of the data as expected. 

Now pointing the site branch at this updated data branch and the site is showing http://sdgdev-813006012.eu-west-1.elb.amazonaws.com/logo-per-language/

Images are not showing up at this point, so I am looking into that now.

**Comment by jwestw** [comment]
@brockfanning Please can you clarify, does "Point feature branch at logo-per-language for open-sdg and jekyll-open-sdg-plugins (in Gemfile)" mean that I change the line

`gem "jekyll-open-sdg-plugins", "1.3.0"`

to

`gem "jekyll-open-sdg-plugins", "logo-per-language"`

or something else?

**Comment by brockfanning** [comment]
@jwestw No, to point a Gemfile at a Git branch you need to use this syntax: https://github.com/open-sdg/open-sdg/blob/1.4.0-dev/tests/site/Gemfile#L7

**Comment by jwestw** [comment]
okay, @brockfanning @LucyGwilliamAdmin I have made the changes to the gem file and attempted to resolve other errors that I was seeing on tests via about 2 million commits. 

After a hard refresh the [feature branch](http://sdgdev-813006012.eu-west-1.elb.amazonaws.com/logo-per-language/) seems to be working.

**Comment by jwestw** [comment]
I could also make use of some different logo files to test that it is pointing to the correct one.

**Comment by LucyGwilliamAdmin** [comment]
@jwestw that's great - thanks for testing. Re. goal images - don't worry too much about that - iwe have a config setting which says to use svg images but they aren't available in anything but English. I think as long as you can see that the image source is changing in the inspect column, no need to swap images

**Comment by brockfanning** [comment]
Just explaining my latest commits - I forgot some documentation, but didn't change anything functionality-wise. Since it seems like this is heading towards approval, I'll also merge the jekyll-open-sdg-plugins branch and re-run the tests.

**Comment by brockfanning** [comment]
Ok cool, tests are passing now.

**Comment by jwestw** [comment]
Just confirming, Russian and French logos are at:

http://sdgdev-813006012.eu-west-1.elb.amazonaws.com/logo-per-language/assets/img/ru/SDG_logo.png
and
http://sdgdev-813006012.eu-west-1.elb.amazonaws.com/logo-per-language/assets/img/fr/SDG_logo.png

**Review by jwestw — APPROVED** [review]
Approving according to tests.

**Pull request merged**
