### PR TITLE
Default mouse cursor on disabled elements

### LINKED ISSUE #850: Ensure disabled components are clear to screen readers
**Page 144 in DAC report**

**Issue from DAC report:**
Colour alone is used to indicate that the button is disabled. Low vision users reliant on alternative colour schemes could not identify why the button was not functioning.

Additionally, the mouse pointer changes to a hand which serves as a visual cue to low vision users to indicate this element is clickable.

**Solution from DAC report:**
Ensure that the mouse pointer does not change for disabled components.

```
CSS:
*[disabled], *[aria-disabled="true"] {
cursor: default;
}
```
Please consider including some text in the label to describe that a button is disabled.

**Example from DAC report:**

```
<button id="clear" aria-disabled="true" class="disabled">Clear selections (button disabled)<i class="fa fa-remove"></i></button>
```

image

### PR DESCRIPTION
**Pull request by brockfanning**
Fixes #850 (partially)

Still under discussion at #850.

### CODE REVIEW

**Comment by LucyGwilliamAdmin** [comment]
@brockfanning I think from what DAC said in their latest reply (see comment on #850: https://github.com/open-sdg/open-sdg/issues/850#issuecomment-690294277), the mouse change will be inlcuded with the `disabled="disabled"` attribute

**Comment by brockfanning** [comment]
@jwestw @LucyGwilliamAdmin This is ready again for review.

**Comment by jwestw** [comment]
Feature branch refreshed: http://sdgdev-813006012.eu-west-1.elb.amazonaws.com/jw-test-disabled-button-fixes

**Comment by jwestw** [comment]
Now says "[something] button not available".

**Review by jwestw — APPROVED** [review]
Approving based on previous comments and review of code.

**Pull request merged**
