### PR TITLE
High contrast cookie modal

### PR DESCRIPTION
**Pull request by brockfanning**
Q | A
--- | ---
Feature branch/test site URL | [Link](http://uk-sdg-feature-branches.s3-website.eu-west-2.amazonaws.com/feature-site-cookie-modal-accessibility/)
Fixed issues | Fixes #ISSUENUMBER
Related version | 1.6.0-dev
Bugfix, feature or docs? |
* [ ] Keeps backward-compatibility
* [ ] Includes tests
* [ ] Updated docs
* [ ] Updated config forms
* [ ] Added CHANGELOG entry

### CODE REVIEW

**Comment by christoph-LSN** [comment]
@brockfanning 

looks good....

image

**Comment by LucyGwilliamAdmin** [comment]
@brockfanning is further review required for this?

**Comment by brockfanning** [comment]
@LucyGwilliamAdmin No I don't think so, that screenshot shows it well.

**Comment by LucyGwilliamAdmin** [comment]
@brockfanning do you think the colour of the toggles and button need to be changed?

**Comment by brockfanning** [comment]
@LucyGwilliamAdmin Maybe yes - like a black background on the toggles and a yellow background with black text for the button?

**Comment by brockfanning** [comment]
@LucyGwilliamAdmin Here is an updated screenshot:

image

**Comment by sarah-beasley** [comment]
Make outline white with black in the box. Colour of toggle - should change between on and off. OFF - Add a white border around the toggle and keep circle white with black infill. ON - Make the opposite so black circle and white infill (no border)

**Comment by christoph-LSN** [comment]
@brockfanning @LucyGwilliamAdmin can someone merge this into 2.1.0-dev?
I still get this when looking at the cookie setings in high contrast mode: 

image

**Comment by brockfanning** [comment]
@christoph-LSN We tweaked this a bit - would you have time to give it another try and maybe post a screenshot?

@sarah-beasley @otis-bath This could also be tested against the UK platform - that would be good, even though the UK platform does not use this - as it would confirm whether these changes might affect the UK's custom cookie stuff. So, a feature branch would be good here.

**Comment by christoph-LSN** [comment]
@brockfanning looks good

image

image

**Comment by otis-bath** [comment]
@brockfanning - testing this feature, it is causing some of our images to not display properly
image

**Comment by LucyGwilliamAdmin** [comment]
@otis-bath I think the logo isn't showing because we're overwriting files. I think you need to look at the what's being overwritten for GDS cookies here and remove the overwritten file/code so can test: https://github.com/ONSdigital/sdg-indicators/tree/feature-site-cookie-modal-high-contrast#readme

**Comment by brockfanning** [comment]
@LucyGwilliamAdmin Actually I was hoping to see a feature branch with your normal cookie setup, just to confirm that these changes don't affect your styling. A second feature branch to show these actual changes (with the cookie overrides removed) would be fine too, although there is a screenshot posted above showing that.

@otis-bath I think the logo image problem is a weird interaction with our javascript which tries to switch out the normal and high-contrast images. The problem is that the feature branch has "high-contrast" in the URL, and so our javascript is messing up the path to that image. If you want to confirm that theory, you could make a new feature branch but call the branch something else, like "feature-site-cookie-modal-accessibility".

**Comment by LucyGwilliamAdmin** [comment]
@brockfanning ahh right, sorry I misunderstood what was happening!

Didn't we decide we would have the high contrast toggle like the toggle here: https://uk-sdmx-api-platform.github.io/site/3-2-1/ (put in high contrast mode)

**Comment by brockfanning** [comment]
Ah, that's right - I'll give it another try.

**Comment by LucyGwilliamAdmin** [comment]
@brockfanning Are the two toggles different colours here: 
image

**Comment by otis-bath** [comment]
Okay great thank you @brockfanning @LucyGwilliamAdmin - have updated the link and without the cookie overrides this sorts the UK site. If we are happy with the designs above this can be approved

**Review by otis-bath — APPROVED** [review]

**Pull request merged**
