### PR TITLE
Reporting status for any metadata field

### LINKED ISSUE #209: Allow reporting status to be viewed by other things than just by Goal
When in Kyrgyzstan we were asked if it would be possible to display reporting status by ministry (so that they can hold them accountable) I have mocked this up here (only visually, not code):
[reportingstatus.docx](https://github.com/open-sdg/open-sdg/files/3314833/reportingstatus.docx)

Could we implement this? Or something similar which would allow countries to configure they're own reporting status by X page e.g. by Tier

### PR DESCRIPTION
**Pull request by brockfanning**
Fixes #209 

This depends on a PR in sdg-build: https://github.com/open-sdg/sdg-build/pull/80

## How it works

First, the data repository needs to be configured to include extra fields in the reporting stats. For info on that see the [other PR](https://github.com/open-sdg/sdg-build/pull/80).

Once that's done, nothing special needs to be done here. When the site repo is built next it will automatically pick up the extra fields. The reporting status page will display the goals as usual, but will also have separate tabs for each of the extra fields.

Translation note: Any extra fields included will need to be translated under the "metadata_fields" group (as in `page.t.metadata_fields.my_extra_field`).

reporting-status-extra-field

### CODE REVIEW

**Comment by brockfanning** [comment]
Hi @LucyGwilliamAdmin I added some notes in the other PR: https://github.com/open-sdg/sdg-build/pull/80

The extra fields have to be configured in the data repository, and it depends on an open PR in sdg-build.

**Comment by LucyGwilliamAdmin** [comment]
@brockfanning ah right, I did see the other PR and add that code but missed that I needed to change something on the bottom line.

I've just done that [here](https://github.com/ONSdigital/sdg-data/blob/open-sdg-master-data/scripts/output.py#L8) but the field doesn't seem to be displaying on the [feature branch](http://sdgdev-813006012.eu-west-1.elb.amazonaws.com/open-sdg-master/reporting-status/)

**Comment by LucyGwilliamAdmin** [comment]
@brockfanning Ok, I've managed to get the other tab to display now (see [feature branch](http://sdgdev-813006012.eu-west-1.elb.amazonaws.com/open-sdg-master/reporting-status/))

Looks good - the only issue I can see is that the number of indicators available for each breakdown isn't in a box (link on status by goal).

Also for consistency do we want all of the tab names to be 'Status by extra_field_name'?

**Comment by brockfanning** [comment]
Great, I'll try to get that box on there.

I'm also going to confirm that everything looks the same as before, if there are no extra fields. I worry that it may still try to render tabs, even when there are no extra fields.

I agree that having "Status by" in all the tabs would be nice for consistency. I'll think on how that might work translation-wise.

**Comment by LucyGwilliamAdmin** [comment]
I guess one way around the translations would be to have a drop down rather than tabs e.g, have 'Status by' and then next to it a dropdown (similar to the one used for changing language). I guess that this would also be future proof as if a country ends up with lots of different extra fields, there wouldn't be loads of tabs?

**Comment by brockfanning** [comment]
@LucyGwilliamAdmin @SavvasStephanides This is ready again for testing. I added a quick Google translation of "status by %field" [here](https://github.com/open-sdg/translations-open-sdg/commit/f34bd907979b208abfc5af4ec448d3227c823e06), which I'm passing the translated metadata field name to.

**Comment by LucyGwilliamAdmin** [comment]
@brockfanning I've tried testing this again but I seem to be having an issue - all of the checks are passing but the other fields don't seem to be showing on the reporting status page.

[Feature branch](http://sdgdev-813006012.eu-west-1.elb.amazonaws.com/reporting-status-extra-fields/reporting-status/)
[Data branch](https://github.com/ONSdigital/sdg-data/tree/reporting-status-fields) - added config file and specified extra fields in there
[Site branch](https://github.com/ONSdigital/sdg-data/tree/reporting-status-fields)

**Comment by brockfanning** [comment]
@LucyGwilliamAdmin The extra tabs are there, but they're invisible because they're not getting text. If you hover around you can find them and click.

To get the text to show up, try changing the URL in [this line](https://github.com/ONSdigital/sdg-data/blob/fd2615fc3755599f25ce4b6a5ef994e6a37c378f/config_data.yml#L20) to read:
```
https://github.com/open-sdg/translations-open-sdg.git@1.0.0-rc2
```

(rc2 instead of rc1)

I just added those "status by %field" translations, so I had to create new tag for them.

**Comment by LucyGwilliamAdmin** [comment]
@brockfanning thanks so much - that worked!

**Comment by LucyGwilliamAdmin** [comment]
This looks really good now - not to be picky but is it possible for 'indicators' to be changed to 'indicator' when there is only one indicator in a group within a field to save it from saying '1 indicators'?

**Comment by brockfanning** [comment]
@LucyGwilliamAdmin Just gave that a quick try - can you test?

**Comment by brockfanning** [comment]
@LucyGwilliamAdmin I threw in some quick documentation about this [here](https://open-sdg.readthedocs.io/en/latest/reporting-status/). Please give it a read and see if there is anything you would change or add.

**Comment by LucyGwilliamAdmin** [comment]
@brockfanning I think that's good so far! Maybe we should add something about the value being a list of fields which are present in the metadata files?

**Pull request merged**
