### PR TITLE
Fit total number of indicators on one line

### PR DESCRIPTION
**Pull request by LucyGwilliamAdmin**

### CODE REVIEW

**Comment by brockfanning** [comment]
@LucyGwilliamAdmin Small thing, but could you tweak the indentation so it matches the other code?

**Comment by LucyGwilliamAdmin** [comment]
@brockfanning I'm not sure what's happening as when I go to edit it the indents look like they are correct but then when I save they are not

**Comment by brockfanning** [comment]
@LucyGwilliamAdmin I think there is a TAB character in there somewhere. Try removing all the whitespace and only using spaces.

**Comment by LucyGwilliamAdmin** [comment]
Ah yes, that fixed it - thanks!

**Pull request merged**
