### PR TITLE
Architecture diagram

### LINKED ISSUE #40: Architecture diagram
Let's add to the documentation a graphical representation of all the moving pieces in this platform.

### PR DESCRIPTION
**Pull request by brockfanning**
This is an attempt at an architecture diagram in the documentation. It includes tooltips on each item. Here is a screenshot of what this looks like, with one of the tooltips open:

architecture-diagram-draft-3

### CODE REVIEW

**Comment by brockfanning** [comment]
Fixes #40

**Comment by brockfanning** [comment]
@dougmet @AnnCorp @Norric1Admin Here is an updated screenshot, with the automation/hosting more clearly split into two separate pieces. Also, since I can't include all the tooltips in one screenshot, here is the text of all the tooltips (for review purposes):
* Open SDG: Open SDG provides the core layouts, styling, and functionality for your site. This is a Jekyll theme designed to be easily customised if needed.
* SDG Translations: SDG Translations provides translations of all the text used on your site. This is a stand-alone project which can be forked and extended to translate any implementation-specific text as needed.
* Site repository: This contains all the content, configuration, and customisations that are specific to your implementation. A starter template is available here. This functions as your own custom Jekyll site.
* Prose.io: Prose.io is a free cloud service that allows for user-friendly editing of the data and metadata files. This functions as a data management system for curating the statistics in the platform.
* SDG Build: SDG Build handles the requisite pre-processing of your data and metadata. This is a stand-alone library which does not require customisation.
* Data repository: This contains all the data and metadata for your implementation. A starter template is available here. Data and metadata imports, validation, and pre-processing are all handled here.
* Tooltip between data-repo and site-repo: The data is imported into the site at build time, which allows the platform to display data even without javascript.
* Automation tool: Any automation tool, such as CircleCI or TravisCI, handles the deployment of the repository to a hosting provider.
* Hosting provider: Any hosting provider, such as Github Pages or Amazon S3, will receive the uploaded files to serve them as a static website.

architecture-diagram-draft-4

**Comment by dougmet** [comment]
Thanks Brock, this looks good.

It's kind of ugly but the link from between data is probably in the wrong place. It should go from the data hosting provider up to the site automation tool. The hosted data is used at build time of the site.

**Comment by dougmet** [comment]
And this tooltip:

> Tooltip between data-repo and site-repo: The data is imported into the site at build time, which allows the platform to display data even without javascript.

Could be:

> Tooltip between data-repo and site-repo: The metadata and headline data is imported into the site at build time, which allows the platform to display data even without javascript.

The main data sets are not imported at build time.

**Comment by Norric1Admin** [comment]
[draft](https://share.sp.ons.statistics.gov.uk/sites/SusIneq/SDG/Sample/NRP/Development/Architecture%20diagram.pdf)

**Comment by dougmet** [comment]
I can't access this -- is it behind your firewall?

**Comment by Norric1Admin** [comment]
@dougmet  Apologies, try [this](https://github.com/Norric1Admin/sdg-indicators/blob/develop/Architecture%20diagram.pdf).

**Comment by dougmet** [comment]
Hi @Norric1Admin yes I like this too. It's a nice more zoomed in diagram. One addition is that in between the green "Data and Metadata Files" and the "Data Service" boxes, we need another CI build box, just like the one on the left.

I think that's important because we don't just serve the files, we process them too, during the build.

**Comment by dougmet** [comment]
And in terms of colour coding I'd make the "Data Service" boxes the same colour as the "Host" box. Then it's clear what is a build and what is a service.

**Comment by brockfanning** [comment]
@dougmet @Norric1Admin I agree with adding detail, though I think it's important to keep it simple enough for someone who is totally new to the platform. This is partly my thinking in the bare-bones flowchart, with more detail via "tooltips" and links. A couple other notes:
* We should keep in mind also that this is intended to be country-agnostic (so for example we wouldn't expect to see references to ONSDigital, etc.)
* I don't think we need to reference previous or changed names ("sdg-indicators")

Based on the great feedback so far I've revamped this PR a bit, to make the flowchart more accurate and the colors more meaningful. Rather than posting screenshots and lots of tooltip text, here is a Codepen so you can see it in action: https://codepen.io/brockfanning/pen/zyQgxY

(FYI you can also try it locally by checking out this branch and running `mkdocs serve`)

**Pull request merged**
