### PR TITLE
Fix title tag on goal page

### LINKED ISSUE #359: Title tags on goal pages lack the short name
The `<title>` tag in the `<head>` on goal pages is missing the short name. Ie, instead of `Goal 1 - End poverty in all its forms everywhere` it just has `Goal 1 -`.

### PR DESCRIPTION
**Pull request by LucyGwilliamAdmin**
Fixes #359

Feature branch: https://sdg.mango-solutions.com/title-fix/1/

### CODE REVIEW

**Comment by LucyGwilliamAdmin** [comment]
@brockfanning do we want a minor release for this?

**Comment by brockfanning** [comment]
@LucyGwilliamAdmin We could - it is technically a bug, albeit a smallish one.

**Comment by LucyGwilliamAdmin** [comment]
So can we add to 0. 9.0?

**Comment by brockfanning** [comment]
Right now I think this would be a "hotfix" release, 0.9.2.

**Comment by brockfanning** [comment]
Ok @LucyGwilliamAdmin I just pushed a tag for 0.9.2.

**Comment by LucyGwilliamAdmin** [comment]
Thanks for doing this. Was going to do it when I return to UK

**Pull request merged**
