### PR TITLE
Map fullscreen accessibility

### PR DESCRIPTION
**Pull request by brockfanning**
Fixes the parts of #936 and #937 that have to do with the fullscreen button.

### CODE REVIEW

**Comment by jwestw** [comment]
Feature branch: http://sdgdev-813006012.eu-west-1.elb.amazonaws.com/jw-test-fix-hierarchical-field-sorting

**Comment by jwestw** [comment]
The same problem is occuring on this feature branch: 

image
NOTE: this is **before** I am changing _config.yml 

However, it is not occuring on https://sdgdata.gov.uk/
image

**Comment by jwestw** [comment]
All tested in Windows high contrast mode. 

Chrome does not respond to Windows high contrast mode, and has its own plug-in called "High Contrast". Using this plug-in it looks like this:

image

This is something like the expected behaviour but this does not seem to be as a result of a fix because on https://sdgdata.gov.uk/3-a-1/ we can also see: 

image

So it seems it was never a problem with this browser/plugin-combo

Both Edge and IE respond to Windows high contrast mode. 

Edge is the best:

image

All the icons in buttons except the search icon are appearing. The search icon does appear in grey if you hover over it however (you can't see my mouse pointer on this screenshot, but it was over the search button). 

IE is pretty bad. 

image

As you can see nothing is fixed and I think it is worse than the originally reported problem as the other buttons' characters have disappeared:

image

As @brockfanning  has pointed out before, Windows High Contrast + IE might be a bit of an edge case. Can we advise people to use Chrome?

**Comment by LucyGwilliamAdmin** [comment]
@brockfanning @jwestw as this is working in Edge and IE with WHCM, I'm sending to DAC for sign-off

**Review by LucyGwilliamAdmin — APPROVED** [review]

**Pull request merged**
