### PR TITLE
Translate mobile search buttons

### LINKED ISSUE #649: Mobile: search toggle reverts to English
When looking at a non-English implementation on a phone, when you touch the search toggle, it shows "Hide" (in English). And when you toggle back, it shows "Search" (in English).

### PR DESCRIPTION
**Pull request by brockfanning**
Fixes #649

### CODE REVIEW

**Comment by brockfanning** [comment]
I wonder if we're seeing different things - for me, what should be displaying "Hide" is showing up blank. I'm not sure why that would happen though.

**Comment by LucyGwilliamAdmin** [comment]
Sorry, I just rechecked - I'm also missing "Hide" - thought I was just checking that Search had been translated

**Comment by brockfanning** [comment]
Similar to #758 I am wondering if there is some reason the latest sdg-translations code may not be getting through. A few days ago I merged translations of "hide" in the "general" group. A way to test this would be to open the developer console and type: "translations.general.hide". But it appears blank, so for some reason that translation is not coming through.

**Comment by LucyGwilliamAdmin** [comment]
Ahh, I probably need to change the data config file - I'll try that now

**Comment by LucyGwilliamAdmin** [comment]
@brockfanning rebuilt data and then the site and Hide is showing for me now:
https://github.com/LucyGwilliamAdmin/sdg-site-quick-start/actions

**Comment by brockfanning** [comment]
Great!

**Pull request merged**
