### PR TITLE
Dropdowns in the main menu

### PR DESCRIPTION
**Pull request by brockfanning**
This allows for dropdowns in the main menu. This can be done by adding a "dropdown" entry inside the normal menu item configuration, like so:

```
menu:
  - translation_key: My dropdown menu
    dropdown:
      - path: my-page
        translation_key: My first dropdown item
      - path: my-other-page
        translation_key: My other dropdown item
```

For an updated configuration form this depends on this PR: https://github.com/open-sdg/jekyll-open-sdg-plugins/pull/67

EDIT: [feature branch](http://sdgdev-813006012.eu-west-1.elb.amazonaws.com/dropdown-menus/)

### CODE REVIEW

**Comment by MoBosse** [comment]
I copied all necessary code elements from this PR to this [Repo](https://github.com/SdgTestEnvironment/sdg-indicators) and it works perfectly! Thanks @brockfanning !

**Comment by jwestw** [comment]
Since MoBosse has tested this I am thinking it doesn't need testing again. @brockfanning would you agree?

**Comment by brockfanning** [comment]
@jwestw Agreed. I think we'll discuss in more detail how to handle tickets like this tomorrow.

**Comment by jwestw** [comment]
Please let me know if this one needs a feature branch, additional testing or code review.

**Comment by LucyGwilliamAdmin** [comment]
@brockfanning is there anything left for this one?

**Comment by brockfanning** [comment]
@LucyGwilliamAdmin Nothing left needs to be done, development-wise. Though this one has not been slated yet to go into the platform. I wrote this because at least one country needs dropdowns, and they have to override a lot in order to get it, which is making it difficult for them to upgrade. Maybe this could be discussed more if you think it should go in.

**Comment by LucyGwilliamAdmin** [comment]
@phillipgardiner @brockfanning I've just added link to feature branch to description for this

**Comment by phillipgardiner** [comment]
@LucyGwilliamAdmin @brockfanning As you know this has not been through any kind of usability testing etc, but the design and function seems logical. One point of mention though, is will this be going to DAC? I just wonder if the highlight colour used on the sub menu might fail accessibility contrast ratios?

**Comment by brockfanning** [comment]
@phillipgardiner I agree that looks pretty light - I had intended to match the language toggle, but now that I compare them it seems lighter. Let me try darkening that text.

**Comment by LucyGwilliamAdmin** [comment]
@brockfanning @phillipgardiner re. this going to DAC I think @AnnCorp  mentioned that if ready we may ask them to take a look even though it's not going on UK site. I think she said she'll have a think

**Comment by brockfanning** [comment]
@LucyGwilliamAdmin Would mind refreshing the feature branch? I've done a bit of refactoring to make the styling more consistent with the language dropdown. I've also pulled in the latest code from the 1.3.0-dev branch.

**Comment by LucyGwilliamAdmin** [comment]
@brockfanning @phillipgardiner Feature branch has been refreshed

**Comment by phillipgardiner** [comment]
@brockfanning @LucyGwilliamAdmin Looks good to me.

**Review by LucyGwilliamAdmin — APPROVED** [review]
Works and looks good with approval from Phill also

**Pull request merged**
