### PR TITLE
Previous/next links on indicators and goals

### LINKED ISSUE #632: Add navigation between goal pages

### PR DESCRIPTION
**Pull request by brockfanning**
Fixes #632 

These translations have been added (English only so far):

* indicator.previous (Previous indicator)
* indicator.next (Next indicator)
* goal.previous (Previous goal)
* goal.next (Next goal)

Actually "goal" was not yet a group in sdg-translations. We've been throwing goal-related things into the "general" group. But I thought we should create a "goal" group and eventually move things over there.

This also depends on a jekyll-open-sdg-plugins branch: https://github.com/open-sdg/jekyll-open-sdg-plugins/pull/62

The configuration to turn this on is something like this for goals:

```
create_goals:
  layout: goal
  previous_next_links: true
```

And something like this for indicators:

```
create_indicators:
  layout: indicator
  previous_next_links: true
```

Note that the automated tests will fail until https://github.com/open-sdg/jekyll-open-sdg-plugins/pull/62 is merged.

[Feature Branch](http://sdgdev-813006012.eu-west-1.elb.amazonaws.com/previous-next-buttons)

### CODE REVIEW

**Comment by brockfanning** [comment]
Ongoing discussion is in #632, and this PR still needs work according to what is decided there.

**Comment by jwestw** [comment]
`I am putting the [feature branch](http://sdgdev-813006012.eu-west-1.elb.amazonaws.com/previous-next-buttons) in the top comment as I have been asked to do.

**Comment by brockfanning** [comment]
@jwestw This is one that depends on a jekyll-open-sdg-plugins change, so the Gemfile would need to be changed to `gem 'jekyll-open-sdg-plugins', git: 'https://github.com/brockfanning/jekyll-open-sdg-plugins.git', branch: 'previous-next-buttons'`. It also needs some config changes, and I've just added those to the description. I should note though that this ticket is not in the 1.3.0 project, so you don't need to spend your time on this (unless you want to!).

**Comment by LucyGwilliamAdmin** [comment]
@AnnCorp @phillipgardiner this one isn't currently in 1.3 - I think these buttons may have come up either in expert review or some usability testing? 

Should it be added to 1.3?

**Comment by phillipgardiner** [comment]
@LucyGwilliamAdmin @AnnCorp  these were mentioned in a previous expert review but then not found as a requirement for the UK during usability testing (see notes in #632). I think this was implemented as other countries requested it.

**Comment by LucyGwilliamAdmin** [comment]
@brockfanning I think we discussed this one last week and decided to make it optional - does that mean there's more to do here?

**Comment by brockfanning** [comment]
@LucyGwilliamAdmin I believe this should already be optional - it depends on that `previous_next_links` configuration in `create_goals` and/or `create_indicators`.

**Comment by jwestw** [comment]
This all seems to work 

## Indicators

image

## Goals 

image

## Also working in High Contrast (selected on site, in Chrome)

image

## Windows high contrast, in Edge

image

**Review by jwestw — APPROVED** [review]
According to last comments I am happy to approve.

**Pull request merged**
