### PR TITLE
Update metadata-format.md

### PR DESCRIPTION
**Pull request by WohnungNDS**
Q | A
--- | ---
Feature branch/test site URL | [Link](add link here)
Fixed issues | Fixes #ISSUENUMBER
Related version | 1.4.0-dev
Bugfix, feature or docs? |
Keeps backward-compatibility? |❌/✔️
Includes tests? |❌/✔️
Updated docs? |❌/✔️
Updated config forms? |❌/✔️
Added CHANGELOG entry? |❌/✔️

### CODE REVIEW

**Comment by LucyGwilliamAdmin** [comment]
@WohnungNDS thanks for the PR - we actually have the `decimal_separator` field documented but as it is a site-wide option it's on the Site configuration page:
https://open-sdg.readthedocs.io/en/latest/configuration/#decimal_separator

**Comment by WohnungNDS** [comment]
Ah OK, I haven't found it.... But it make sense that is in the site configuration page....

**Comment by LucyGwilliamAdmin** [comment]
@WohnungNDS it is at that link: https://open-sdg.readthedocs.io/en/latest/configuration/#decimal_separator

Can we close this one?

**Comment by LucyGwilliamAdmin** [comment]
Closing as`decimal_separator` is already documented

**Pull request closed without merging**
