### PR TITLE
Outline-only focus on disaggregation control dropdowns

### LINKED ISSUE #1053: Highlight only the outline of drop downs  - on focus
On the gov.uk implementation of drop downs: https://design-system.service.gov.uk/components/select/. When a drop down is focused, it is only the outline of the drop down that highlighted (see fig 1). SDG currently highlights the whole drop down. (See fig 2)

Fig1
Screenshot (98)

Fig 2
Screenshot (99)

Recommendation: Implement the GDS on focus style

### PR DESCRIPTION
**Pull request by brockfanning**
Q | A
--- | ---
Feature branch/test site URL | [Link](https://lucygwilliamadmin.github.io/sdg-indicators/1-2-1/)
Fixed issues | Fixes #1053 
Related version | 1.4.0-dev
Bugfix, feature or docs? | Feature
Keeps backward-compatibility? |✔️
Includes tests? |NA
Updated docs? |NA
Updated config forms? |NA
Added CHANGELOG entry? |❌

### CODE REVIEW

**Comment by LucyGwilliamAdmin** [comment]
@brockfanning @phillipgardiner link added - looks good to me though

**Comment by phillipgardiner** [comment]
@LucyGwilliamAdmin @brockfanning Looking good. I'd tend to agree. If you look at the GDS version the yellow box sits outside of the border. It also seems to change the border thickness, but I'm not sure what the reasoning behind that is.

https://design-system.service.gov.uk/components/select/

**Comment by LucyGwilliamAdmin** [comment]
@brockfanning how much effort is it to make the change mentioned above?

**Comment by brockfanning** [comment]
@LucyGwilliamAdmin I've just pushed to a quick commit to give that a try. Changing the thickness of the border on focus would be a bit more tricky, because usually that affects the layout slightly and makes it look like everything is shifting. Feedback is welcome.

**Review by LucyGwilliamAdmin — APPROVED** [review]
Looks great - link has been updated

**Comment by phillipgardiner** [comment]
@brockfanning @LucyGwilliamAdmin Should this still display? Went in to have a look via the link and I see the old style?

**Comment by LucyGwilliamAdmin** [comment]
Sorry @phillipgardiner I switched the branch to check something else - it should be showing this now

**Comment by phillipgardiner** [comment]
@LucyGwilliamAdmin @brockfanning No problem, looks good.

**Pull request merged**
