### PR TITLE
Support for Chart.js annotations

### LINKED ISSUE #913: Target lines
**Is your feature request related to a problem? Please describe.**

The Open SDG platform shows the current status of the indicators, but not the progress towards the 2030 goal.

**Describe the solution that you need**

There needs to be some way to draw a "target line" on the charts, representing the 2030 goal for that indicator.

**Why do you need this feature?**

This is needed to allow Open SDG to show progress.

**Describe alternatives you've considered**

Possible more advanced functionality in the future may include year-by-year targets, but for now let's just get a straight line on chart representing the end (2030) goal.

### PR DESCRIPTION
**Pull request by brockfanning**
Fixes #913 

Here is a variety of indicator metadata changes that you could make to test the various parts of this. You may need to tweak the "value" settings to work with whatever indicator you're testing it on. To save time it's probably best to make each change to a different indicator, so you can test them all on the same feature branch.

1. Confirm that a target_line annotation works:

```
graph_annotations:
  - preset: target_line
    value: 10
```

2. Confirm that a vertical line works:

```
graph_annotations:
  - mode: vertical
    borderDash: [5, 5]
    value: 0.5
    label:
      position: top
      content: My label text
```

3. Confirm that you can override the label of the target_line annotation:

```
graph_annotations:
  - preset: target_line
    value: 10
    label:
      content: My label text
```

4. Confirm that the label text can be translated (here using an arbitrary translation key):

```
graph_annotations:
  - preset: target_line
    value: 10
    label:
      content: indicator.loading_map
```

5. Confirm that a line can have a different start/end value:

```
graph_annotations:
  - preset: target_line
    value: 10
    endValue: 15
```

6. Confirm that an annotation can be different per unit (tweak the units to whatever makes sense for the indicator data):

```
graph_annotations:
  - preset: target_line
    value: 10
    unit: Percentage
  - preset: target_line
    value: 1000
    unit: Total
```

The "series" functionality should work the same as units, so I'm not sure if it's worth the effort of testing at this point.

### CODE REVIEW

**Comment by brockfanning** [comment]
@LucyGwilliamAdmin @jwestw This is ready for review - I've got some examples in the PR description to help with configuring the indicator metadata to test this out.

**Comment by jwestw** [comment]
Feature branch: http://sdgdev-813006012.eu-west-1.elb.amazonaws.com/chart-js-target-lines-indicators

At the moment I am just trying out one change, but will work through them all when I have that working!

**Comment by jwestw** [comment]
Hi @brockfanning I couldn't get this working, even with Lucy's help. 

[Indicator 1.1.1](http://sdgdev-813006012.eu-west-1.elb.amazonaws.com/chart-js-target-lines-indicators/1-1-1/) and [Indicator 2.2.2](http://sdgdev-813006012.eu-west-1.elb.amazonaws.com/chart-js-target-lines-indicators/2-2-2/) have both been updated. 

1.1.1 was updated with the simplest (first) graph annotation setting you suggested in the ticket itself (Please see the [1.1.1's .md file](https://github.com/ONSdigital/sdg-data/blob/jw-test-chart-js-target-lines/meta/1-1-1.md) ). I used a value of 0.1 so it would be within the min and max of the existing Y axis, but the annotation line didn't show up. And 2.2.2 was updated just exactly as you did in the ['Files Changed'](https://github.com/open-sdg/open-sdg/pull/912/files) of the ticket, so the annotations at Y values 1.1 and 1.3 should show up if that what you had working. 

Lucy has helped me check other settings such as the remote theme and the data prefix settings in the indicator branch. 

For reference:
 - [data branch](http://sdgdev-813006012.eu-west-1.elb.amazonaws.com/data/jw-test-chart-js-target-lines)
- [1.1.1's meta json file](http://sdgdev-813006012.eu-west-1.elb.amazonaws.com/data/jw-test-chart-js-target-lines/en/meta/1-1-1.json) (which shows the updates)
- [2.2.2's meta json file](http://sdgdev-813006012.eu-west-1.elb.amazonaws.com/data/jw-test-chart-js-target-lines/en/meta/2-2-2.json)

**Comment by brockfanning** [comment]
@jwestw It's been a while since we added a new metadata field for Open SDG - I wonder if it needs to be added to the _prose.yml file in the data repo. Can you try adding something like this?

```
name: "graph_annotations"
    field:
        element: hidden
        label: "Graph annotations"
        scope: graph
```

That can go anywhere, such as at the end, when the same indentation as the lines before in.

**Comment by brockfanning** [comment]
@jwestw I created a PR to demonstrate this: https://github.com/ONSdigital/sdg-data/pull/2320

**Comment by brockfanning** [comment]
@jwestw Actually I didn't do this in the local test site, so that is probably not the problem. I'll do some more testing and get back to you.

**Comment by brockfanning** [comment]
@jwestw I believe I see the problem - your feature branch is overriding the scripts.html file, which is one of the files changed in this PR. A quick fix would be to delete that file in your feature branch.

I also opened #950 to hopefully avoid the need for that kind of override in the future.

**Comment by brockfanning** [comment]
@jwestw That quickest way to continue testing this PR is for you to delete the `_includes/scripts.html` from your feature branch, when you have a chance.

**Comment by jwestw** [comment]
Okay that worked. 

Confirm that a target_line annotation works:

on 1.1.1 with value set at 0.1

image

on 2.2.2 with value set at 1.1 and 1.3

image

**Comment by brockfanning** [comment]
Thanks @jwestw so far so good. Are you able to try the other configurations on other indicators?

**Comment by jwestw** [comment]
## What's working:

- **Confirm that you can override the label of the target_line annotation**
On 1.4.2 with label set at "TESTING TESTING LABEL":

image


- **Confirm that an annotation can be different per unit (tweak the units to whatever makes sense for the indicator data):**

On 1.a.2 with 
- unit: Percentage (%) of national budget at value: 40

image

- unit: Percentage (%) of gross domestic product (GDP) at value: 20

image

    
- **Confirm that the label text can be translated (here using an arbitrary translation key):** On 3.2.1 with value of 100 and indicator.loading_map as translation key (which should show "Loading map"

image





## What's not working (yet)

Anything that I have supplied an x value to (possibly incorrectly) is not working. 

- **Confirm that a vertical line works:** On 1.2.2 with line I set the vertical line value at 2015. 
The target line is not appearing at x=2015.
- **Confirm that a line can have a different start/end value** On 1.5.1 with y value of 120 and end (x) value of of 2017
The target line is not appearing at y=120

**Comment by jwestw** [comment]
Finally I have 1.2.2 working with this config:

image

It looks like this:

image

**Comment by jwestw** [comment]
Likewise, 3.3.1 is working with comfig:

image


Which again, looks like this: 

image

**Comment by jwestw** [comment]
Finally, I have 3.4.2 working with the start and end config like this:

image

Which looks like this. 

image


So that means they are all working I think.

However I don't know why [1.5.1](http://sdgdev-813006012.eu-west-1.elb.amazonaws.com/chart-js-target-lines-indicators/1-5-1/) is not working with the following config:

image

**Review by jwestw — APPROVED** [review]
I believe all 6 annotation styles have been tested and have passed.

**Comment by brockfanning** [comment]
@jwestw Thanks for testing that. So maybe I'm wrong about 0 to 1? Maybe it is 0 to the number of years? So if there are 10 years, then it's 0 to 10? I should update the documentation I think.

**Pull request merged**
