### PR TITLE
Related indicators, publications, and sources

### LINKED ISSUE #1733: Add 'Related indicators' and 'Related publications' tab
## Mock-ups:

[Indicators_and_publications_v3.pdf](https://github.com/open-sdg/open-sdg/files/9084470/Indicators_and_publications_v3.pdf)

### Related indicators:

- indicator config field e.g. related_indicators which takes a list of indicators

### Related publications

- indicator config field e.g. related_publications which takes multiple items with options for title, link, description and date

### LINKED ISSUE #1734: Improve sources metadata tab configuration
Instead of having multiple fields for one source we should move to using items e.g.

instead of
```
source_active_1: true
source_organisation_1: House of Commons Library
source_periodicity_1: Discontinuous
source_earliest_available_1: 1918
source_geographical_coverage_1: United Kingdom
source_url_1: https://commonslibrary.parliament.uk/research-briefings/sn01250/
source_url_text_1: Women in Parliament and Government
source_release_date_1: 04/03/2022
source_next_release_1: TBC
source_statistical_classification_1: Official Statistic 
source_contact_1: hcinfo@parliament.uk
source_other_info_1: The underlying data from this report has been acquired from the author.
source_active_2: true
source_organisation_2: House of Lords Library
source_periodicity_2: Discontinuous
source_earliest_available_2: 1958
source_geographical_coverage_2: United Kingdom
source_url_2: https://researchbriefings.parliament.uk/ResearchBriefing/Summary/LLN-2015-0017
source_url_text_2: Women in the House of Lords
source_release_date_2: 30/06/2015
source_next_release_2: TBC
source_statistical_classification_2: Official Statistic
source_contact_2: HLInfo@Parliament.uk
source_other_info_2: The underlying data from this report and more recent data has been acquired from the author.
```

could have:

```
sources:
  - source:  House of Commons Library
    organisation: House of Commons Library
    periodicity: Discontinuous
    earliest_available: 1918
    geographical_coverage: United Kingdom
    url: https://commonslibrary.parliament.uk/research-briefings/sn01250/
    url_text: Women in Parliament and Government
    release_date: 04/03/2022
    next_release: TBC
    statistical_classification: Official Statistic 
    contact: hcinfo@parliament.uk
    other_info: The underlying data from this report has been acquired from the author.
  - source: House of Lords Library
    periodicity: Discontinuous
    earliest_available: 1958
    geographical_coverage: United Kingdom
    url: https://researchbriefings.parliament.uk/ResearchBriefing/Summary/LLN-2015-0017
    url_text: Women in the House of Lords
    release_date: 30/06/2015
    next_release: TBC
    statistical_classification: Official Statistic
    contact: HLInfo@Parliament.uk
    other_info: The underlying data from this report and more recent data has been acquired from the author.

### PR DESCRIPTION
**Pull request by brockfanning**
Fixes #1734 
Fixes #1733 

This relies on another PR: https://github.com/open-sdg/jekyll-open-sdg-plugins/pull/144

The new indicator configuration settings are: `publications`, `related_indicators`, and `sources`. Here is some indicator configuration that can be used to demo all three new settings:

```
publications:
  - title: My publication
    link: "https://www.google.com"
    description: My publication description
    date: August 12th 1953
  - title: My other publication
    link: "https://www.google.com"
    description: Another publication description
    date: January 2022
related_indicators:
  - 1.1.1
  - 1.2.1
sources:
  - organisation: House of Commons Library
    periodicity: Discontinuous
    earliest_available: "1918"
    geographical_coverage: United Kingdom
    url: "https://commonslibrary.parliament.uk/research-briefings/sn01250/"
    url_text: Women in Parliament and Government
    release_date: 04/03/2022
    next_release: TBC
    statistical_classification: Official Statistic 
    contact: hcinfo@parliament.uk
    other_info: "This is *some* markdown."
    logo: "https://onsdigital.github.io/sdg-indicators/assets/img/SDG_logo.png"
  - organisation: Another organisation
    periodicity: Discontinuous
    earliest_available: "2000"
    geographical_coverage: United Kingdom
    url: "https://commonslibrary.parliament.uk/research-briefings/sn01250/"
    url_text: Other link text
    release_date: January 2022
    next_release: December 2022
    statistical_classification: Official Statistic 
    contact: hcinfo@parliament.uk
    other_info: "This is some *other* markdown."
    logo: "https://onsdigital.github.io/sdg-indicators/assets/img/SDG_logo.png"
```

These features also require the use of the `metadata_tabs` site configuration. Here is an example of a `metadata_tabs` configuration that includes all of these:

```
metadata_tabs:
  - scope: national
    title: indicator.national_metadata
    description: indicator.national_metadata_blurb
  - scope: global
    title: indicator.global_metadata
    description: indicator.global_metadata_blurb
  - scope: sources_alt
    title: Sources
    description: My blurb about the sources tab
    placeholder: No sources are available at this time
  - scope: related_indicators
    title: Related indicators
    description: My blurb about the related indicators tab
    placeholder: There are no other indicators related to this one
  - scope: publications
    title: Publications
    description: My blurb about the publications tab
    placeholder: There are no publications available for this indicator
```

Q | A
--- | ---
Feature branch/test site URL | [Link](http://uk-sdg-feature-branches.s3-website.eu-west-2.amazonaws.com/feature-related-indicators-publications-sources/1-2-2/)
Fixed issues | Fixes #1733 and #1734
Related version | 2.1.0-dev
Bugfix, feature or docs? | Feature
* [x] Keeps backward-compatibility
* [x] Includes tests
* [x] Updated docs
* [x] Updated config forms
* [ ] Added CHANGELOG entry

### CODE REVIEW

**Comment by otis-bath** [comment]
Hi @brockfanning, have this on a FB - really like the design and think this looks good, only question is that I removed the old sources metatdata yet the tab still appears. How will this be hidden with the new sources tab design?

**Comment by otis-bath** [comment]
Set metadata tabs configuration (to hide old sources tab) or if new sources code being used then hide old tab. 

Should other fields show up if they are empty - can we make the other fields placeholders? Brock to finish the placeholder ticket and then come back to this 

Sources to be moved to the left of related indicators 

If a country has not configured these do we want them to show. Our approach has always been to maintain consistency and show on all even if some are not present

**Comment by brockfanning** [comment]
@otis-bath This is ready for a refresh now. I've added some docs and tests. Also, this now requires the use of the `metadata_tabs` site config. See the PR description and let me know if anything's not clear.

**Review by otis-bath — APPROVED** [review]
This looks good and the issues from before have been resolved, think there are still a couple of bits to discuss on this at the tech call regarding how the fields are treated. In the meantime do you have any thoughts from a UX perspective @phillipgardiner

**Comment by phillipgardiner** [comment]
A few bits of feedback based on the original mock up,

In regard to 1733

- Tab should be called 'Related Publications'
- The spacing of Title, description and date on the 'related Publications' tab should be the same as that used on the 'Updates' page (e.g. increase spacing between each)
- If no related publications exist the text should read: No related publications exist for this indicator
- If no related publications exist we do not need the sentence: My blurb about the related indicators tab, displayed.

- The word 'Goal' should appear before the Goal number in 'related indicators'
- Bullet points are not required next to each indicator description
- The space between each indicator description should be increased
- If no related indicators exist the text should read: No related indicators exist for this indicator
- If no related publications exist we do not need the sentence: My blurb about the related indicators tab, displayed.

Please see the original mock-up (https://github.com/open-sdg/open-sdg/files/9084470/Indicators_and_publications_v3.pdf) for further detail of the above - thanks

In regard to 1734

- I don't think we need the sentence 'My blurb about the sources tab' is sources exist
- If no sources exist, display '‘No data sources available’ in grey and italics

**Comment by brockfanning** [comment]
@otis-bath This is ready for a refresh. Note that all of the wording issues that @phillipgardiner noted will need to be fixed by adjusting your configuration settings.

**Comment by brockfanning** [comment]
@otis-bath @phillipgardiner Actually if it would save time, we don't technically need to test those wording changes. Because these are configurable, each country could use their own wording.

**Comment by otis-bath** [comment]
@brockfanning @phillipgardiner - So I have taken a look at this and have a couple of observations. 

I have renamed the tab to related publications and if you look at [121](http://uk-sdg-feature-branches.s3-website.eu-west-2.amazonaws.com/feature-related-indicators-publications-sources/1-2-1/) you can see what it looks like when the field is left blank with the greyed out text. I am not 100% sure on how the spacing has changed but any of the blurb text can be customised or removed anyway it's just there to show what it looks like

**Review by phillipgardiner — COMMENTED** [review]
@otis-bath @brockfanning 

Only one small change for me. The space between the publications displayed could be reduced by about half (not sure if this happens at brocks end or locally?).

Additionally I noticed 'Related indicators' has a lower case 'i' and should be upper case 9again not sure if this is a local change?)

@otis-bath As Brock has pointed out there are a number of wording bits that would need to be updated locally (such as the grey text wording), so we must remember to capture these and update at the necessary point.

**Comment by brockfanning** [comment]
@otis-bath There's less space beneath the publications now. I think all labels/wording are configurable, so would be done locally. In fact, this PR no longer needs anything in sdg-translations to change, so I'll close that sdg-translations PR.

**Comment by otis-bath** [comment]
Have refreshed it @phillipgardiner - just check you are happy with the changes? I won't delete the FB so when we come to making the upgrade I will just copy the code across then we can check it all looks good.

**Comment by phillipgardiner** [comment]
@brockfanning Sorry we have just noticed a couple of additional changes required best made for out the box. These are:

1) Can we make the Goal title in the related indicators tab 'Bold'
2) Can the goal titles use the short goal title rather than the long one (e.g. 'No poverty' rather than 'End poverty in all its forms everywhere'

Thanks,

**Comment by brockfanning** [comment]
@otis-bath This is ready for a refresh.

**Comment by otis-bath** [comment]
All refreshed - did you want to take a look @phillipgardiner

**Comment by phillipgardiner** [comment]
@otis-bath @brockfanning Looks great to me - thanks

**Pull request merged**
