### PR TITLE
Refactor and style updates for tags on goal pages

### LINKED ISSUE #373: Proxy tags improvement
Maybe we could make the following improvements to tags:
1. Tags don't split over several lines
2. Stop tags on second line from overlapping

image

### PR DESCRIPTION
**Pull request by brockfanning**
Fixes #373 

Note that this does not affect the tags on the News page, but I think a follow-up ticket to make them consistent would be good. However that should not be started until this PR and #1078 have both been merged.

EDIT: [feature branch](http://sdgdev-813006012.eu-west-1.elb.amazonaws.com/tag-style-updates)

### CODE REVIEW

**Comment by jwestw** [comment]
Here's the [feature branch](http://sdgdev-813006012.eu-west-1.elb.amazonaws.com/tag-style-updates).

@phillipgardiner you will also need to see this one as it's related to #1078.

**Comment by LucyGwilliamAdmin** [comment]
@jwestw see the `tags` metadata field here to display a tag: https://open-sdg.readthedocs.io/en/latest/metadata-format/#recommended-special-fields

**Comment by phillipgardiner** [comment]
@jwestw are there tags visible for to look at, at all?

**Comment by jwestw** [comment]
Here's the [feature branch](http://sdgdev-813006012.eu-west-1.elb.amazonaws.com/tag-style-updates) again with tags applied to 1-1-1 and 1-4-2.

@phillipgardiner please tag a look.

**Comment by phillipgardiner** [comment]
@jwestw Thank you. Looks good to me. Good work @brockfanning

**Review by jwestw — APPROVED** [review]
Approving according to the conversation and checks

**Pull request merged**
