### PR TITLE
Button revamp

### LINKED ISSUE #635: Improve button style to improve clickability
See GDS guidance

### PR DESCRIPTION
**Pull request by brockfanning**
Fixes #635

### CODE REVIEW

**Comment by LucyGwilliamAdmin** [comment]
@jwestw do you want to have a go at creating a feature branch for this and then posting link here so @phillipgardiner can review?

**Comment by jwestw** [comment]
@phillipgardiner Please check the feature branch I made: http://sdgdev-813006012.eu-west-1.elb.amazonaws.com/button_check/

I have looked myself and the changes Brock has made seem to work exactly as needed. Please confirm.

**Comment by phillipgardiner** [comment]
@jwestw Thanks for doing that. @brockfanning looking good, the only thing I spotted was that the gap between buttons is different, is this something that could be made consistent? (see screenshot)
Screenshot (44)_LI

**Comment by brockfanning** [comment]
@phillipgardiner I've pushed a commit that should help with that spacing.

@jwestw My latest change was tricky enough that I would recommend we confirm that the normal button functionality still works. In particular these items should be checked:
* "Download chart image" still works
* "Download chart image" still works after disaggregations are selected
* "Download chart CSV" still works
* "Download chart CSV" still works after disaggregations are selected
* "Download source CSV" still works
* "Download table CSV" still works
* "Download table CSV" still works after disaggregations are selected

For the ones that say "after disaggregations are selected", the point is to make sure that the download includes those selected disaggregations.

**Review by LucyGwilliamAdmin — APPROVED** [review]
Updated feature branch:
http://sdgdev-813006012.eu-west-1.elb.amazonaws.com/button_check/1-2-1/

Checked all buttons on Chart and Table, and also on Chrome and IE - all seems to be working fine

**Pull request merged**
