### PR TITLE
Update contribute-translations.md

### PR DESCRIPTION
**Pull request by LucyGwilliamAdmin**
Q | A
--- | ---
Feature branch/test site URL | [Link](add link here)
Fixed issues | Fixes #ISSUENUMBER
Related version | 1.3.0-dev
Bugfix, feature or docs? |
Keeps backward-compatibility? |❌/✔️
Includes tests? |❌/✔️
Updated docs? |❌/✔️
Updated config forms? |❌/✔️
Added CHANGELOG entry? |❌/✔️

### CODE REVIEW

**Comment by LucyGwilliamAdmin** [comment]
@brockfanning does this make sense?

Also I noticed you could also change the interface language in that area so added a little bit about that

**Review by brockfanning — APPROVED** [review]
Looks good!

**Comment by LucyGwilliamAdmin** [comment]
@brockfanning I've actually just read it back and not sure this is the best heading:

- Show string in another existing language

"Maybe Show source translation string in another existing language"

**Comment by brockfanning** [comment]
@LucyGwilliamAdmin That also works. I guess you want the minimum of lingo then it could also be something like: "Working from a non-English language"?

**Comment by LucyGwilliamAdmin** [comment]
Ah yes - that sounds great!

**Comment by LucyGwilliamAdmin** [comment]
I actually went for _Translating_ from a non-English language, just for a bit more clarity

Thanks for your help!

**Pull request merged**
