### PR TITLE
Updates to news layout markup/style

### LINKED ISSUE #1057: changes to 'Updates' page
This is a direct copy of https://github.com/ONSdigital/sdg-indicators/issues/3397

A number of design changes are required to the 'updates' page in order to align it with GDS standards. It was decided in weekly tech call these changes would be made to OpenSDG 

A screenshot showing the new design (using word doc) can be seen here:
Screenshot (19)

A similar working example can be found on the UK website here: https://sdgdata.gov.uk/publications/

The changes compared to the current UK layout are:

Title of page changed to: Updates on Sustainable Development Goals
Update title and initial paragraph text to be 16px
Date format to be: dd, full month name, yyyy
Category labels to be alongside date (with relevant spacing in between)
Date and category font size set to: small
Removal of the Post by category option (this is not required at this time due to the small number of current updates shown)

### PR DESCRIPTION
**Pull request by brockfanning**
Fixes #1057 

EDIT: [Feature Branch](http://sdgdev-813006012.eu-west-1.elb.amazonaws.com/news-style-updates)

### CODE REVIEW

**Comment by jwestw** [comment]
Here is the [feature branch](http://sdgdev-813006012.eu-west-1.elb.amazonaws.com/news-style-updates).

@phillipgardiner you'll need to see this one as it fixes #1057 the issue you raised.

**Comment by phillipgardiner** [comment]
@jwestw @brockfanning This is great - thank you. The only thing I have spotted is not directly related to this as such. But for this page I specified that 'Date and category font size set to: small'. However looking at our 'Publications page' is seems on that page we set 'font-size: 85%'. I believe we should probably make these the same. Having looked at the the updates page layout on a mobile device <small> font is quite small. I think we should therefore probably change 'Date and category font size to 85%' to align with the publications page.

@brockfanning @jwestw  I'm not sure how you wish to manage this as technically this is a change, so we could close this task and then I create a new card to change it to 85%, or happy if you just want to make the change now. Either way let me know.

**Comment by brockfanning** [comment]
@phillipgardiner @jwestw That's a simple tweak so I just pushed it up to this branch - this is ready for a feature branch refresh.

**Comment by jwestw** [comment]
[Feature branch](http://sdgdev-813006012.eu-west-1.elb.amazonaws.com/news-style-updates) has been refreshed.

**Comment by phillipgardiner** [comment]
@jwestw Good to go :) @brockfanning thanks for making the update.

**Review by jwestw — APPROVED** [review]
Approving according to Phil's comment.

**Pull request merged**
