### PR TITLE
Back-to-top cleanup and added to goals/indicators/status pages

### LINKED ISSUE #1622: Add 'back to top' link to long pages
image

A back to top link is required to be added to the following pages:

- All goals pages (for example: https://sdgdata.gov.uk/1/)
- All indicator pages (for example: https://sdgdata.gov.uk/1-2-1/)
- Reporting status page (https://sdgdata.gov.uk/reporting-status/)
- Privacy notice (https://sdgdata.gov.uk/privacy-notice/)

The back to top link is required to be moved to the right hand side on the following pages

- Publications page (https://sdgdata.gov.uk/publications/)
- FAQ page (https://sdgdata.gov.uk/faq/)

Please ensure the GDS pattern is used: https://github.com/alphagov/govuk-design-system-backlog/issues/5

image

### PR DESCRIPTION
**Pull request by brockfanning**
Q | A
--- | ---
Feature branch/test site URL | [Link](http://uk-sdg-feature-branches.s3-website.eu-west-2.amazonaws.com/feature-site-back-to-top-on-some-pages/)
Fixed issues | Fixes #1622 
Related version | 2.0.0-dev
Bugfix, feature or docs? |
* [ ] Keeps backward-compatibility
* [ ] Includes tests
* [ ] Updated docs
* [ ] Updated config forms
* [ ] Added CHANGELOG entry

### CODE REVIEW

**Comment by otis-bath** [comment]
@brockfanning this is all working as intended on goals and status pages etc - should this be on indicator pages or not? Currently not showing on the indicators  
http://uk-sdg-feature-branches.s3-website.eu-west-2.amazonaws.com/feature-site-back-to-top-on-some-pages/5-5-1/

**Comment by otis-bath** [comment]
@phillipgardiner are you happy with the placement and design of these 'Back to Top' signs on indicator and pages
http://uk-sdg-feature-branches.s3-website.eu-west-2.amazonaws.com/feature-site-back-to-top-on-some-pages/1-2-1/

**Comment by phillipgardiner** [comment]
@brockfanning @otis-bath Thanks for doing this. A couple of small comments. 

1) Is the arrow able to be change to be inline with the GDS one? I feel we may have had this conversation before and ended up going with what we have as that was the default or something, but thought i'd ask again
image
2) On the indicator pages I think the link needs a bit more breathing space from the content. I would therefore increase the top margin of the back to top link from 15 to 30. This does then mean the space on the goal page is probably a bit big but I guess it a compromise?

Thanks

**Comment by brockfanning** [comment]
@phillipgardiner I have been limiting choices to the icons that are in the font-awesome (version 4.5) library. We've been using the "arrow-up" icon, but there is also a "long-arrow-up" icon. Here is what that would look like:
Screenshot from 2022-06-02 10-22-36

**Comment by phillipgardiner** [comment]
@brockfanning OK, it were using font awesome icons only then I'd go with the long arrow as its closer to the GDS icon due to its weighting / prominence.

**Comment by brockfanning** [comment]
@otis-bath This is ready for a FB refresh when you have time.

@phillipgardiner For some reason I thought the GDS approach of using an SVG icon was problematic in some way, but I just tried it out locally and it's working OK in Firefox. Let's see what the FB looks like after a refresh and test in a few browsers. The color of the arrow seems to inherit the color of the link, which I think is fine.

**Comment by otis-bath** [comment]
@brockfanning @phillipgardiner All updated - can be viewed here:
http://uk-sdg-feature-branches.s3-website.eu-west-2.amazonaws.com/feature-site-back-to-top-on-some-pages/

**Review by phillipgardiner — CHANGES_REQUESTED** [review]
@brockfanning @otis-bath Can I just check is the arrow the same colour blue as the text? On my screen it looks slightly different I think.

Also is there any way of lining up the arrow so the bottom is level with with the underline as the arrow looks slightly off to me (compare with screen shot in ticket)

Thanks

**Comment by brockfanning** [comment]
@phillipgardiner I just pushed a tweak to the margin-bottom that could help with the alignment issue (@otis-bath do you mind another refresh?)

About the color, I think it should be the same. The SVG code that GDS uses has `fill="currentColor"` which I assumed means that it inherits whatever color the parent has. I don't see anything that would be changing the color, and on my screen they seem to be synced up.

**Comment by phillipgardiner** [comment]
@brockfanning thank you. I just wanted to check about the colour as I though it could quite possibly be my screen but wanted to double check.

**Comment by otis-bath** [comment]
@brockfanning @phillipgardiner - refreshed, what are your thoughts?
http://uk-sdg-feature-branches.s3-website.eu-west-2.amazonaws.com/feature-site-back-to-top-on-some-pages/

**Comment by phillipgardiner** [comment]
@otis-bath @brockfanning much better, thank you

**Review by otis-bath — APPROVED** [review]

**Pull request merged**
