### PR TITLE
Hide/show the sidebar depending on the active tab

### PR DESCRIPTION
**Pull request by brockfanning**

### CODE REVIEW

**Comment by Norric1Admin** [comment]
Agreed, I like this feature a lot! I report the same problem on my Samsung phone.

**Comment by brockfanning** [comment]
I couldn't figure out how to get the animation to work vertically, but the latest commit at least fixes the white space problem.

**Comment by LucyGwilliamAdmin** [comment]
Maybe using something like [this](https://css-tricks.com/almanac/properties/s/scroll-behavior/)

**Comment by brockfanning** [comment]
No prob. My first impression was that this requires some javascript. I've pushed up another commit that should address the problem.

**Comment by LucyGwilliamAdmin** [comment]
One thing I have just noticed is that when on desktop version and map tab has been selected there is a lot of white space between the metadata tab panel and the bottom of the page

**Comment by brockfanning** [comment]
I haven't noticed that space problem. Is this happening on a test branch that I could take a look at, by any chance?

**Comment by LucyGwilliamAdmin** [comment]
This feature branch https://sdg.mango-solutions.com/remove-disaggs/3-a-1/

**Comment by brockfanning** [comment]
Good catch, that was due to the indicator having a lot of disaggregations (making it very tall). I've made another commit that should help. It might be a good idea to confirm that the mobile fix still works.

**Comment by LucyGwilliamAdmin** [comment]
Something else has happened now: 
Seems like the disaggregations are displaying below the bottom of the page:

**Comment by brockfanning** [comment]
I just tried a quick fix, any better now?

**Comment by LucyGwilliamAdmin** [comment]
@brockfanning Great, works on mobile and desktop!

**Pull request merged**
