### PR TITLE
Remove role from datatable

### LINKED ISSUE #921: Remove grid role from tables
**URL:** http://sdgdev-813006012.eu-west-1.elb.amazonaws.com/dac2020/3-a-1/

**Screenshot:**
image

A role of ‘grid’ has been used on a table which has not been implemented as a standard grid widget. Grids require focus to be managed, and once this role is assigned the usual table shortcuts will not work with assistive technology.

**Current Code Ref(s):** #DataTables_Table_0 
`<table class="table table-hover dataTable no-footer" id="DataTables_Table_0" role="grid" style="width: 100%;">[…]</table>`

**Solution:**
Please remove the role of grid from this table. For more information, please visit [Data Grid Examples | WAI-ARIA Authoring Practices 1.1](https://www.w3.org/TR/wai-aria-practices-1.1/examples/grid/dataGrids.html) and [Grid Design Pattern in WAI-ARIA Authoring Practices 1.1](https://www.w3.org/TR/wai-aria-practices-1.1/#grid).

### PR DESCRIPTION
**Pull request by brockfanning**
Fixes #921

### CODE REVIEW

**Comment by jwestw** [comment]
Feature branch:  http://sdgdev-813006012.eu-west-1.elb.amazonaws.com/jw-test-datatable-not-grid

**Comment by jwestw** [comment]
Comparing http://sdgdev-813006012.eu-west-1.elb.amazonaws.com/jw-test-datatable-not-grid/3-a-1/ and https://sdgdata.gov.uk/3-a-1/ 

Indeed I couldn't get the assistive screen reader to read data out from the tables in the current UK site but it worked well on the feature branch. Each line and cell were read out as expected. 

I think I brought this up before, but as the cell is read out no visible focus is apparent on the data. I looked at the "Example 1: Minimal Data Grid" examples at: https://www.w3.org/TR/wai-aria-practices-1.1/examples/grid/dataGrids.html
and saw that they those tables have a visual focus (a dotted outline of the cell) as the reader goes from cell to cell. All arrow keys are usable. Also a little arrow-keys-diagram comes up, to indicate that you can navigate the table in this way. 

image

**Comment by brockfanning** [comment]
@jwestw I think that implementing a true "data grid" would be ideal - this would involve displaying the focused cell and supporting the arrow keys, like you say. But the fact is that we have not implemented that yet, and so DAC's request was to simply remove `role="grid"`. That's all I've done here. We could definitely go the other route and try to implement a data grid, but that will be a more involved task so I didn't attempt that here.

**Comment by jwestw** [comment]
Okay, great. I am happy to merge.

**Comment by jwestw** [comment]
Accidentally closed. Reopening.

**Review by jwestw — APPROVED** [review]

**Comment by LucyGwilliamAdmin** [comment]
@brockfanning @jwestw I sent this to DAC for sign off and had the following reply:

>The table header aria-label and aria-controls can be removed from <th> now. Also, what seems to be preventing table shortcuts for screen readers in some browsers is setting the rowspan and colspan attributes. I think these attributes are interpreted as specifying the area introduced by the table header, so when the rowspan is set on a column header sometimes the tech seems to get confused. I would remove these as they may prevent screen reading software correctly relaying the table structure in certain browsers, and they don’t add anything for simple tables.
> 
> ```
> <th scope="col" class="sorting_asc" aria-controls="DataTables_Table_0" rowspan="1" colspan="1" aria-sort="ascending" aria-label="Year: activate to sort column descending" style="white-space: nowrap;"><span tabindex="0" role="button" aria-describedby="column-sort-info">Year</span><span class="sort"><i class="fa fa-sort-down"></i><i class="fa fa-sort-up"></i></span></th>
> ```

**Pull request merged**
