### PR TITLE
Map slider accessibility

### LINKED ISSUE #939: Mark slider year up as text instead of a link
URL: http://sdgdev-813006012.eu-west-1.elb.amazonaws.com/dac2020/3-a-1/

**Screen shot:**
image

The year ‘2016’ is implemented as a link and the link text changes depending on the year selected, however it does not seem to perform any function upon activation.

Solution:
If a link has no purpose, please consider marking it up as text and not as a link.

### LINKED ISSUE #940: Ensure map slider meets colour contrast guidelines
**URL:** http://sdgdev-813006012.eu-west-1.elb.amazonaws.com/dac2020/3-a-1/

**Screen shot:**
image

The grey (#DDD) background colour of the slider knob fails colour contrast guidelines with a ratio of 1.4:1 against the white background. The grey (#a5a5a5) border colour also fails with a ratio of 2.5:1 meaning low vision users will struggle to use this functionality.

**Solution:**
Ensure that the visual presentation of graphical components has a contrast ratio of at least 3:1 against adjacent colours so that low vision users are able to perceive the information.

### PR DESCRIPTION
**Pull request by brockfanning**
Fixes #940 
Fixes #939 
Fixes part of #937 (the part about the map slider)

### CODE REVIEW

**Comment by jwestw** [comment]
Feature branch: http://sdgdev-813006012.eu-west-1.elb.amazonaws.com/jw-test-map-slider-accessibility

Testing now.

**Comment by jwestw** [comment]
Confirming fixed:

- [ ] 940 appears to be fixed. Outline is now black or nearly black 
- [ ] 939 appears to be fixed as the year, e.g. 2016, in the slider is not a link and cannot be clicked. 
- [ ] 937: Slider is focusable, gets highlighted and controlled by arrow keys. (I think it now has a role programmatically)

Not sure if this has passed:
- [ ] 937:  Aria-label is preset in/on most map buttons (I think this is what is meant by "links" in the #937 ticket), however I think it is still missing on the full screen and search buttons. 
- [ ] 937:  Likewise I think `role="button"` is missing on the full screen and search buttons too. In both cases I might be missing what I am meant to be seeing.

**Comment by brockfanning** [comment]
Thanks @jwestw, I'm planning to do the search and fullscreen fixes in their own PRs.

**Review by LucyGwilliamAdmin — APPROVED** [review]
@brockfanning @jwestw sent this to DAC for signoff (just the year slider) and they said it looks resolved so approving

**Pull request merged**
