### PR TITLE
Update styling of progress bars

### PR DESCRIPTION
**Pull request by SavvasStephanides**
Resubmission of the progress bar styling. I think we should open a different ticket for high contrast since it seems to be a larger general change.

### CODE REVIEW

**Comment by SavvasStephanides** [comment]
Thanks @brockfanning 

> 1. I believe the indicator pages are unchanged, right? If that's the case, we don't need to add "http://127.0.0.1:4000/1-2-2/" to the accessibility tests.

Yes you're right

> 2. We should have an `inprogress` indicator too, so that that color-combination is tested also.

Definitely. I'll add this too.

**Comment by brockfanning** [comment]
@SavvasStephanides Just noting what we talked about - let's try making the "complete" status count black, and increasing the font size of the entire row of status counts, as well as the overall status count to 16px.

**Comment by SavvasStephanides** [comment]
@brockfanning Should be ready for review

Updated screenshot:

image

**Comment by SavvasStephanides** [comment]
Not sure why it's failing the contrast test. It's black text on white background 🤔

**Comment by brockfanning** [comment]
@SavvasStephanides I guess the high-contrast issues need to be resolved here, or the automated tests won't pass.

Also I thought the consensus was that the words "Reported online 6%", "Statistics in progress 0%", etc, were to be 16px as well. @phillipgardiner any thoughts?

**Comment by SavvasStephanides** [comment]
@brockfanning I think we agreed to set just the numbers. Also, see above for the contrast test failure

**Comment by phillipgardiner** [comment]
@SavvasStephanides @brockfanning umm, I'm not 100% certain what was agreed for the text, as the conversation was jumping about a bit and people looking on all different devices etc to form thier decision. But I think?? people were saying to change it to 16px as long as it didn't effect the wrapping on a PC browser. If you change to 16px though does that affect all text across the site though?

**Comment by brockfanning** [comment]
@SavvasStephanides I did have the words set to 16px (in the dev tools) when I was screensharing, FWIW.

About the test failures, It's only the high-contrast version (the one that runs after clicking the high contrast button) that is failing. This is from the test log:

```
cd tests && npx pa11y-ci --config accessibility/pa11yci-desktop.json
Running Pa11y on 4 URLs:
 > http://127.0.0.1:4000/1/ - 0 errors
 > http://127.0.0.1:4000/ - 0 errors
 > http://127.0.0.1:4000/1-1-1/ - 0 errors
 > http://127.0.0.1:4000/reporting-status/ - 0 errors

✔ 4/4 URLs passed
cd tests && npx pa11y-ci --config accessibility/pa11yci-mobile.json
Running Pa11y on 4 URLs:
 > http://127.0.0.1:4000/1/ - 0 errors
 > http://127.0.0.1:4000/ - 0 errors
 > http://127.0.0.1:4000/1-1-1/ - 0 errors
 > http://127.0.0.1:4000/reporting-status/ - 0 errors

✔ 4/4 URLs passed
cd tests && npx pa11y-ci --config accessibility/pa11yci-contrast.json
Running Pa11y on 4 URLs:
 > http://127.0.0.1:4000/1/ - 0 errors
 > http://127.0.0.1:4000/ - 0 errors
 > http://127.0.0.1:4000/1-1-1/ - 0 errors
 > http://127.0.0.1:4000/reporting-status/ - 18 errors
```

**Comment by phillipgardiner** [comment]
Not sure why it's failing the contrast test. It's black text on white background but it says the contrast is 1:1 🤔 - Is that for the black text on white background???? As that easily passes: https://webaim.org/resources/contrastchecker/

**Comment by brockfanning** [comment]
That particular automated test uses the high-contrast button. This is what it's seeing before it fails:
 
Screenshot from 2020-03-05 05-48-02

**Comment by SavvasStephanides** [comment]
oooh that makes sense 🤦‍♂️

I'll go fix it. Thanks @brockfanning

**Comment by phillipgardiner** [comment]
@brockfanning @SavvasStephanides ah yes that makes sense then on the high contrast version! @SavvasStephanides I would say it was decided on 16px for the words too then as whatever brock changed it too was what we ended up agreeing on.

**Comment by SavvasStephanides** [comment]
@phillipgardiner @brockfanning I was going to postpone the high contrast changes for another ticket but since it fails these tests, I'm going to include them here.

**Comment by SavvasStephanides** [comment]
@brockfanning This should be ready for re-review

**Comment by brockfanning** [comment]
Thanks @SavvasStephanides. Here's a screenshot for you to review @phillipgardiner 

Screenshot from 2020-03-16 13-24-46


To me it looks great. The only thing I'd suggest is a white top/bottom border on the high-contrast "Statistics in progress" region of the bar.

**Comment by phillipgardiner** [comment]
@brockfanning thanks for the screen shot, I was eagerly anticipating finding out what it would look like :). @SavvasStephanides looks great. Good work. As Brock says I suppose to be a true inverse the grey "Statistics in progress" should have a white outer line on the progress bar as on the 'normal' one it has a black outline. Great stuff 👍

**Comment by SavvasStephanides** [comment]
Thanks @brockfanning @phillipgardiner. I'm in the process of make a few further improvements. Should be ready to review soon.

**Comment by SavvasStephanides** [comment]
@brockfanning @phillipgardiner Turns out setting the border messes up with the chart in reporting status, wrapping stuff to a new line. I've decided to revert this but I have made a few changes

image

**Pull request merged**
