### PR TITLE
Automated accessibility testing

### PR DESCRIPTION
**Pull request by brockfanning**
This allows for using [pa11y](https://github.com/pa11y/pa11y) for automated testing. For now it's separate from the tests that run on each PR, since out-of-the-box we are failing some tests. Further investigation is needed to decide if the failures are valid. If not, we should tweak the tests/.pa11yci file to skip those errors. If they are valid, we need to fix the problems.

The command to run these tests is `make test.accessibility`. This tests the homepage, goal page, indicator page, and reporting status page.

### CODE REVIEW

**Comment by brockfanning** [comment]
@SavvasStephanides I think this might be a good first step towards accessibility testing. At least this allows an easy way to run that tests. Next would be to run them and investigate each failure to decide if it's valid or not.

**Comment by SavvasStephanides** [comment]
Hi @brockfanning. I'm curious how this works. Does it run as a test after a pull request? And what does it test?

The reason I'm asking is, as we discussed before, there are some accessibility issues we can't exactly tackle. Case in point, the contrast of the goal tiles. Would the tests fail in that case?

**Comment by brockfanning** [comment]
@SavvasStephanides To have this run as part of the pull-request tests, we would need to add it to the "make test" rule. But for now, I have it separate, as a "make test.accessibility" rule. So, it's not actually "automated" yet (bad PR name, sorry).

Pa11y has a ton of config options to control what it tests. In this PR all I'm doing is telling Pa11y which pages to test (see the .pa11yci file in the PR). I'm leaving everything else at the defaults. Stuff indeed fails at the moment. If you're curious what's failing on those page, here's the output (and you can try yourself by running `make test.accessibility`):

```
Running Pa11y on 4 URLs:
 > http://127.0.0.1:4000/ - 1 errors
 > http://127.0.0.1:4000/1/ - 1 errors
 > http://127.0.0.1:4000/1-1-1 - 7 errors
 > http://127.0.0.1:4000/reporting-status/ - 1 errors

Errors in http://127.0.0.1:4000/:

 • This button element does not have a name available to an accessibility API. Valid names
   are: title undefined, element content, aria-label undefined, aria-labelledby undefined.

   (#search-btn)

   <button id="search-btn" type="submit"><i class="fa fa-search" aria-hi...</button>

Errors in http://127.0.0.1:4000/1/:

 • This button element does not have a name available to an accessibility API. Valid names
   are: title undefined, element content, aria-label undefined, aria-labelledby undefined.

   (#search-btn)

   <button id="search-btn" type="submit"><i class="fa fa-search" aria-hi...</button>

Errors in http://127.0.0.1:4000/1-1-1:

 • This button element does not have a name available to an accessibility API. Valid names
   are: title undefined, element content, aria-label undefined, aria-labelledby undefined.

   (#search-btn)

   <button id="search-btn" type="submit"><i class="fa fa-search" aria-hi...</button>

 • This element has insufficient contrast at this conformance level. Expected a contrast
   ratio of at least 4.5:1, but text in this element has a contrast ratio of 2.79:1.
   Recommendation:  change text colour to #565656.

   (#clear)

   <button id="clear" class="disabled">Clear selections <i class="fa f...</button>

 • This table appears to be used for layout, but contains a caption element. Layout tables
   must not contain captions.

   (#datatables > table)

   <table class="table-responsive table table-hover dataTable no-footer" role="grid">
   <caption>Proportion of p...</table>

 • This element has insufficient contrast at this conformance level. Expected a contrast
   ratio of at least 4.5:1, but text in this element has a contrast ratio of 3.93:1.
   Recommendation:  change background to #fefefe.

   (#indicator-main > section > ul > li:nth-child(2) > a)

   <a class="nav-link" data-toggle="tab" href="#global" aria-controls="global" role="tab"
   data-on="click" data-event-category="Tab change" data-event-action="Change metadata view"
   data-event-label="Change to My global metadata title tab">My global metad...

 • This element has insufficient contrast at this conformance level. Expected a contrast
   ratio of at least 4.5:1, but text in this element has a contrast ratio of 3.93:1.
   Recommendation:  change background to #fefefe.

   (#indicator-main > section > ul > li:nth-child(3) > a)

   <a class="nav-link" data-toggle="tab" href="#sources" aria-controls="sources" role="tab"
   data-on="click" data-event-category="Tab change" data-event-action="Change metadata view"
   data-event-label="Change to My sources title tab">My sources title</a>

 • This element has insufficient contrast at this conformance level. Expected a contrast
   ratio of at least 4.5:1, but text in this element has a contrast ratio of 3.93:1.
   Recommendation:  change background to #fefefe.

   (#indicator-main > section > ul > li:nth-child(4) > a)

   <a class="nav-link" data-toggle="tab" href="#edit" aria-controls="edit" role="tab">Edit</a>

 • This element has insufficient contrast at this conformance level. Expected a contrast
   ratio of at least 4.5:1, but text in this element has a contrast ratio of 3.93:1.
   Recommendation:  change background to #fefefe.

   (#indicator-main > section > div:nth-child(1) > ul > li:nth-child(2) > a)

   <a class="nav-link" data-toggle="tab" href="#tableview" aria-controls="tableview"
   role="tab" data-on="click" data-event-category="Tab change" data-event-action="Change data
   view" data-event-label="Change to Table tab">Table</a>

Errors in http://127.0.0.1:4000/reporting-status/:

 • This button element does not have a name available to an accessibility API. Valid names
   are: title undefined, element content, aria-label undefined, aria-labelledby undefined.

   (#search-btn)

   <button id="search-btn" type="submit"><i class="fa fa-search" aria-hi...</button>

✘ 0/4 URLs passed
Makefile:57: recipe for target 'test.accessibility' failed
```

**Comment by SavvasStephanides** [comment]
OK cool. I think let's keep it away from the build tests for now.

**Pull request merged**
