### PR TITLE
New breadcrumb configuration and separator

### LINKED ISSUE #629: Change breadcrumbs to GDS standard
Follow GDS visual standard for breadcrumbs
(https://designsystem.service.gov.uk/components/breadcrumbs/)

### PR DESCRIPTION
**Pull request by brockfanning**
Fixes #629 and #630 

screenshot-127 0 0 1_4000-2020 08 22-13_27_45

### CODE REVIEW

**Comment by brockfanning** [comment]
@jwestw @LucyGwilliamAdmin This is ready for review now. Note that there is a new configuration option for controlling the breadcrumbs: https://github.com/brockfanning/open-sdg/blob/breadcrumb-revamp/docs/configuration.md#breadcrumbs

**Comment by LucyGwilliamAdmin** [comment]
@brockfanning this is what it looks like by default i.e. no config:
http://sdgdev-813006012.eu-west-1.elb.amazonaws.com/breadcrumbs-revamp-default/

Here's what it looks like with the full example i.e. post, goal and indicator with translations:
http://sdgdev-813006012.eu-west-1.elb.amazonaws.com/breadcrumbs-revamp/

Is this correct?

On the default version, the page which your on also shows in breadcrumbs (not a link), but doesn't show on the full example version - is this expected?

**Comment by brockfanning** [comment]
@LucyGwilliamAdmin @phillipgardiner Yes that's what I intended. In the GDS standard the current page is not included in the breadcrumbs. The default version is there for backwards compatibility. Admittedly it's an unexpected difference. If we wanted to make them consistent, we could either include the current page in the GDS version, or remove the current page from the backwards-compatible version. Personally I kind of lean towards the GDS version, because I'm thinking that the user already knows what page they're on. But I'm fine with either approach.

**Comment by brockfanning** [comment]
@LucyGwilliamAdmin Also, great idea to test with and without the new config!!

**Comment by brockfanning** [comment]
Sorry for the repeated comments - last one... I would also be fine with leaving them inconsistent, with the eventual plan of making the "breadcrumbs" config setting required.

**Comment by LucyGwilliamAdmin** [comment]
Ok, great - I'm fine with either way around!

**Review by LucyGwilliamAdmin — APPROVED** [review]
All looks good!

**Pull request merged**
