### PR TITLE
Docs link to new case study by Germany

### PR DESCRIPTION
**Pull request by brockfanning**

### CODE REVIEW

**Comment by LucyGwilliamAdmin** [comment]
@brockfanning is there a way I can see how this looks within [readthedocs](https://open-sdg.readthedocs.io/en/latest/)

**Comment by brockfanning** [comment]
@LucyGwilliamAdmin Locally you can see the docs by going into the root of the project on the command line and typing `mkdocs serve`. But you'll first need to install Python and [mkdocs](https://www.mkdocs.org/).

**Comment by LucyGwilliamAdmin** [comment]
Do I need to change anything so that it points at brockfanning-patch-1? I can view the docs but Germany's case study isn't there

**Comment by brockfanning** [comment]
Ah, in this case my branch is in the origin repo, so it should be as easy as:

```
git fetch origin
git checkout brockfanning-patch-1
mkdocs serve
```

**Pull request merged**
