### PR TITLE
UX improvements for config and data form headers

### LINKED ISSUE #1694: UX improvements to data edit form
Couple of minor changes required to the data edit form - these are: 

- Position 'Download data' and 'Go to repository' buttons next to each other horizontally instead of vertically
- As a result of horizontal buttons the grey shadow box can be reduced in height relevant to the button height
- Stop buttons from overlapping when viewed on mobile
- Ensure 'Value' column which contains numbers is right justified, label should be right justified too.

### PR DESCRIPTION
**Pull request by brockfanning**
This addresses the items mentioned in #1694. To keep things consistent, I also applied these changes to the indicator config and metadata config forms.

Q | A
--- | ---
Feature branch/test site URL | [Link](http://uk-sdg-feature-branches.s3-website.eu-west-2.amazonaws.com/feature-site-data-form-style-fixes/1-1-1/)
Fixed issues | Fixes #1694 
Related version | 2.1.0-dev
Bugfix, feature or docs? |
* [ ] Keeps backward-compatibility
* [ ] Includes tests
* [ ] Updated docs
* [ ] Updated config forms
* [ ] Added CHANGELOG entry

### CODE REVIEW

**Review by otis-bath — APPROVED** [review]
Thanks for this @brockfanning - could you have a look @phillipgardiner and check you are happy - all the forms should be enabled on each indicator

**Review by phillipgardiner — COMMENTED** [review]
@otis-bath @brockfanning Only thing I would say is the position of the buttons when you reduce the size of the screen seems bit off. Essentially when ipad, or phone size it all becomes a bit off center.

**Comment by phillipgardiner** [comment]
Also has the 'Go to repository' button dissapeared? or s that just my view?

**Comment by brockfanning** [comment]
@phillipgardiner The "Go to repository" for the indicator config, metadata config, and data config, all require a configuration setting that the UK does not have enabled at the moment. But you can see it on the site configuration form: http://uk-sdg-feature-branches.s3-website.eu-west-2.amazonaws.com/feature-site-data-form-style-fixes/config/

Regarding the issues with some device widths - I do see that when some content wraps it looks a bit odd. Here's a screenshot below - is this what you're seeing too?

image

**Comment by phillipgardiner** [comment]
@brockfanning Yes. Also as the UK doesn't have the 'go to repository' config enabled there is only one button so it is a lot higher than the input field - alhtough weirdly I only get this on Chrome on my PC, when viewed in Chrome on MAC is looks OK.

Annotation 2022-09-08 144733

**Comment by otis-bath** [comment]
@phillipgardiner - I have enabled the 'go to repository' option on this FB: http://uk-sdg-feature-branches.s3-website.eu-west-2.amazonaws.com/feature-site-data-form-style-fixes/1-1-1/

**Comment by sarah-beasley** [comment]
Brock to add a space beneath the search bar for when the wrap goes across two lines.

**Comment by brockfanning** [comment]
@otis-bath @sarah-beasley This one is ready for a refresh of the feature-branch.

**Comment by sarah-beasley** [comment]
@brockfanning just refreshed and the issue where the spacing below the search bar when the buttons are wrapped is better now. However for the site config and edit metadata forms, the buttons are still spaced quite close together on smaller screens ~tablet size.

image

The edit data tab is fine though.

**Comment by brockfanning** [comment]
@sarah-beasley This is ready for a refresh, when you have time.

**Comment by sarah-beasley** [comment]
> @sarah-beasley This is ready for a refresh, when you have time.

Thanks @brockfanning have tested again and think it looks much better with the spacing at different screen sizes :) approved.

**Review by sarah-beasley — APPROVED** [review]

**Pull request merged**
