### PR TITLE
Support for keyboard operation of the map selection legend

### PR DESCRIPTION
**Pull request by brockfanning**
This is not in response to a particular issue but I suspect it will come up. The selection legend on maps can't be accessed or operated with a keyboard. This should allow users to tab onto those items, and to remove them from the list by pressing enter.

### CODE REVIEW

**Comment by LucyGwilliamAdmin** [comment]
Feature branch: http://sdgdev-813006012.eu-west-1.elb.amazonaws.com/map-selection-legend-accessibility/3-a-1/

**Comment by LucyGwilliamAdmin** [comment]
@brockfanning I'm a little unsure about what this should be doing

**Comment by brockfanning** [comment]
@LucyGwilliamAdmin This affects "selection legend" that appears in the upper right corner of maps, when you select regions. Those items in the upper right should now be accessible by keyoboard (tabbing onto them). Also if you are tabbed onto one of them and you press the enter key, it should behave like you clicked on it.

**Comment by LucyGwilliamAdmin** [comment]
@brockfanning yes, looks like it's keyboard accessible now which is great 👍 

However the default map isn't showing any labels on the scale

**Comment by brockfanning** [comment]
Let's create an issue and postpone this one.

**Comment by LucyGwilliamAdmin** [comment]
@brockfanning did we say we would close this PR and reopen if/when we come back to the issue?

**Comment by brockfanning** [comment]
Yes I think so, sounds good.

**Pull request closed without merging**
