### PR TITLE
Show post excerpts on news page

### LINKED ISSUE #425: Excerpt missing from News page
Even though there is a excerpt field in the markdown files for posts, the excerpt doesn't actually show anywhere

### PR DESCRIPTION
**Pull request by brockfanning**
Fixes #425 

@LucyGwilliamAdmin I haven't tested this - this a quick shot in the dark, in case it works.

### CODE REVIEW

**Comment by LucyGwilliamAdmin** [comment]
@brockfanning yes, will test now.

I think another change the news page may benefit from is one we've implemented in the UK:
https://github.com/ONSdigital/sdg-indicators/blob/develop/_layouts/news.html

It just moves the categories from the top of the post on the News page to the bottom. When it was at the top, it looked as if the posts are grouped into categories whereas they're actually in date order.

**Comment by LucyGwilliamAdmin** [comment]
@brockfanning have tested the excerpt part and looks good.
The only thing I can see that we need to document is that if no excerpt is set, the first paragraph (?) is automatically set as excerpt - see this [feature branch](http://sdgdev-813006012.eu-west-1.elb.amazonaws.com/open-sdg-news-page-set-excerpt/updates/) where excerpt was only set for International work.

**Comment by brockfanning** [comment]
@LucyGwilliamAdmin The categories move sounds good - I just added that.

Jekyll actually has its own documentation of the excerpt functionality: https://jekyllrb.com/docs/posts/#post-excerpts

I don't believe we have any post-specific documentation - do you think we should add that?

**Comment by LucyGwilliamAdmin** [comment]
@brockfanning testing the latest changes - do you think it would make sense to have the categories between the date and the excerpt?

This is how it looks at the moment?
image

**Comment by LucyGwilliamAdmin** [comment]
@brockfanning re. documentation - I think we could add something (even if we just give basic overview and simplify what is in the Jekyll guidance)

**Comment by brockfanning** [comment]
Yeah, it's not very clear that those are even categories. It seems like they ought to be links to other listing pages specifically for that category. Or maybe to have "Categories: " as a label next to them? Or maybe just removed altogether?

It also occurs to me that the news/post functionality is not set up to work with multilingual. For example, if a country has a post translated into two languages, I think it would show up twice on the News page. Also, different languages show dates in different ways, so we'd want to figure out how to properly display dates according to the current language.

If you agree, should we turn this into a general news/post revamp? Or make separate tickets for that?

**Comment by LucyGwilliamAdmin** [comment]
@brockfanning I agree that the news/post pages could do with a revamp.
@AnnCorp I know we briefly discussed the news page the other day - what are your thoughts?

**Comment by brockfanning** [comment]
@LucyGwilliamAdmin I think we discussed going ahead with this one. I created some other tickets for followup work:
* #435 
* #434 
* #433

**Pull request merged**
