### PR TITLE
Better support for third-party and remote javascript files.

### LINKED ISSUE #950: Better support for custom external javascript
**Is your feature request related to a problem? Please describe.**

In order to add custom external javascript libraries, implementations need to override the large and often-changing "scripts.html" file. This causes complications when upgrading.

**Describe the solution that you need**

The `custom_js` should support external libraries. In addition, there should be a `scripts_custom.htm` include file which is empty, but when implementations can override to have more control over the external scripts.

**Why do you need this feature?**

Implementations often need to add third-party javascript libraries such as for analytics or visualization.

**Describe alternatives you've considered**

No other alternatives considered.

### PR DESCRIPTION
**Pull request by brockfanning**
Fixes #950

### CODE REVIEW

**Comment by brockfanning** [comment]
@LucyGwilliamAdmin @jwestw This PR is intended to help avoid the need for overriding `_includes/scripts.html`. For example it would have avoided the need for [this "Loop11" commit](https://github.com/ONSdigital/sdg-indicators/commit/62579415463f0c73fb62e4d8ee64be01fd6457d7).

**Comment by jwestw** [comment]
Feature branch for 951: http://sdgdev-813006012.eu-west-1.elb.amazonaws.com/jw-test-951-better-external-javascript-support

**Comment by jwestw** [comment]
Hi 

I see updates to file such as the addition of custom.js and changes to _config.yml. How would I test this? Even if I change the _config.yml with 👍 
```custom_js:
  - /custom.js```
Since my feature branch doesn't have custom.js nor the other changes, nothing will be effective. Could you advise please?

**Comment by brockfanning** [comment]
@jwestw I would recommend this:

First delete the `_includes/scripts.html` file in your feature branch.

Next create a new file in your feature branch called `_includes/scripts-custom.html`. The contents of that file should be:

```
<script src="//cdn.loop11.com/embed.js" type="text/javascript" async="async"></script>
```

In this way you can get your custom Loop11 functionality without needing to override the frequently-changing `_includes/scripts.html` file.

As for confirming that your Loop11 functionality still works correctly - I can't help much with that one. It may be impossible to test on a feature branch. @phillipgardiner may have more insights there.

**Comment by jwestw** [comment]
@phillipgardiner I have update the feature branch as instructed. I wonder if you can verify if the loop11 functionality is testable?

**Comment by phillipgardiner** [comment]
@jwestw @brockfanning I set up a dummy study on the feature branch and can confirm that the study was able to run successfully, so I can confirm the loop 11 functionality still works correctly.

**Comment by LucyGwilliamAdmin** [comment]
@brockfanning @jwestw so I think if the loop11 stuff is working this can be marked as approved right?

**Review by LucyGwilliamAdmin — APPROVED** [review]
We agreed in last week's tech call that this could be approved but didn't get around to it

**Pull request merged**
