### PR TITLE
High-contrast chart image downloads

### PR DESCRIPTION
**Pull request by brockfanning**
#710 

Testing instructions: Let's make sure that the image download still looks good in both normal and high contrast, with and without selected disaggregations.

### CODE REVIEW

**Comment by LucyGwilliamAdmin** [comment]
http://sdgdev-813006012.eu-west-1.elb.amazonaws.com/chart-download-high-contrast-fix

I think lines should be white to meet high contrast guidelines. Also footer of bar charts is getting cut off.

Line charts (1.2.1):

Default contrast with disaggs:
indicator_1-2-1 (10)

High contrast with disaggs:
indicator_1-2-1 (11)

Default contrast with no disaggs:
indicator_1-2-1 (12)

High contrast with no disaggs:
indicator_1-2-1 (13)


Bar charts (11.3.1):
Default contrast with disaggs:
indicator_11-3-1

High contrast with disaggs:
indicator_11-3-1 (2)

Default contrast with no disaggs:
indicator_11-3-1

High contrast with no disaggs:
indicator_11-3-1 (3)

**Comment by brockfanning** [comment]
@LucyGwilliamAdmin Is the issue with the line color specific to downloaded images? Or is it also a problem when just using high-contrast mode while viewing the site?

**Comment by LucyGwilliamAdmin** [comment]
@brockfanning there are some lines on the high-contrast version of the site but not on the download image:
site:
image

They are a little faint but must have gone through DAC

**Comment by brockfanning** [comment]
@LucyGwilliamAdmin Since we're doing the grid lines in a separate PR, are any other changes needed in this one?

**Comment by LucyGwilliamAdmin** [comment]
@brockfanning nope, don't think any other changes are needed here - I will approve

**Review by LucyGwilliamAdmin — APPROVED** [review]
Looks good - other issues are being fixed in another PR so marking this one as approved

**Pull request merged**
