### PR TITLE
Custom javascript for better tab accessibility

### LINKED ISSUE #840: Make sure tab panels are included in page sequence
**Page 55 in DAC report**

**Issue from DAC report:**
Tab-panel content does not take focus upon activation. Tabs have been implemented as same page links, but these do not work and upon activation, focus is taken to the other tabs before the tab-panel content.

Tab-panels are not focusable and screen reader users are not able to navigate from the tabs using cursor keys, so in order to read the content within the tab it is necessary to tab to the next focusable element on the page, and then use the cursor keys to navigate back up the page.

**Solution from DAC report:**
Include the tabpanel in the page sequence so that it can be focused by screen reader users. Ensure that focus is taken to the tabpanel upon activation.

**Example from DAC report:**

```
<div class="tab-content">
    <div role="tabpanel" class="tab-pane active" id="national"
tabindex="0">…</div>
</div>
```

Includes data tabpanel, metadata tabpanel and reporting status tab-panel

### PR DESCRIPTION
**Pull request by brockfanning**
Fixes #840 

@jwestw @LucyGwilliamAdmin This is ready for review. Because this is a moderately significant bit of javascript and does change the tab behavior, I've got this as an optional feature, `accessible_tabs`. Eventually I would foresee this is the default behavior, but for now I don't want to cause problems for the countries during upgrades.

So, when testing this in a feature branch, you would need to add `accessible_tabs: true` to the _config.yml file.

### CODE REVIEW

**Comment by jwestw** [comment]
Feature branch: http://sdgdev-813006012.eu-west-1.elb.amazonaws.com/jw-test-tab-keyboard-navigation

**Comment by LucyGwilliamAdmin** [comment]
@brockfanning So now when tabbing through, focus goes from tab name to tab content unless a diff tab is selected using left and right arrow keys, which is great:
http://sdgdev-813006012.eu-west-1.elb.amazonaws.com/tab-nav/1-1-1/

However, there is something in the report (page 56) which I'm unsure about:

"Tab-panels are not focusable and **screen reader users are not able to navigate from the tabs using cursor keys**, so in order to read the content within the tab it is necessary to tab to the next focusable element on the page, and then use the cursor keys to navigate back up the page."

I'm not sure if this means that when the tab name is focussed on, the user should be able to use down arrow to start reading through tab content?

This is not the case on the feature branch or on the [w3 tabs example](https://www.w3.org/TR/wai-aria-practices/examples/tabs/tabs-2/tabs.html) though.

**Review by LucyGwilliamAdmin — APPROVED** [review]
I've compared this with a couple of accessibility tab examples, and tab and screen reader act in same way 👍 

http://sdgdev-813006012.eu-west-1.elb.amazonaws.com/tab-nav/1-1-1/

**Comment by jwestw** [comment]
A couple of things I noticed on this:
- when tables are sortable, there is not indication that it has been completed. Clicking the button to sort them doesn't make screen reader say "sorted" nor is a click sound played. 
- although the column headers are read out through the screen reader I didn't find a way to have the data read out. Is that intended behaviour?

**Comment by brockfanning** [comment]
@jwestw I just added a commit that might help with the sorting issue. Can you give it a try?

About moving around in the table, I believe the standard keyboard shortcuts are CTRL+ALT+arrow keys. This is how non-sighted users would get the data read to them, as I understand it.

**Comment by jwestw** [comment]
Feature branch refreshed: http://sdgdev-813006012.eu-west-1.elb.amazonaws.com/tab-nav

**Comment by jwestw** [comment]
The first issue is improved. Reader now says that you can sort the column. However I didn't find a way to make it say anything when it is clicked to make data sorted ascending or descending. 

I couldn't get CTR + ALT + arrows to work, but SHIFT + Arrows did work. As the data is selected it reads it out, but the highlight doesn't move. 
The way data items in the table are selected seems odd to me but this could just be the behaviour of NVDA, I am not sure. Behaviour is:
- SHIFT + Down selects data first going down a row, then cycling through that row's columns. 
- SHIFT + left/right selects individual numerals/characters in the data so when it hits '8.15' it reads out '8 selected' then 'dot selected'.
- I don't see the selection move (but maybe this isn't important) 

Again, all of this behaviour might be NVDA specific and be out of our control

**Comment by LucyGwilliamAdmin** [comment]
@brockfanning @jwestw table sorting is fixed here, isn't it:

https://github.com/open-sdg/open-sdg/pull/880

**Comment by brockfanning** [comment]
Yes, technically table-sorting is unrelated to this ticket, but I thought I would throw that tweak in. All I'm doing in that last commit is copying the `aria-sort` attribute (which is generated by jquery.datatables) to the custom `<span role="button">` that we added in #880. My hope was that the `aria-sort` property would resolve the problem. If we need to do much else than it should probably be in a separate ticket.

@jwestw You're right that we probably don't want to get too involved with the workings of a particular screenreader. And I would guess it's fine that the cells don't get highlighted, since it is likely only non-sighted people using that. (Also cells aren't "focusable" anyway, so couldn't normally be highlighted.)

**Comment by LucyGwilliamAdmin** [comment]
@brockfanning @jwestw is there anything else to fix on this one?

**Comment by brockfanning** [comment]
Not that I know of.

**Pull request merged**
