### PR TITLE
Create cityoflosangeles.md

### PR DESCRIPTION
**Pull request by dawncomer**
@brockfanning following up - here's the City of LA Case Study for the ReadtheDocs on OpenSDG.

@angelamhkim - please add/edit as needed.

thanks!
Dawn

### CODE REVIEW

**Comment by brockfanning** [comment]
@dawncomer @angelamhkim This looks great to me, thank you so much! Is it OK to merge it, or should I wait for any other changes?

**Comment by dawncomer** [comment]
Hi @brockfanning thanks!  @angelamhkim and I have completed the updates.  It's ready to merge.  Thanks!
Dawn

**Comment by dawncomer** [comment]
Hi @brockfanning Thanks for posting.  the formatting is not viewing correctly on the customization question.   Is there something I need to do on our side to edit? https://open-sdg.readthedocs.io/en/latest/case-studies/cityoflosangeles/

@angelamhkim fyi

**Comment by brockfanning** [comment]
@dawncomer Ah, thanks for pointing that out. The ReadTheDocs service is a little more strict about their markdown. I would try adding a blank line before the beginning of that bullet list.

**Comment by dawncomer** [comment]
thanks @brockfanning i suspected a missing blank line might be the cause.  appreciate the edit.

@angelamhkim fyi

**Pull request merged**
