### PR TITLE
Hide search and contrast, and switch to language-toggle links, when no javascript

### LINKED ISSUE #1615: Hide search when JS is off
We need to hide search when JS is off since it's impossible to get it to work. However, we need to adjust the interface (particularly on mobile) so you are not just left with a big white gap where the search bar would have been.

### Discussed in https://github.com/open-sdg/open-sdg/discussions/1611

<div type='discussions-op-text'>

<sup>Originally posted by **LucyGwilliamAdmin** May 16, 2022</sup>
When JS if off, searching for any terms results in continuous loading wheel.

**To discuss: can we/should we display an error message instead in this instance? or should we completely hide the search?**

Search results when JS is off:
image
</div>

### PR DESCRIPTION
**Pull request by brockfanning**
Q | A
--- | ---
Feature branch/test site URL | [Link](http://uk-sdg-feature-branches.s3-website.eu-west-2.amazonaws.com/feature-site-no-js-hiding/)
Language FB URL | [Link](http://uk-sdg-feature-branches.s3-website.eu-west-2.amazonaws.com/feature-no-js-hiding-language/)
Fixed issues | Fixes #1615 and #1617 
Related version | 2.0.0-dev
Bugfix, feature or docs? |
* [ ] Keeps backward-compatibility
* [ ] Includes tests
* [ ] Updated docs
* [ ] Updated config forms
* [ ] Added CHANGELOG entry

### CODE REVIEW

**Comment by otis-bath** [comment]
Hi @brockfanning - just checking this PR, do I need to point towards a branch in your jekyll-open-sdg-plugins, sdg-build or translations repos? Currently have configured the FB to point at brockfanning/open-sdg@no-js-hiding in the site config but the page is not loading irrespective of js on/off - [see here](http://uk-sdg-feature-branches.s3-website.eu-west-2.amazonaws.com/feature-site-no-js-hiding/) I can't see any branches in these repos but let me know if there is something I need to change - thanks

**Comment by brockfanning** [comment]
@otis-bath I'm guessing that we are at the point now where every feature branch needs to point to the 2.0.0-dev branches of both jekyll-open-sdg-plugins and sdg-build.

**Review by otis-bath — APPROVED** [review]
Thanks Brock, all working now as you can see here: 
http://uk-sdg-feature-branches.s3-website.eu-west-2.amazonaws.com/feature-site-no-js-hiding/
image
-OB

**Comment by brockfanning** [comment]
Thanks @otis-bath - also @LucyGwilliamAdmin and @phillipgardiner just making sure that you're OK with this too, given that there are no design adjustments on the no-javascript platform (ie, no change of layout to deal with blank space after hiding the elements).

**Comment by brockfanning** [comment]
@phillipgardiner That's right - any drop-downs in the header (like drop-downs in the nav and also the language switcher) and the hamburger menu all rely on javascript to work.

**Comment by brockfanning** [comment]
@phillipgardiner @otis-bath I believe we had decided to also switch to language-toggle links (instead of a dropdown) so that at least the language toggle will still work. I've updated the PR with that. You could do a FB to test this, but you would need to turn on a second language.

I think we decided not to worry about the main navigation drop-downs not working at this point, but correct me if I'm remembering that wrong.

**Comment by otis-bath** [comment]
@brockfanning @phillipgardiner 
I have added a second language to a second FB and as you can see with Javascript off the language toggle still works
http://uk-sdg-feature-branches.s3-website.eu-west-2.amazonaws.com/feature-no-js-hiding-language/

**Comment by brockfanning** [comment]
Still to do: make the hamburger menu expanded by default on mobile with no javascript.

**Comment by brockfanning** [comment]
I'll merge this, since there is another ticket for the hamburger menu: #1653

**Pull request merged**
