### PR TITLE
Remove centering of chart titles

### LINKED ISSUE #1236: Left align graph titles
Left hand aligned graph titles are considered best practice as it supports the way people read and helps create a clear visual hierarchy.

Need to ensure that it doesn't have a knock on affect to other page elements though

### PR DESCRIPTION
**Pull request by brockfanning**
Q | A
--- | ---
Feature branch/test site URL | [Link](http://uk-sdg-feature-branches.s3-website.eu-west-2.amazonaws.com/feature-site-left-aligned-graph-titles)
Fixed issues | Fixes #1236 
Related version | 1.5.0-dev
Bugfix, feature or docs? | feature
* [x] Keeps backward-compatibility
* [ ] Includes tests
* [ ] Updated docs
* [ ] Updated config forms
* [ ] Added CHANGELOG entry

### CODE REVIEW

**Comment by LucyGwilliamAdmin** [comment]
@phillipgardiner I've added a link to feature branch and looks good to me - did you want to have quick check?

**Comment by LucyGwilliamAdmin** [comment]
Align with chart footers please

**Comment by brockfanning** [comment]
@LucyGwilliamAdmin It's ready for a refresh.

**Comment by LucyGwilliamAdmin** [comment]
@brockfanning @phillipgardiner feature branch ready again

**Comment by phillipgardiner** [comment]
@brockfanning @LucyGwilliamAdmin Great, thanks both. Happy :)

**Review by LucyGwilliamAdmin — APPROVED** [review]

**Pull request merged**
