### PR TITLE
More space beneath reporting status goal items

### LINKED ISSUE #796: Increase white space on 'Reporting Progress' page between goals
On the reporting progress page the goal rows are very tightly packed against the horizontal grey lines. Adding some additional white space will increase the comprehensibility of this page. I believe this would just be a case of changing the bottom margin from something like 4px to 20px. I have attached a screen shot showing the existing spacing and how it could look.

Screenshot (36)

### PR DESCRIPTION
**Pull request by brockfanning**
Fixes #796

### CODE REVIEW

**Comment by LucyGwilliamAdmin** [comment]
@brockfanning I've just created a feature branch for this but there doesn't seem to be any extra white space:
http://sdgdev-813006012.eu-west-1.elb.amazonaws.com/increasespace-rspage/reporting-status/

I've taken a look and we don;t seem to be overwriting anything

**Comment by LucyGwilliamAdmin** [comment]
Does it have a diff class?
image

**Comment by brockfanning** [comment]
@LucyGwilliamAdmin I'll go back to this. I'm wondering if maybe my fix only affects sites that are using the extra reporting status fields feature.

**Comment by brockfanning** [comment]
@LucyGwilliamAdmin I've made an attempt at fixing the spacing issue, and this is ready for review again.

**Review by LucyGwilliamAdmin — APPROVED** [review]
Looks good:
http://sdgdev-813006012.eu-west-1.elb.amazonaws.com/increasespace-rspage/reporting-status/

**Pull request merged**
