### PR TITLE
Improvements to vision of table content in high contrast mode.

### PR DESCRIPTION
**Pull request by JABedford**
Fixes some issues with visibility of content in tables that were raised in issue #2

### CODE REVIEW

**Comment by dougmet** [comment]
See http://XX.XX.XX.XX/test-high-contrast-no-merge/5-3-1/

image

**Comment by dougmet** [comment]
It's a yes from me. Would appreciate one other check and then we should merge. Actually think this should go in `0.3.1`

**Comment by dougmet** [comment]
Whoever merges, make sure you squash-and-merge, as a couple of cancelling commits slipped in.

**Comment by JABedford** [comment]
My mistake Brock. 
Commits removed.

**Pull request merged**
