### PR TITLE
Proxy indicators feature

### LINKED ISSUE #1744: Reporting Proxy data
User need = As a user, I want it to be clearer when proxy data has been used so that I can quickly understand the indicator and decide if it is relevant to my needs.

In order to fulfil the above user need the following design has been constructed. This was discussed during the tech call and is ready for development. The mock up contains notes and guidance. Any additional questions please ask. 

[Proxy_v10.pdf](https://github.com/open-sdg/open-sdg/files/9141772/Proxy_v10.pdf)

In addition the GDS insert text component can be found here: https://design-system.service.gov.uk/components/inset-text/. An example of this in use on the UK site can be found here: https://sdgdata.gov.uk/1-b-1/

### PR DESCRIPTION
**Pull request by brockfanning**
Q | A
--- | ---
Feature branch/test site URL | [Link](http://uk-sdg-feature-branches.s3-website.eu-west-2.amazonaws.com/feature-proxy-indicators/1-3-1/)
Fixed issues | Fixes #1744 
Related version | 2.2.0-dev
Bugfix, feature or docs? | Feature
* [x] Keeps backward-compatibility
* [x] Includes tests
* [x] Updated docs
* [x] Updated config forms
* [ ] Added CHANGELOG entry

This PR depends on my "proxy-indicators" branch in sdg-translations. So the config_data.yml file should be updated like this:

```
translations:
  - class: TranslationInputSdgTranslations
    source: https://github.com/brockfanning/sdg-translations.git
    tag: proxy-indicators
```

To set an entire indicator to be a "proxy", this is needed in the indicator configuration:

```
proxy: proxy
```

To set individual series within an indicator to be proxies, this is needed instead (for example):

```
proxy: both
proxy_series:
  - my first proxy series
  - my other proxy series
```

Note that tests will fail until the sdg-translations branch is merged.

### CODE REVIEW

**Comment by sarah-beasley** [comment]
Functionality seems great, thanks @brockfanning ! I was just wondering whether it's easy enough for different users to change the colours/positioning on their platforms, or is that only changeable through Open SDG repos? And how specific can you be in the positioning - just thinking in the series boxes, the pill might be a bit close to the text at the moment

image

**Comment by brockfanning** [comment]
@sarah-beasley It's easy for users to change the color and font-size through "Sass variables", but it's not easy for users to change the positioning/spacing. So I think we should tweak the positioning/spacing until we're happy with it. Should I add a bit of margin around the pill?

**Comment by AaronONS** [comment]
Hi yep I think give the pill a bit more space on the within the series boxes if we can.

**Comment by sarah-beasley** [comment]
@brockfanning is it also possible for users to change the 'proxy = description text' whenever they like, just in case we need to make any tweaks? I couldn't see where it would be in the code to do this, but I've probably missed something!

**Comment by brockfanning** [comment]
@sarah-beasley I added that extra margin. About the label and description, I added some sitewide config for controlling that. It can be used by putting this in the site configuration:

```
proxy_indicators:
  label: Proxy
  description: My alternate proxy description
```

**Comment by sarah-beasley** [comment]
Thanks @brockfanning, I added the code to the site config and it worked - will be great to be able to control that :) @AaronONS are you happy with the amended positioning of the pill in the series boxes as seen in screenshot below? (and in FB link at the top)
image

**Comment by sarah-beasley** [comment]
@brockfanning we've noticed that in smaller windows, the wrap of the text with the proxy label within the chart/table isn't quite right:
image

Also we have reviewed as a team and think that for consistency and clarification, it would be great to have this proxy label on the chart and graph when there is no series breakdown (whole indicator) too. So if you could please add that in for the whole indicator scenario, that would be great! Thanks

**Comment by brockfanning** [comment]
@sarah-beasley I believe these should be fixed if you would like to test again.

**Comment by sarah-beasley** [comment]
Happy with the fix, just holding off approving until data team have reviewed and some usability testing has been carried out by Aaron.

**Review by sarah-beasley — APPROVED** [review]
tested and approved

**Pull request merged**
