### PR TITLE
Update the chart download button when data changes

### LINKED ISSUE #313: Download Chart CSV button not working on IE

### LINKED ISSUE #392: Download chart CSV not including added series
This needs confirmation but there does seem to be a problem related to headlines and the "Download chart CSV" button. For demonstration, try the button here: https://kazstat.github.io/sdg-site-kazstat/en/1-2-1/

### PR DESCRIPTION
**Pull request by brockfanning**
Fixes #392 
Fixes #313

### CODE REVIEW

**Comment by brockfanning** [comment]
Hold off on reviewing this, I want to try something else.

**Comment by brockfanning** [comment]
@SavvasStephanides @LucyGwilliamAdmin Ok, this is ready for review.

**Comment by SavvasStephanides** [comment]
@LucyGwilliamAdmin It might be an Excel issue. The important thing is to render properly in a text editor since that's what people will use.

**Comment by LucyGwilliamAdmin** [comment]
@SavvasStephanides I actually disagree - lots of people use Excel for viewing CSVs and a lot of the time it is the default programme.

It would be great if this something that could be fixed in code but if not I'm happy to approve.

**Comment by SavvasStephanides** [comment]
@LucyGwilliamAdmin Fair enough. Since it's a CSV file I'd assume they use it as text files (with scripts etc.)

That being said, it seems to work fine when I open it in Numbers (Apple spreadsheet program)

image

**Comment by LucyGwilliamAdmin** [comment]
@SavvasStephanides yeah, definitely seems to be an Excel problem - it is possible to get the Cyrillic characters to show properly but requires some extra work (https://community.jaspersoft.com/wiki/how-import-csv-document-cyrillic-symbols-excel-and-correctly-render-them-program), which is a shame!

Never the less, I will approve now.

**Comment by brockfanning** [comment]
Maybe relevant: https://stackoverflow.com/questions/6002256/is-it-possible-to-force-excel-recognize-utf-8-csv-files-automatically

I haven't read through it though.

**Pull request merged**
