### PR TITLE
Indicator iframes

### LINKED ISSUE #2023: Embed indicators onto other indicator pages
Allow embedding indicators on other pages (discussions/2013) embedded using an iframe. Should be able to generate pages for every indicator, generate a second page and the header and footer would be hidden - so could be used to embed on other sites. Think about removing the scroll, metadata tabs, etc from the embedded indicator?

### PR DESCRIPTION
**Pull request by brockfanning**
This PR (along with https://github.com/open-sdg/jekyll-open-sdg-plugins/pull/159) create iframe-friendly versions of each indicator. The URLs of the iframe-friendly versions is the same, but with "-frame" at the end. For example the iframe-friendly version of `/1-1-1` would be `/1-1-1-iframe`.

The "iframe-friendly" part is that these new versions of the indicators do not include the sitewide header and footer. They do include other parts of the indicator pages, like the indicator header, and the metadata tabs, which in theory could be removed as well, if that is what folks prefer (let me know in the comments below). They also include usage of the Pym.js library which can be used to avoid vertical scrollbars on the iframe.

Testing instructions:

In your site repository's Gemfile, point to my other branch in jekyll-open-sdg-plugins:

`gem 'jekyll-open-sdg-plugins', git: 'https://github.com/brockfanning/jekyll-open-sdg-plugins.git', branch: 'indicator-iframes'`

In any page in your site, add some code in order to embed an indicator. For example, to create a new page that embeds an indicator, you could create a file called "my-page.md" with something like this:

```
---
title: My page
permalink: /my-page/
layout: page
---
Indicator 1.1.1 should be embedded below:

<script type="text/javascript" src="https://pym.nprapps.org/pym.v1.min.js"></script>
<div id="my-iframe-container"></div>
<script>
    var pymParent = new pym.Parent('my-iframe-container', '{{ site.baseurl }}/1-1-1-iframe', {});
</script>
```

You could also simply do an iframe directly, however then you lose out on the benefit of the Pym.js library, which is what is supposed to prevent vertical scrollbars. If you wanted to do this, it would be something like this:

```
---
title: My page
permalink: /my-page/
layout: page
---
Indicator 1.1.1 should be embedded below:

<iframe src="{{ site.baseurl }}/1-1-1-iframe"></iframe>
```

(though you'd probably also need to play around with the height and width)

Note that the automated tests here will fail until the jekyll-open-sdg-plugins PR is merged.

Q | A
--- | ---
Feature branch/test site URL | [Link](add link here)
Fixed issues | Fixes #2023 
Related version | 2.3.0-dev
Bugfix, feature or docs? | Feature
* [ ] Keeps backward-compatibility
* [ ] Includes tests
* [ ] Updated docs
* [ ] Updated config forms
* [ ] Added CHANGELOG entry

### CODE REVIEW

**Comment by christoph-LSN** [comment]
@brockfanning how do I test this? pointing to brockfanning:indicator-iframes in my site config.yml? And then creating a page including _layouts/indicator-iframe.html?

**Comment by brockfanning** [comment]
@christoph-LSN I've added testing instructions above. Thanks for trying it out!

**Comment by christoph-LSN** [comment]
Thank you @brockfanning I will test it tomorrow morning!

**Comment by christoph-LSN** [comment]
@brockfanning @MoBosse it works, more or less.

loading the pagen https://christoph-lsn.github.io/MT_Site/decision_makers/index.html first time half of the metadata tabs aren't shown. Inspecting the site or changing the size of the browser window the rest is shown.

how do I add more than one indicator on one page?

Adding a second Indicator shows only the last one.

https://github.com/christoph-LSN/MT_Site/blob/develop/_pages/decision_makers.html

````
<script type="text/javascript" src="https://pym.nprapps.org/pym.v1.min.js"></script>
<div id="my-iframe-container"></div>
<script>
    var pymParent = new pym.Parent('my-iframe-container', '{{ site.baseurl }}/1-1-1-iframe', {});
    var pymParent = new pym.Parent('my-iframe-container', '{{ site.baseurl }}/1-3-1-iframe', {});
</script>
````

**Comment by christoph-LSN** [comment]
@brockfanning 

Adding a second var and a second div works for two or more indicators.

```
<script type="text/javascript" src="https://pym.nprapps.org/pym.v1.min.js"></script>
<div id="my-iframe-container"></div>
<div id="my-iframe-container-2"></div>
<script>
    var pymParent = new pym.Parent('my-iframe-container', '{{ site.baseurl }}/1-1-1-iframe', {});
    var second = new pym.Parent('my-iframe-container-2', '{{ site.baseurl }}/1-3-1-iframe', {});
</script>
```

**Comment by christoph-LSN** [comment]
@brockfanning don't get i hurry with this issue. I am three weeks off for cycling the Pyrenees....

**Comment by christoph-LSN** [comment]
@brockfanning Thank you for your work on this issue. My decision makers decided to have a Word&Excel solution.... So I don't need this Iframe issue anymore

**Comment by sarah-beasley** [comment]
Hi @christoph-LSN , thanks for the update. We'd be keen for your opinion as you've tested this, even if you won't now actually be using. As we would still like to include the functionality as part of our next Open SDG release if possible!

**Review by sarah-beasley — APPROVED** [review]

**Pull request merged**
