### PR TITLE
Remove uppercase styling for top menu

### PR DESCRIPTION
**Pull request by SavvasStephanides**
UK feature branch: http://sdgdev-813006012.eu-west-1.elb.amazonaws.com/opensdg1_titlecasemenu/

### CODE REVIEW

**Comment by LucyGwilliamAdmin** [comment]
Looks good. Did we discuss about maybe increasing the font size now that title case is being used? I think even just going up to 15px looks fine

**Comment by brockfanning** [comment]
Side note - I'm not sure why that test is failing. I'll investigate today.

**Comment by SavvasStephanides** [comment]
> Looks good. Did we discuss about maybe increasing the font size now that title case is being used? I think even just going up to 15px looks fine

The current size is at 14px, so it's unlikely that moving to 15px is going to make much of a difference

> Side note - I'm not sure why that test is failing. I'll investigate today.

Thanks!

**Comment by LucyGwilliamAdmin** [comment]
@SavvasStephanides I know it doesn't sound like it would make that much of a difference but when I had a quick look using the inspect panel, it does actually make a difference.

14px:
image
15px:
image

**Comment by brockfanning** [comment]
About the failing test - it was apparently random failure. That unfortunately happens sometimes with javascript browser testing. If it happens a lot, a quick fix is something like "And I wait 5 seconds" just to give javascript time to work. But I just went to CircleCI and clicked "Re-run workflow from start", and it passed.

**Comment by SavvasStephanides** [comment]
> About the failing test - it was apparently random failure. That unfortunately happens sometimes with javascript browser testing. If it happens a lot, a quick fix is something like "And I wait 5 seconds" just to give javascript time to work. But I just went to CircleCI and clicked "Re-run workflow from start", and it passed.

Thanks @brockfanning !

> I know it doesn't sound like it would make that much of a difference but when I had a quick look using the inspect panel, it does actually make a difference.

@LucyGwilliamAdmin Changed the fontsize to 15px

**Pull request merged**
