### PR TITLE
Bootstrap 5

### PR DESCRIPTION
**Pull request by brockfanning**
This PR is to allow an optional upgrade to Bootstrap 5. In order to use this, the site configuration "bootstrap_5" needs to be true. Eg:

```
bootstrap_5: true
```

This depends on a PR in jekyll-open-sdg-plugins: https://github.com/open-sdg/jekyll-open-sdg-plugins/pull/125

Possible scenarios to test (not all need to be feature-branches - some could maybe be screenshots):

* at least two languages, eg:

        languages:
           - en
           - es
           
* language toggle using links, eg:

        header_language_toggle: links

* using "content" for at least one goal, eg:

        create_goals:
          goals:
            - content: My goal 1 content

* using previous/next links for indicators and goals, eg:

        create_goals:
          previous_next_links: true
          
        create_indicators:
          previous_next_links: true
               
* dropdowns in menu, eg:

        menu:
          - path: unneeded-path
            translation_key: My dropdowns
            dropdown:
              - path: about
                translation_key: Another link to about page

Feature branch: http://uk-sdg-feature-branches.s3-website.eu-west-2.amazonaws.com/feature-site-bootstrap-5/

### CODE REVIEW

**Comment by brockfanning** [comment]
@otis-bath @LucyGwilliamAdmin @phillipgardiner I thought I would start a PR for this, even though it is not finished. At the time of writing it should be ready to review the frontpage, including the new hamburger-style mobile menu. So feel free to start a feature branch, but again only the frontpage is ready for review.

One question I had was: Should the hamburger menu get the same darker treatment that it does right now? I've left it at the default white background, but I could change it to a darker background to match what we have currently.

**Comment by LucyGwilliamAdmin** [comment]
@brockfanning @phillipgardiner @otis-bath I've just added link to description for feature branch (thanks for creating Otis!)

My thoughts re. hamburger menu so far are should the search bar be underneath when the menu is open? i.e. like what happens here: https://getbootstrap.com/docs/5.1/getting-started/introduction/

**Comment by otis-bath** [comment]
@brockfanning @LucyGwilliamAdmin @phillipgardiner thought I added a comment on this with my thoughts on the FB but might have just been thinking aloud.

 Agree this looks better but would say there is no way to really tell any of the options are links as they are still in the grey text with no boxes or colour differentiation. Agree with your point Lucy, feel like the hamburger menu should be further down if the search bar is staying there as the button doesn't do anything to it

**Comment by phillipgardiner** [comment]
@brockfanning @otis-bath @LucyGwilliamAdmin For me is is less about weather it gets the darker treatment and more about ensuring the logo, search bar and hamburger menu work / look right together.

I think Lucy comment about placement of the search box is valid. I think we also need to consider the logo, size and placement in order for it too look right.

**Comment by LucyGwilliamAdmin** [comment]
Changes for next iteration:
1. move search bar below extended menu
2. bring hamburger in line with logo
3. Apply old link colour to links

**Comment by brockfanning** [comment]
@otis-bath Would you be able to do a refresh of the feature branch when possible?

Some specific notes:
1. Moving the search below the menu proved to not be so difficult, thanks to the fact that on desktop it can be in the absolute upper right. This allows me to use "absolute" positioning on desktop, whereas on mobile it appears below the menu.
2. Bring the hamburger in line with the logo: I've tried the same approach as with the search bar, which is to use "absolute" positioning, and have it 10 pixels down from the top of the container.
3. Apply old colour to links: This should be done now, but let's stay vigilant for any other places where I've missed something.
4. Make sure custom CSS is applied: Actually this was already happening, but there are apparently some interesting points on this subject:
    1. In Bootstrap 3, the button styles included `font-size: 14px` and `white-space: nowrap`. In Bootstrap 5, it is `font-size: 1rem` and nothing about white-space. This has the effect of making the "Take part in user research" button text wrap, because of [custom UK styling](https://github.com/ONSdigital/sdg-indicators/blob/develop/_sass/custom.scss#L59) that is limiting the width of the button. It's not obvious how we should handle cases like this and maybe could be discussed on a tech call.
    2. Open SDG had [code in the footer styling to float images and give them some margin](https://github.com/open-sdg/open-sdg/blob/1.8.0-dev/_sass/layouts/_footer.scss#L9-L13). I can't think of why that code is there. I have not yet added it to this PR, and so that is why the OGL license in the footer is messed up. I guess we do have to bring it over, since it was already there, but I thought I'd bring it up. Maybe it is there from some previous functionality where we had images appearing in the footer? I can't remember any though.

**Comment by otis-bath** [comment]
Hi @brockfanning, refreshed this morning and a definite improvement. Search displaying below menu and hamburger has dropped in line with the logo. When we are talking about old colour applying to links what are we referring to - is this that when the links are clicked through on the menu the box highlights yellow?

Agree would be worth discussing the user research box as is quite intrusive. Thanks

image

**Comment by phillipgardiner** [comment]
@otis-bath _When we are talking about old colour applying to links what are we referring to?_ This is referring to the colours of the hyperlinks in both a unvisited (blue) and visited (purple) state.

**Comment by phillipgardiner** [comment]
- 

> Ah thanks @phillipgardiner - this is not showing currently in the hamburger menu then


> Ah thanks @phillipgardiner - this is not showing currently in the hamburger menu then
 It won't appear on the menu items, this is in reference to all the other hyperlinks on the homepage only

**Comment by phillipgardiner** [comment]
@brockfanning thanks for updating this so quickly. 

- Is it just me or is the hamburger menu still slightly higher than the logo? It is quite possibly just me or just a trick of the eye but it looks like it is marginally higher still (is it aligning with padding of the image or something weird like that?)
- I've got this screenshot from my iPhone, as you can see the hamburger appears stretched / elongated?
hamburger_iphone
- Yep lets discuss custom styling, buttons etc on next tech call

**Comment by brockfanning** [comment]
@phillipgardiner I can double-check on the alignment of the navbar toggle and the logo image. If there's any extra padding in the image itself then it will definitely appear to be slighly off, but I will try to make sure that  the top of the toggle is at least aligned with the top of the logo image.

Regarding the issues on the iPhone: I should mention, that the toggle behavior where it animates into an "X" -- that is not Bootstrap core - that's actually some custom code I found on a blog post. I was going to ask if that's too cute, and maybe it should just be a normal hamburger icon. Maybe what I'll do for now is go back to a normal hamburger icon, and then we can revisit if needed. I suspect that will solve the iPhone problem.

**Comment by brockfanning** [comment]
@otis-bath This is ready for another refresh in order to test the goal pages, but I've added some instructions in the top post on how to use the Bootstrap 5 version of the goal layout.

@phillipgardiner Once the feature branch has been refreshed you should see the default navbar toggle, aligned similarly with the logo.

All, please take a look at goal pages, after the feature branch has been refreshed.

**Comment by otis-bath** [comment]
@brockfanning @phillipgardiner @LucyGwilliamAdmin - have refreshed this FB, the hamburger menu is now in line as intended however I'm not sure what has happened to the goal pages. I have toggled the 
create_goals:
  layout: goal-bootstrap5 
in the site configuration but looks very clustered

**Comment by LucyGwilliamAdmin** [comment]
@phillipgardiner @brockfanning @otis-bath feature branch has been refreshed and here's the feature branch with the goal-with-progress layout as a reminder: http://uk-sdg-feature-branches.s3-website.eu-west-2.amazonaws.com/feature-progress-testing/1/

**Comment by brockfanning** [comment]
@LucyGwilliamAdmin @otis-bath I'm confused by the links above. Just checking the feature branch for this PR, it looks like the homepage is messed up now, and the goal pages are not showing progress. I'll investigate more.

**Comment by phillipgardiner** [comment]
@LucyGwilliamAdmin @otis-bath @brockfanning Sorry what are we supposed to be doing? Are we suppose to be comparing and pointing out anything that's different between versions. Sorry for my confusion! Happy to do that if that's the plan.

One thing I did already notice on the Bootstrap 5 homepage is that everything is bigger. E.g. the actual page is wider than the existing page and therefore all images etc are larger - is that on purpose?

**Comment by brockfanning** [comment]
To be clear about the Bootstrap upgrade in general: by upgrading the version of Bootstrap, various things will definitely change. My first priority here is to make things generally look good and close to what we had. I won't try to make everything 100% identical for now, because that would be a lot of work. But that doesn't mean we can't go for that. But I didn't think I should do extra work to change things that might actually look better in Bootstrap 5. For example maybe the wider page is a good thing? To that specific point, Bootstrap 5 does have a new "extra extra large" breakpoint, and maybe that is what's happening. But definitely if you notice changes that are not an improvement, we should do the work to fix those.

For some reason the goal tiles on the homepage are invisible when I use Firefox - that's what I was seeing (and am still seeing) on the homepage. The goal pages are looking as expected to me now.

**Comment by brockfanning** [comment]
@phillipgardiner Reading some more through the upgrade docs for Bootstrap 4 and 5, it does seem like they have increased the font size from what it was in Bootstrap 3. If fonts are looking too big we could look into overriding the Bootstrap font sizes to keep them smaller.

@otis-bath This is ready for another refresh. I believe I've got most/all pages done now. Note there are a couple more config changes needed to see the indicator and reporting-status pages. I've updated the top post.

The problem I mentioned above with Firefox might be fixed now.

**Comment by phillipgardiner** [comment]
@brockfanning understood, I guess therefore it will be a case of identifying what's different and then deciding if the change is a negative or positive.

**Comment by otis-bath** [comment]
Hi @brockfanning @LucyGwilliamAdmin @phillipgardiner 
So I have refreshed the main FB http://uk-sdg-feature-branches.s3-website.eu-west-2.amazonaws.com/feature-site-bootstrap-5/ and made the suggested changes to the site config to alter the indicator pages and reporting-status page. 

From what I have noticed on the indicator pages, when there are multiple series' the boxes have bunched up next to one another. The maps are not loading in (is this expected for now?) and the links to the global metadata and sources are not working even though the URL is changing when each link is clicked. 

The reporting-status page looks good and the tabs work as intended on there the only obvious difference being the wider view.

**Comment by LucyGwilliamAdmin** [comment]
@brockfanning @phillipgardiner @otis-bath I get the same as Otis but just commenting to say don't know if on purpose but I actually prefer the radio buttons right next to each other i.e. like this:
image
instead of this:
image

**Comment by phillipgardiner** [comment]
@brockfanning @otis-bath @LucyGwilliamAdmin so I have reviewed the main FB (http://uk-sdg-feature-branches.s3-website.eu-west-2.amazonaws.com/feature-site-bootstrap-5/) and listed all the things I have spotted in this spreadsheet 
([Bootstrap5_changes.xlsx](https://github.com/open-sdg/open-sdg/files/8205926/Bootstrap5_changes.xlsx). Not 100% sure if that was the intention, but a useful exercise non the less. Guess we can discuss on todays tech call. 

@LucyGwilliamAdmin In regard to the radio buttons above, we would ideally need to keep the space between them, as this follows best practices etc for radio buttons.

**Comment by LucyGwilliamAdmin** [comment]
Brock will make Phill's suggested changes to the main feature branch. Between us we will come up with a list of scenarios/options that need testing - Lucy and Otis will create feature branches.

**Comment by LucyGwilliamAdmin** [comment]
@brockfanning I've removed the file that was overwriting the metadata section but there still seems to be issues

**Comment by brockfanning** [comment]
@otis-bath This can be refreshed whenever you have time. I believe I've addressed the things mentioned so far. However I think there is still a problem with maps, that I'm still looking into.

@phillipgardiner I've added a column with some notes on what I changed. A couple rows are marked TBD because I think we could cover them during a call. And one row (row 34) I need clarification on (either I'm not seeing it, or it got fixed elsewhere).
[Brock's changes - Bootstrap5_changes.xlsx](https://github.com/open-sdg/open-sdg/files/8223216/Bootstrap5_changes.xlsx)

**Comment by brockfanning** [comment]
One annoyance I'm noticing is that clicking a metadata tab changes the browser's scroll position. I'm trying to figure out what that's happening.

**Comment by LucyGwilliamAdmin** [comment]
@brockfanning re your last point, it seems like that already happens - I think probably because depending on what tab you are viewing the length of the page changes

**Comment by brockfanning** [comment]
It does seem to happen a bit sometimes on the live site - but for me it's worse on this feature branch. In particular, sometimes when I click on one of the metadata tabs, the page scrolls up to the top of the chart - which is odd. Not all the time though. I'm trying to figure out a pattern but haven't yet.

**Comment by LucyGwilliamAdmin** [comment]
@brockfanning is there a particular indicator it's happening on? I did have a similar thing happening yesterday before the metadata tabs were fixed, and when I looked in URL, #tab-global had been added to the end - are you getting that?

**Comment by otis-bath** [comment]
@LucyGwilliamAdmin @brockfanning I'm not getting this issue now but was seeing it before on the FB. The URL was changing before the latest commit but that has been fixed now and the tabs are functioning without issue as far as I can see?

**Comment by brockfanning** [comment]
Quick note - the issue I was noticing with the scroll position happens in Firefox, but I'm not seeing the problem in Chrome.

**Comment by LucyGwilliamAdmin** [comment]
@brockfanning ok, that makes sense why I'm not seeing the same behaviour then as using Chrome!

**Comment by phillipgardiner** [comment]
@brockfanning @LucyGwilliamAdmin @otis-bath This sis looking great, I have whizzed through the spreadsheet and changes, couple of comments from me though:

- Row 12 of spreadsheet - Thanks for getting rid of padding but I think it's all now too tight, perhaps we could put 10px back? (but the horizontal and vertical gaps between tiles would need to be the same size)
- Row 28 of spreadsheet - I'm still not seeing an 'x' on the clear selections button still?
- Row 34 of spreadsheet - Is referring to the issue Lucy rasied above (https://github.com/open-sdg/open-sdg/pull/1558#issuecomment-1060695621)
Additionally I have noticed a couple of additional things
-  on indicator http://uk-sdg-feature-branches.s3-website.eu-west-2.amazonaws.com/feature-site-bootstrap-5/15-2-1/, in the sources tab, the row 'link to data source' the text which says 'open in a new window' is now visible. I believe on the live site, this text is visually hidden but read by screen readers.
- The space between the main navigation and the breadcrumbs has decreased, can this be increased

That's all for now, happy to do another run through next week or sometime when we believe all is done just to check if we have missed anything.

**Comment by brockfanning** [comment]
@otis-bath This can be refreshed when you have a chance. I believe I've addressed everything mentioned so far, including maps, the goals page, and the items in the latest feedback from @phillipgardiner. The only thing I know of that I haven't resolved is that Firefox tab-related annoyance that I mentioned.

Quick tech note - I had switched from "Font Awesome" icons to "Bootstrap Icons", but now I've switched back, because parts of the map stuff depend on Font Awesome. So, you may have noticed some slight differences in icons, but now they should be back to the same as we have now.

**Comment by otis-bath** [comment]
Great thanks @brockfanning - can see the maps working (apart from 10-3-1 which is a separate issue) and the Goals page also looks much better than before.

@phillipgardiner when you are back and get the chance could you have a look at the design aspects you raised on Thursday again and the new Goals page now as well? Cheers

**Comment by brockfanning** [comment]
@otis-bath Another thing you could try: If you point the Gemfile to a PR on the jekyll-open-sdg-plugins repo, you can avoid needing all the extra config changes -- all you need is `bootstrap_5: true`.

The Gemfile would need to have:

```
gem 'jekyll-open-sdg-plugins', git: 'https://github.com/brockfanning/jekyll-open-sdg-plugins.git', branch: '2.0-deprecation-warnings'
```

Then you would not need to have the config about `goal-bootstrap5`, `indicator-bootstrap5`, `reportingstatus-bootstrap5`, etc.

The idea with this is to make it easier for people to try out Bootstrap 5, by changing only 1 setting.

**Comment by otis-bath** [comment]
That's great thanks @brockfanning

**Comment by phillipgardiner** [comment]
@otis-bath @brockfanning gets my thumbs up - thank you

**Comment by phillipgardiner** [comment]
@brockfanning @otis-bath I have been through and checked the remain pages. I have added anything else spotted to this spreadsheet (rows 38 to 47) [Bootstrap5_changes_updated.xlsx](https://github.com/open-sdg/open-sdg/files/8255409/Bootstrap5_changes_updated.xlsx)
 . Happy to run through anything again once the scenarios etc have been decided. Thanks.

**Comment by otis-bath** [comment]
@brockfanning @LucyGwilliamAdmin I have created a FB with the language toggle incorporated here http://uk-sdg-feature-branches.s3-website.eu-west-2.amazonaws.com/feature-bootstrap-5-language/ In the mobile view this is within the hamburger menu and relatively large so might need some rescaling here as discussed if its all going to fit on the single line. Thanks

**Comment by brockfanning** [comment]
@otis-bath This can be refreshed now. It includes a revamped header.

@phillipgardiner The latest changes address most of the items you mentioned. A few notes though:
* I think the items about the Cookies page are already happening on the live site, and also that is a custom UK page, so it's possible that should be address in a separate ticket.
* The items about the Publications and Updates pages might need discussion. One difference between Bootstrap 3 and 5 is that in Bootstrap 3 the margin below paragraphs is 10px, and in Bootstrap 5 the margin below paragraphs is 1rem.

**Comment by otis-bath** [comment]
@brockfanning - great thanks. Only thing with this header, all links working okay and looking as they should but when you are on the frontpage and hover over the links in the header, the content is pushed down ever so slightly which doesn't occur on the other pages.

**Comment by brockfanning** [comment]
@otis-bath I just pushed a change that should hopefully fix that.

**Comment by brockfanning** [comment]
I've also added a few scenarios in the top post. I know it's a lot, so maybe not all of them need to be feature-branches. I'd be happy to test some locally and post screenshots.

**Comment by brockfanning** [comment]
Screenshot of the `header_language_toggle: links` scenario:
screenshot-127 0 0 1_4000-2022 03 17-06_58_38

**Comment by brockfanning** [comment]
Screenshots of the menu with dropdowns (collapsed and expanded):
screenshot-127 0 0 1_4000-2022 03 17-07_00_54
screenshot-127 0 0 1_4000-2022 03 17-07_02_55

**Comment by brockfanning** [comment]
I see that the chart image download is not working great - I'll see if I can improve that.

**Comment by brockfanning** [comment]
The latest commit should improve the downloaded chart image.

**Comment by phillipgardiner** [comment]
@brockfanning @otis-bath @LucyGwilliamAdmin just catching up on all the comments made yesterday, my comments...

@LucyGwilliamAdmin on the cookie page there is text that is not the right size. This is UK only, where do we need to stick a ticket to address this at some point (low priority). Github or Trello Product backlog?

@otis-bath The next / previous feature branch all looks good, but could we potentially add a ticket somewhere (Github?) to change the colour from the bright blue currently used, I believe we could use something more appropriate here (low priority)

@brockfanning in regard to the chart download (good spot :)). Is it possible to get the chart title all on one line (as per current experience (e.g. 1.2.1). Also are units of measure and geographical area supposed to appear in the footnote as they are not displayed?

@brockfanning in regard to the spacing on the publication and update page. Do we have any options? The issue is if you look at the 2nd, 3rd, results you are not really able to tell if the date belongs to the result above or the one below. 

Other than the comments above, I have looked at all the feature branches created by Otis and they all look good. :)

**Comment by brockfanning** [comment]
@phillipgardiner I guess the image download still needs some work, I'll look into it.

The Publications page is custom for the UK, so I think the only thing to do there is play around with line-breaks in your content.

The Updates page is something we can fix though - I think our options are:
1. Increase the margin-bottom on the dates, so that the next news item is further away
2. Decrease the margin of the last paragraph before the date, so that the date is closer to the last paragraph

**Comment by phillipgardiner** [comment]
@brockfanning I would go with 'Decrease the margin of the last paragraph before the date, so that the date is closer to the last paragraph', however is only needs to be marginal, see https://sdgdata.gov.uk/updates/. thanks

**Comment by brockfanning** [comment]
@otis-bath This can be refreshed when convenient. If you haven't already, can you make sure there's a FB with bootstrap_5 set to false?

**Comment by otis-bath** [comment]
@brockfanning - have refreshed this branch and all working as before from what I can see. Have also created the branch with it set to off http://uk-sdg-feature-branches.s3-website.eu-west-2.amazonaws.com/feature-site-bootstrap-5-off which has the Gemfile set to the deprications notice branch and bootstrap off and is looking and working like the current live site. 

@phillipgardiner - the main branch http://uk-sdg-feature-branches.s3-website.eu-west-2.amazonaws.com/feature-site-bootstrap-5/ has been refreshed, did you want to check the margins/downloads are as you would expect?

**Comment by phillipgardiner** [comment]
@otis-bath Yep checked margins and downloads and all looking good, @brockfanning thank you.

**Comment by brockfanning** [comment]
@otis-bath Sounds great, I don't know of anything else needed here, so I'm ready to squash/merge when you approve.

**Review by phillipgardiner — APPROVED** [review]
@otis-bath @brockfanning happy to approve design elements

**Pull request merged**
