### PR TITLE
aria-describedby for no-data-hint

### LINKED ISSUE #929: Ensure "No options available..." message is programmatically associated with its field
**URL:** http://sdgdev-813006012.eu-west-1.elb.amazonaws.com/dac2020/3-b-1/

**Screen shot:**

The hint text ("No options available because of the filters above") describing the dependency is not programmatically associated with the field.

**Solution:**
Please use an aria-describedby attribute to programmatically associate instructions with the field.

### PR DESCRIPTION
**Pull request by brockfanning**
Fixes #929

### CODE REVIEW

**Comment by jwestw** [comment]
Feature branch: http://sdgdev-813006012.eu-west-1.elb.amazonaws.com/jw-test-no-data-hint-aria

**Comment by jwestw** [comment]
The screen reader reads "No options available because of the filters above" on both https://sdgdata.gov.uk/3-b-1/ and in my feature branch http://sdgdev-813006012.eu-west-1.elb.amazonaws.com/jw-test-no-data-hint-aria/3-b-1/ . 

I can see the difference in the code, but I am not sure what behaviour changes I should be observing here.

**Comment by brockfanning** [comment]
@jwestw Can you describe _when_ the screenreader announces that? If the screenreader is announcing it when you tab to the button, I think that is the intended behavior.

**Comment by LucyGwilliamAdmin** [comment]
@jwestw just looked at this, and for me it's not read out on live site but is on your feature branch

**Comment by jwestw** [comment]
> @jwestw just looked at this, and for me it's not read out on live site but is on your feature branch

I think we had this difference before, didn't we? In setup, it has the desired behaviour in both branches. So as long as you are seeing it in the feature branch and it wasn't appearing before, then it is fixed.

**Review by jwestw — APPROVED** [review]
Approving on the basis of what Lucy has found.

**Pull request merged**
