### PR TITLE
Make indicator links in goal page appear clickable

### PR DESCRIPTION
**Pull request by SavvasStephanides**
This change makes it clearer that the indicator cards on the goal page are actually clickable. This also sets the goal page layout to `goal-by-target`.

#### Default contrast

image

#### High contrast

image

#### Default contrast

image

### CODE REVIEW

**Comment by brockfanning** [comment]
@SavvasStephanides Just so you know, in the automated tests the normal goal pages use the "goal" layout, but I've got a custom goal page using the goal-by-target layout. That custom goal page can be reached at /testing-goal-by-target/. (See [here](https://github.com/open-sdg/open-sdg/blob/master/tests/site/_goals/goal-by-target.md)). So if you want to make sure goal-by-target gets tested, we could add that path to the pa11y configurations.

Also a nitpick, instead of "blue" I would recommend #337ab7 - it's what we're using for link color, I believe it comes from Bootstrap.

**Comment by brockfanning** [comment]
Also if I'm interpreting the test failure right, it doesn't like the tags' yellow background with the blue text? If it still fails with #337ab7 we might have to keep the tags' text black, or make the tags' yellow background fainter.

**Comment by SavvasStephanides** [comment]
> if you want to make sure goal-by-target gets tested, we could add that path to the pa11y configurations.

Good idea.

> Also if I'm interpreting the test failure right, it doesn't like the tags' yellow background with the blue text? If it still fails with #337ab7 we might have to keep the tags' text black, or make the tags' yellow background fainter.

Possibly a darker colour will fix this. Maybe keep it black as it was?

**Comment by SavvasStephanides** [comment]
A bit strange that the contrast tests are still failing on high contrast. Pretty sure everything is black on yellow or vice versa.

image

**Comment by brockfanning** [comment]
@SavvasStephanides Check the Pa11y output - it says the errors on on the goal 1 page in the high contrast tests. I'd recommend doing a `make serve` and looking at goal 1 in high contrast.

**Comment by SavvasStephanides** [comment]
@brockfanning That's what I did. That's where the screenshot above comes from.

EDIT: Turns out, the problem is in the `goal` layout of the goal page 🤦‍♂️

image

**Comment by SavvasStephanides** [comment]
@brockfanning Tests pass now. Ready for re-review

**Comment by brockfanning** [comment]
@SavvasStephanides A couple of pieces of feedback:
1. In high-contrast mode, the indicator status ("Reported online", etc.) is blue, but I think it should be black
2. Regarding the tags - I don't think this PR should change anything tag-related. I believe the expert-review feedback here was just about the indicator titles, so tags should stay black, on both normal and high contrast.

**Comment by SavvasStephanides** [comment]
Thanks for the feedback @brockfanning 

> 1. In high-contrast mode, the indicator status ("Reported online", etc.) is blue, but I think it should be black

Good point

> 2. Regarding the tags - I don't think this PR should change anything tag-related. I believe the expert-review feedback here was just about the indicator titles, so tags should stay black, on both normal and high contrast.

That was the original styling but the tests kept failing and recommending I use the blue colour it is now. I'll revert back and see if it does it again.

**Comment by brockfanning** [comment]
@SavvasStephanides Should I review again or is it still in progress?

**Comment by SavvasStephanides** [comment]
@brockfanning This is ready for review.

**Comment by SavvasStephanides** [comment]
@brockfanning Last change was just resolving merge conflicts

**Comment by brockfanning** [comment]
@SavvasStephanides I'm still seeing blue text on the tags.

**Comment by SavvasStephanides** [comment]
@brockfanning Maybe it reverted back when I tried to resolve the merge conflict. I'll have a look

**Comment by brockfanning** [comment]
@SavvasStephanides To be more clear - I'm seeing blue text on the tags in normal contrast mode.

**Comment by SavvasStephanides** [comment]
@brockfanning Ready for re-review. Should turn the tag colour to black.

**Pull request merged**
