### PR TITLE
Yellow hover color for disaggregation values in dropdown

### LINKED ISSUE #1115: Change disaggregation control row highlight colour in high contrast mode
When a user moves thier mouse over the rows within a disaggregation control that row is highlighted. Currently the colour used is: grey #F5F3F3. 

Could this be changed to yellow #ffdd00 in order to match the same functionality on the table rows..

### PR DESCRIPTION
**Pull request by brockfanning**
Q | A
--- | ---
Feature branch/test site URL | [Link](add link here)
Fixed issues | Fixes #1115 
Related version | 1.3.0-dev
Bugfix, feature or docs? | Bugfix
Keeps backward-compatibility? |✔️
Updated docs/config-forms? |NA
Added CHANGELOG entry? |❌

### CODE REVIEW

**Comment by jwestw** [comment]
On the [feature branch](http://sdgdev-813006012.eu-west-1.elb.amazonaws.com/disaggregation-control-row-hover/2-1-1/), this seems to be working:

image


@phillipgardiner Please can you confirm that this is working and solves #1115 ?

**Comment by phillipgardiner** [comment]
@jwestw This is to solve #1115 but, nope the yellow should be #FFDD00. Not sure if this is something to do with the order in which you build feature branches or something though? as there are other things wrong on this feature branch which have been addressed on other feature branches.

**Comment by jwestw** [comment]
Thanks @phillipgardiner I was also trying to check if it is #ffdd00. When I googled it, it looked similar but possibly not the same due to it being on a different background. And that it certainly wasn't the original #F5F3F3 so thought maybe it was fixed.

I probably wouldn't be too concerned about other features if they have been fixed just recently. However if there's something more fundamental broken, then we might need to raise it with Brock. What unexpected behaviour are you seeing?

**Comment by phillipgardiner** [comment]
@jwestw I think its probably me just getting confused with how feature branches are used. but for instance in this one: https://github.com/open-sdg/open-sdg/pull/1117#pullrequestreview-598503376, the error message is fixed. But then in the one for this ticket the error message is how it was originally.

Either way for this ticket the yellow should be #FFDD00

**Comment by brockfanning** [comment]
@phillipgardiner I think I was basing this off the table hover styles - in the table hover styles it looked like we're using "yellow" and not "ffdd00".

**Comment by phillipgardiner** [comment]
@brockfanning umm weird i could have sworn I'd seen the table rows in #FFDD00? Oh well might have been me playing with the colours in the 'inspect window' instead! Can we change it to #FFDD00 please?

**Comment by phillipgardiner** [comment]
@brockfanning found it http://sdgdev-813006012.eu-west-1.elb.amazonaws.com/chart-color-accessibility-revamp/1-2-1/ thought I was going mad then!

**Comment by brockfanning** [comment]
Ah! I guess we updated that color in another PR, which has since been merged. I guess my memory only goes back a few PRs... :)

I have merge the latest code into this branch, which should resolve it after a feature branch refresh.

**Comment by jwestw** [comment]
The [feature branch](http://sdgdev-813006012.eu-west-1.elb.amazonaws.com/disaggregation-control-row-hover/) should have been refreshed.

**Comment by phillipgardiner** [comment]
@brockfanning Tell me about it, my brain is gonna explode with all the changes and PRs going on :)

@jwestw - Looks good to me 

Thanks both

**Review by jwestw — APPROVED** [review]
Approving according to my tests and Phil's last comment.

**Pull request merged**
