### PR TITLE
Update data download card to use new translations

### LINKED ISSUE #1727: Change download button wording
**To do:** Change the wording of the SDG download buttons.

From > To
- Download Chart Image > Download chart image (.png)
- Download Chart CSV > Download chart data (.csv)
- Download Source CSV > Download source data (.csv)
- Download all data > Download all data (.zip)

Additionally for .zip. The sentence immediately under the buttons ' ZIP file - 47.7 MB etc' is to be replaced with 'Size: 46.4 MB, Data last updated: 04 July 2022'

@brockfanning I understand there are also additional buttons not currently used in the UK such as CSVW. The same format should be used for these. If you can let me know what additional buttons exist I can advise.

### PR DESCRIPTION
**Pull request by brockfanning**
This PR depends on an sdg-translations PR: https://github.com/open-sdg/sdg-translations/pull/290

Q | A
--- | ---
Feature branch/test site URL | [Link](http://uk-sdg-feature-branches.s3-website.eu-west-2.amazonaws.com/feature-download-button-update/1-1-1/)
Fixed issues | Fixes #1727 
Related version | 2.1.0-dev
Bugfix, feature or docs? |
* [ ] Keeps backward-compatibility
* [ ] Includes tests
* [ ] Updated docs
* [ ] Updated config forms
* [ ] Added CHANGELOG entry

### CODE REVIEW

**Review by otis-bath — APPROVED** [review]
This looks good @brockfanning, just wanted to confirm you are happy with this @phillipgardiner - the text on the download buttons has changed to what we agreed previously

**Review by phillipgardiner — COMMENTED** [review]
@otis-bath I'm happy with the ones that I can see but unable to see the ones such as the SDMX button to say yes or no. 

Additionally not sure if it ended up being part of this ticket or an addtional ticket but it was mentioned on ticket: https://github.com/open-sdg/open-sdg/issues/1727 that...Additionally for .zip on the homepage. The sentence immediately under the buttons ' ZIP file - 47.7 MB etc' is to be replaced with 'Size: 46.4 MB, Data last updated: 04 July 2022'

**Comment by brockfanning** [comment]
@otis-bath The feature branch needs to point at the remote_theme brockfanning/download-button-update in order to see the change @phillipgardiner mentions above.

**Comment by otis-bath** [comment]
@brockfanning - my bad missed this when building the FB. @phillipgardiner - this should now be complete

**Review by phillipgardiner — APPROVED** [review]
Looks good :)

**Pull request merged**
