### PR TITLE
Style fixes for data edit form

### LINKED ISSUE #1659: Button placement on data edit page
**Please complete the following information** 
Site repository URL: https://open-sdg.org/open-sdg-site-starter/1-1-1/data/
Open SDG version: 1.8.0

**Describe the bug**

The buttons at the top of the data edit page are placed incorrectly.

**To Reproduce**
1. Go to any indicator
2. Click on "Edit data"
3. Note the jumbled button placement

**Expected behavior**

They should be aligned neatly along the right.

**Screenshots**

Screenshot from 2022-06-09 06-34-26

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser: Firefox
 - Version: latest

### PR DESCRIPTION
**Pull request by brockfanning**
Q | A
--- | ---
Feature branch/test site URL | [Link](http://uk-sdg-feature-branches.s3-website.eu-west-2.amazonaws.com/feature-site-data-form-button-placement/1-1-1/data/)
Fixed issues | Fixes #1659 
Related version | 2.0.0-dev
Bugfix, feature or docs? | Bugfix
* [ ] Keeps backward-compatibility
* [ ] Includes tests
* [ ] Updated docs
* [ ] Updated config forms
* [ ] Added CHANGELOG entry

### CODE REVIEW

**Comment by brockfanning** [comment]
@otis-bath I think this broke when we switched to Bootstrap 5.

**Comment by otis-bath** [comment]
@brockfanning Have this on a FB here: http://uk-sdg-feature-branches.s3-website.eu-west-2.amazonaws.com/feature-site-data-form-button-placement/1-1-1/data/
Should there still be the 'Go to repository' button as this seems to be missing?

**Comment by brockfanning** [comment]
@otis-bath @phillipgardiner This ticket was intended only to fix a bug - the button placement got messed up when we switched to Bootstrap 5. I'm happy to make more improvements but I think that should be done separately from this bugfix.

**Comment by phillipgardiner** [comment]
@brockfanning sorry do we have a ticket for minor improvements to the data edit form? There are a couple of minor points i'd like to add to it that came up in the expert review we undertook.

**Comment by brockfanning** [comment]
@phillipgardiner I made a ticket for configuration forms in general - #1674 - but it's more about the other config forms. If you could start a new issue for the points I can reference it from the general one. (Or you could put them in the general one if that would be more appropriate.)

**Pull request merged**
