### PR TITLE
Add data notice above catch-all

### PR DESCRIPTION
**Pull request by LucyGwilliamAdmin**
Feature for #295

### CODE REVIEW

**Comment by LucyGwilliamAdmin** [comment]
@brockfanning made those changing. Can be seen working [here](https://sdg.mango-solutions.com/data-notice-test1/1-1-1/)

**Comment by LucyGwilliamAdmin** [comment]
There's 3 fields which can be used in the metadata file to configure this box:
* data_notice_heading
* data_notice_text
* data_notice_colour - there's 3 set options for this: [success](https://sdg.mango-solutions.com/data-notice-test1/1-1-1/), [danger](https://sdg.mango-solutions.com/data-notice-test1/1-2-1/) and [warning](https://sdg.mango-solutions.com/data-notice-test1/1-2-2/)

I did start taking a look at adding some set neutral options following Matt's feedback but didn't want to do too much on it until we've decided if and how we're going to use them.

**Comment by brockfanning** [comment]
Looking good. A few more comments:
1. Not a huge deal, but since the options are success/warning/danger, maybe a more accurate field name would be something like "data_notice_level", or "data_notice_type", or if you want to get totally technical, "data_notice_class".
2. We should add some documentation of this feature in [this file](https://github.com/open-sdg/open-sdg/blob/master/docs/metadata-format.md).
3. This might be a good chance to try out adding an automated test. If you're interested, here would be the steps:
    1. Add the required metadata to a particular indicator, such as 1.2.1 in [this file in the testing data repo](https://github.com/open-sdg/open-sdg-data-testing/blob/develop/meta/1-2-1.md). For example you might give it a `data_notice_heading` of "My data heading".
    2. Add a new file [here](https://github.com/open-sdg/open-sdg/tree/master/tests/features) called something like `DataNotice.feature`
    3. Use another of the .feature files as a guide. The "scenario" might be something like:
        ```
        Scenario: Data notices appear on indicator pages
            Given I am on "/1-2-1"
            Then I should see "My data heading"
        ```
    Thereafter, we could rest assured that the data notice functionality would never get broken. :)

**Comment by brockfanning** [comment]
@LucyGwilliamAdmin A note about custom selectors in tests. You could add the following to [this file](https://github.com/open-sdg/open-sdg/blob/master/tests/features/support/mink.js):

```
"success data notice": "div.alert.success",
```

And then I believe your step in the test would be the following:

```
Then I should see 1 "success data notice" element
```

**Comment by brockfanning** [comment]
Also generally each "Scenario" has a different name, depending on what is being tested. In this case, actually, I think you could put all the steps into a single scenario, like maybe:

```
  Scenario: Data notices appear on indicator pages
    Given I am on "/1-2-1"
    Then I should see "My data notice heading"
    And I should see "My data notice text"
    And I should see 1 "success data notice" element
```

**Pull request merged**
