### PR TITLE
FAQ: Update mapping and embedded content examples

### PR DESCRIPTION
**Pull request by Norric1Admin**
@AnnCorp Here's an [example](https://github.com/open-sdg/open-sdg/edit/Norric1Admin-patch-1/docs/faq.md) of how this would look - click 'Preview'.

Hold off on this until tomorrow, as the 3.4.2 embed is no longer live.

### CODE REVIEW

**Comment by AnnCorp** [comment]
Can’t seem to access the preview at the moment…

**Comment by Norric1Admin** [comment]
@AnnCorp Here's how it would look:
image

**Comment by brockfanning** [comment]
@Norric1Admin This has a conflict because of a recent change. Is this update still needed? If so, you could either try the "resolve conflicts" approach, or just close it and start a new PR with the same changes. Whichever you prefer.

**Comment by Norric1Admin** [comment]
@brockfanning I've resolved the conflict - can this be approved?

**Comment by brockfanning** [comment]
@Norric1Admin Can you remove the addition of a second "Can data in a platform be accessed via API?" section? I think this was the conflict, and as this PR is now, it will result in 2 of those sections.

**Comment by Norric1Admin** [comment]
@brockfanning Thanks for noticing - rookie error! OK to be merged?

**Pull request merged**
