### PR TITLE
Create template for PRs

### PR DESCRIPTION
**Pull request by LucyGwilliamAdmin**
Currently looks like this (updated following feedback):
Q | A
--- | ---
Feature branch/test site URL | [Link](add link here)
Fixed issues | #`issue`
Related version | 1.3.0-dev
Bugfix, feature or docs |
Keeps backward-compatibility? |❌/✔️
Updated docs/config-forms? |❌/✔️
Added CHANGELOG entry? |❌/✔️

So filled in for this PR as an example (updated following feedback):
Q | A
--- | ---
Feature branch/test site URL | NA
Fixed issues | #1077
Related version | master
Bugfix, feature or docs | Feature
Keeps backward-compatibility? |NA
Updated docs/config-forms? |NA
Added CHANGELOG entry? |NA

Most of these fields came from this [example on json-editor repo](https://github.com/json-editor/json-editor/pull/882) but I've added some others.

Let me know if you think there's any we should remove or if there are others we should add?

### CODE REVIEW

**Comment by brockfanning** [comment]
@LucyGwilliamAdmin Cool. This is just my preference, but when I see those symbols I think of ❌ as "bad" and ✔️ as "good". So I'm wondering if the questions can be worded in a way so that we eventually want all ✔️. Some notes on each one:

Q | A | Notes
--- | --- | ---
Fixed issues | #1077 | If this works with github's auto-linking feature, great. I'll test that out next time I open a PR.
Related version | NA | Most PRs will be for the upcoming version (1.3.0-dev right now) so maybe we can provide that default here.
Is bugfix? | ❌| Maybe this question could be "Bugfix, feature, or docs?" with plain text answers?
New feature? | ✔️ | See above
Breaks backward-compatibility? | ❌| I'd reverse this, like "Keeps backward-compatibility" so the ✔️is "good".
Tests pass? | ✔️ | I don't think we need this because it shows up automatically.
Feature branch/test site URL | NA | Sounds good
Reviewed | ❌| I don't think we need this because it shows up automatically.
Updated README/docs? | ❌| Maybe this could also include configuration form updates. Like: "Updated docs/config-forms?"
Added CHANGELOG entry? | ❌| Sounds good

**Comment by LucyGwilliamAdmin** [comment]
@brockfanning I agree with those changes. I'll see if there's any other thoughts before I make the changes though

**Comment by AnnCorp** [comment]
@LucyGwilliamAdmin this is a great idea. Agree with Brock's comments. 
Only one further thought: might be helpful to have the link to feature branch/test url nearer the top so quicker to access (I know those links will break eventually once feature branches will be removed, but while dev in progress think easier if the link at top).

**Comment by LucyGwilliamAdmin** [comment]
@brockfanning @AnnCorp this has just been updated following your feedback - see top comment for how it looks now

**Comment by brockfanning** [comment]
@LucyGwilliamAdmin My only suggestion is to add a "?" after "Bugfix, feature, or docs". Looks great!

**Comment by LucyGwilliamAdmin** [comment]
@brockfanning oh yeah - missed that, just added

**Review by brockfanning — APPROVED** [review]

**Comment by LucyGwilliamAdmin** [comment]
@brockfanning I should have merged into 1.3.0-dev since that is now the default branch - should I revert this PR and merge into 1.3.0 instead?

**Comment by brockfanning** [comment]
@LucyGwilliamAdmin No I think we have some stuff in master that needs to go into 1.3.0-dev anyway. I'd suggest creating a new PR to merge master into 1.3.0-dev.

**Pull request merged**
