### PR TITLE
Extra margin under news listings

### LINKED ISSUE #1160: Increase white space between update items
This white space between each listing on the updates page requires increasing slightly. The spacing should be the same as that used on the publications page (sorry I do not know what the px used on the publications page is). 

Screenshot (190)_LI

### PR DESCRIPTION
**Pull request by brockfanning**
Q | A
--- | ---
Feature branch/test site URL | [Link](https://lucygwilliamadmin.github.io/sdg-indicators/updates/)
Fixed issues | Fixes #1160 
Related version | 1.4.0-dev
Bugfix, feature or docs? | Feature
Keeps backward-compatibility? |NA
Includes tests? |NA
Updated docs? |NA
Updated config forms? |NA
Added CHANGELOG entry? |❌

### CODE REVIEW

**Comment by LucyGwilliamAdmin** [comment]
@brockfanning @phillipgardiner I've just added link to sandpit for this

**Comment by phillipgardiner** [comment]
@LucyGwilliamAdmin Sorry for me that is too big a gap. I can't seem to find the answer but ideally the same spacing as that used on the publications page would be used - as effectively they follow the same content layout.

**Comment by LucyGwilliamAdmin** [comment]
@phillipgardiner 40px is what's on that sandpit

This is 30px:
image

This is 25px:
image

The live site is 20px

**Comment by phillipgardiner** [comment]
@LucyGwilliamAdmin 25px then please.

**Comment by brockfanning** [comment]
Ok, just updated the PR.

**Comment by LucyGwilliamAdmin** [comment]
Thanks @brockfanning, I've just updated the link @phillipgardiner

**Review by LucyGwilliamAdmin — APPROVED** [review]

**Pull request merged**
