### PR TITLE
Simplify goals layout and allow configurable intro

### PR DESCRIPTION
**Pull request by brockfanning**
This will fail testing at the moment, but demonstrates a quick example of simplifying the goals layout and configuring its intro.

### CODE REVIEW

**Comment by brockfanning** [comment]
@AnnCorp @phillipgardiner I've added that space beneath the goals page description.

**Comment by phillipgardiner** [comment]
@brockfanning is there a feature branch somewhere which I can view it on?

**Comment by brockfanning** [comment]
@phillipgardiner I can't push to those feature branches, but here is a screenshot:

Screenshot from 2020-07-30 07-00-47

**Comment by AnnCorp** [comment]
@brockfanning looks good to me too.

**Comment by LucyGwilliamAdmin** [comment]
Feature branch here:
http://sdgdev-813006012.eu-west-1.elb.amazonaws.com/1-1-0-upgrade/goals/

**Pull request merged**
