### PR TITLE
2.1.0 release docs

### PR DESCRIPTION
**Pull request by brockfanning**

### CODE REVIEW

**Comment by otis-bath** [comment]
Hi @brockfanning is there any guidance on overrides for 2.1.0 to come?

**Comment by brockfanning** [comment]
@otis-bath Ah, I forgot that part. Yes I'll add that.

I also need to fill in any "recommended configuration changes". I was thinking of adding a note that if "hide_empty_metadata" is false then "empty_metadata_placeholder" is recommended. I'll look for others too.

**Comment by brockfanning** [comment]
@otis-bath @LucyGwilliamAdmin @sarah-beasley This is ready for review. This is only documentation, so it does not need a feature branch - just a review of the language. The easiest way would be to read the files in my branch:

* Updates: https://github.com/brockfanning/open-sdg/blob/2.1.0-release-docs/docs/updates.md
* Upgrade instructions: https://github.com/brockfanning/open-sdg/blob/2.1.0-release-docs/docs/upgrades/upgrading-2-1-0.md
* Changelog: https://github.com/brockfanning/open-sdg/blob/2.1.0-release-docs/docs/changelog.md

In particular let me know what you think of the items in the upgrade instructions, and if I've forgotten any new features that should go in there. (For example I didn't mention the new goal header feature, but that could be added if you think it would make sense to do that.)

**Comment by brockfanning** [comment]
I've added a section about the goal_content_heading feature.

**Pull request merged**
