### PR TITLE
Handle searches with no input

### LINKED ISSUE #1192: Search results page shows results when no search term is entered
**Please complete the following information** 
**Describe the bug**
A clear and concise description of what the bug is:
Even when no search term is entered before clicking the search button, search results show (314 so it could possibly be that it's just returning every single page as a result).

There are some accessibility issues with this but in the first instance we need to decide if we want any results to show at all

**To Reproduce**
1. Go to 'https://sdgdata.gov.uk/'
2. Click on the search button - don't enter a search term
3. Scroll down to under search bar

**Expected behavior**
A clear and concise description of what you expected to happen:
Either:

- no results show (with message)
- accessibility issues are resolved

**Screenshots**
image

**Accessibility issues**

1. If a user clicks the ‘search’ button without entering any search text, the main page content appears to be hidden from assistive technology. None of the content is relayed with screen reading software, and none of the links are recognised with voice activation software. Instead, the ‘loading search results graphic’ is identified with screen reading software, despite appearing to be hidden. 
  Solution: Ensure that information and functionality is presented to assistive technology. 
2. A search result for Pages >> /indicators.json is returned but it does not have a link or any description - this should be removed.

### PR DESCRIPTION
**Pull request by brockfanning**
Q | A
--- | ---
Feature branch/test site URL | [Link](https://lucygwilliamadmin.github.io/sdg-indicators/search/?q=)
Fixed issues | Fixes #1192
Related version | 1.4.0-dev
Bugfix, feature or docs? |
Keeps backward-compatibility? |✔️
Includes tests? |✔️
Updated docs? |NA
Updated config forms? |NA
Added CHANGELOG entry? |❌

This depends on the latest translations.

### CODE REVIEW

**Comment by LucyGwilliamAdmin** [comment]
@brockfanning @phillipgardiner I've just added a link - one thing I noticed is that the issue mentions adding 'Try adjusting your search to find what your looking for' but I don't know how that would fit with the 'Did you mean ...' functionality

**Comment by brockfanning** [comment]
@LucyGwilliamAdmin Is that branch point to the latest sdg-translations? If so I must have done something wrong, because the message is not appearing.

**Comment by LucyGwilliamAdmin** [comment]
It's pointing at 1.4.0-dev but will rebuild the data repo now to double check

**Comment by LucyGwilliamAdmin** [comment]
@brockfanning @phillipgardiner working now

**Comment by phillipgardiner** [comment]
@brockfanning @LucyGwilliamAdmin Tried to check this one but I get the old experience.

**Comment by LucyGwilliamAdmin** [comment]
@phillipgardiner see link now

**Comment by phillipgardiner** [comment]
@LucyGwilliamAdmin @brockfanning Thanks. Looking good. Could we please increase the white space between the 'No results' and 'Try adjusting your search to find what your looking for' sentences please?

**Comment by LucyGwilliamAdmin** [comment]
Adding screenshot so I can point at other branches for a while:

image

**Comment by brockfanning** [comment]
@LucyGwilliamAdmin I just added an extra line between before that message, so it's ready for another look.

**Comment by LucyGwilliamAdmin** [comment]
Rebuilt - @phillipgardiner this is ready for you to review again

**Comment by phillipgardiner** [comment]
@brockfanning @LucyGwilliamAdmin Looks good to me - thank you

**Review by LucyGwilliamAdmin — APPROVED** [review]

**Pull request merged**
