### PR TITLE
Empty include file for custom disclaimer content

### LINKED ISSUE #1546: Add configurable button to disclaimer in header
### Discussed in https://github.com/open-sdg/open-sdg/discussions/1541

<div type='discussions-op-text'>

<sup>Originally posted by **LucyGwilliamAdmin** January 17, 2022</sup>
UK has implemented button in the dev disclaimer.

Do we want to add to Open SDG?
image
</div>

Need to consider if can be used without dev-disclaimer and what to call it (could possibly call it header call to action)

Configuration options - text and link.
Style will be set but could be customised

### PR DESCRIPTION
**Pull request by brockfanning**
Q | A
--- | ---
Feature branch/test site URL | [Link](http://uk-sdg-feature-branches.s3-website.eu-west-2.amazonaws.com/feature-site-dev-disclaimer-off)
Fixed issues | Fixes #1546 
Related version | 1.8.0-dev
Bugfix, feature or docs? |
* [ ] Keeps backward-compatibility
* [ ] Includes tests
* [ ] Updated docs
* [ ] Updated config forms
* [ ] Added CHANGELOG entry

### CODE REVIEW

**Comment by brockfanning** [comment]
@otis-bath This PR adds an include file for the purpose of adding custom content to the disclaimer. And this also adds a site configuration setting (`hide_disclaimer`) for hiding the disclaimer.

We talked about the possibility of the custom content being separate from the disclaimer, but I found that this was impossible to do, and so I had to keep them together. So, if the `hide_disclaimer` setting is used, the custom stuff will be hidden also.

In one FB, to test hiding the disclaimer, you can set this site config:

```
hide_disclaimer: true
```

In a second FB, to test the custom content in the disclaimer, you can do the following:

1. Create a file in the site repo at: `_includes/components/dev-disclaimer-custom.html`
2. Give the file the following content:

        {% unless page.hide_my_button %}<a id="takepartButton" aria-labelledby="takepartButton" href="{{ site.baseurl }}/take-part" class="btn btn-primary btn-download btn-takepart" role="link">Take part in user research</a>{% endunless %}

3. Delete your override of `_includes/components/dev-disclaimer.html`.

If all goes well, you should still see the "Take part in user research" button the same as before.

**Comment by otis-bath** [comment]
Hi @brockfanning - have just taken a look at this, are other configurations required other than just pointing to your FB and the hide_disclaimer: true / instructions for the custom disclaimer. The changes are not affecting the frontpage? 
http://uk-sdg-feature-branches.s3-website.eu-west-2.amazonaws.com/feature-site-dev-disclaimer-off
http://uk-sdg-feature-branches.s3-website.eu-west-2.amazonaws.com/feature-site-dev-disclaimer-custom

**Comment by brockfanning** [comment]
@otis-bath Sorry I guess the UK override of _includes/components/dev-disclaimer.html needs to be deleted in both feature branches. The `hide_disclaimer` setting won't work while that override is there.

**Comment by otis-bath** [comment]
@brockfanning - great thanks, this has removed the disclaimer from this FB. On the custom FB are we expecting the disclaimer to look exactly the same as before when hide_disclaimer is set to false? When it is true it removes the beta disclaimer and feedback.  http://uk-sdg-feature-branches.s3-website.eu-west-2.amazonaws.com/feature-site-dev-disclaimer-custom/ As you can see has reinstated the feedback button but also the beta text?

**Comment by brockfanning** [comment]
@otis-bath The way I would expect it to work is:
* FB with custom include file and override removed: Looks and behaves exactly the same as on live site
* FB with `hide_disclaimer` and override removed: The entire section is removed (beta, message, button, etc)

**Review by otis-bath — APPROVED** [review]
Looks good and working as planned -OB

**Review by phillipgardiner — APPROVED** [review]
@otis-bath looks good to me :)

**Comment by brockfanning** [comment]
@otis-bath Sorry about this - I just realized that we already have a config section dedicated to the disclaimer. I've just pushed up a change. For the FB where it is hidden, do you mind changing it from:

```
hide_disclaimer: true
```

To instead adding `hidden: true` to the `disclaimer` section. For example:

```
disclaimer:
  phase: BETA
  message: This website is in development – your <a href="https://www.surveymonkey.co.uk/r/SDGfeedback">feedback</a> will help us to improve it
  hidden: true
```

**Comment by otis-bath** [comment]
@brockfanning have made this change and everything still functioning properly as before

**Pull request merged**
