### PR TITLE
Alt tag for loading image

### LINKED ISSUE #738: The loading animation on Indicator page doesn't have an alt tag
**Please complete the following information** 
Site repository URL:  github.com/open-sdg/open-sdg
Open SDG version: 1.0.0

**Describe the bug**

Running an accessibility test with Pa11y returns this error against indicator pages with sections on top of the charts ([example](http://sdgdev-813006012.eu-west-1.elb.amazonaws.com/opensdg1/3-4-2/)). 

**To Reproduce**

1. Grab the URL of an indicator with a "catch-all" section on top
2. Run a Pa11y accessibility test
3. Pa11y will alert that the loading animation doesn't have an `alt` tag (see screenshot)

**Expected behavior**

All images should have an alt tag for accessibility.

**Screenshots**

image

**Desktop (please complete the following information):**

Tested on desktop configuration, including high contrast

**Smartphone (please complete the following information):**

Also tested on mobile configuration of 320x480

### PR DESCRIPTION
**Pull request by brockfanning**
Fixes #738

### CODE REVIEW

**Comment by brockfanning** [comment]
Actually we may as well do this right and translate the word "Loading". Please hold off on reviewing until SDG Translations has this translated.

**Comment by brockfanning** [comment]
Ok, this is ready for review now that 'Loading' is translated.

**Comment by brockfanning** [comment]
@LucyGwilliamAdmin I wonder if there's some reason it would not be getting the latest sdg-translations. I merged a translation of "Loading" a few days ago.

One way to test is to open the developer console while on that indicator page, and type "translations.indicator". It should display a long list of translations, one of which needs to be "loading". If that's missing, it might explain why the test is still failing.

**Comment by LucyGwilliamAdmin** [comment]
I've updates the data config file, but I'm not sure where in developers console I should be searching - is it elements?

**Comment by brockfanning** [comment]
Here's what it looks like in my Firefox:

Screenshot from 2020-07-06 09-06-53

It does look like the translation is there now, so I'm wondering if maybe the pa11y test will pass now.

**Comment by brockfanning** [comment]
Cool!

**Pull request merged**
