### PR TITLE
Configuration form accessibility fixes

### PR DESCRIPTION
**Pull request by brockfanning**
This attempts to address the items in #1000. Changes include:

* Remove all "table formatting" (ie, fields in rows) and instead display all fields vertically
* Remove the Markdown editor and show plain text areas instead
* Labels for integer fields (eg "Goal color number")
* Adds a message to links about opening in a new tab (screenreaders only)
* Use a button for the search filter
* Adds screenreader status announcement of search filter results

This also fixes IE support in general, which had been broken by recent changes.

A couple of items from #1000 are not fixed here:
* Item 4 - related to color fields: Since we're only using the standard HTML5 input for color, I would want to get confirmation that we actually need to remove those.
* Items 2 and 9 (I think these are the same right?): This is going to be a more difficult fix, and I thought I would submit this PR with the easier items.

### CODE REVIEW

**Comment by brockfanning** [comment]
@LucyGwilliamAdmin @jwestw This PR includes some accessibility fixes for the config forms, but it also includes a general platform-wide fix for IE support. **That IE issue definitely should be fixed before we launch 1.2.0.** Let me know if I should split it out into a separate PR.

**Comment by brockfanning** [comment]
@jwestw @LucyGwilliamAdmin I have pushed some code that changes the H3 elements to divs. I think this should help with items 2 and 9 from the DAC feedback. This is now ready to be reviewed and/or sent back to DAC (with the only unaddressed item being #4 about the colors).

**Comment by LucyGwilliamAdmin** [comment]
@brockfanning Thanks for letting me know - I will send back to DAC today

**Comment by LucyGwilliamAdmin** [comment]
@brockfanning before I send - is Create pages table what is expected now?
http://sdgdev-813006012.eu-west-1.elb.amazonaws.com/config-form-accessibility-fixes/config/

**Comment by brockfanning** [comment]
@LucyGwilliamAdmin Hmm, no it's not. Can you try pointing to the master branch of jekyll-open-sdg-plugins?

**Comment by LucyGwilliamAdmin** [comment]
@brockfanning done and rebuilt - I think that's more what I was expecting - what about you?

**Comment by brockfanning** [comment]
@LucyGwilliamAdmin Sorry, still some issues. Please hold off, I'll investigate more.

**Comment by brockfanning** [comment]
@LucyGwilliamAdmin I've added a bit of backwards compatibility for the create_pages setting. I think this should be ready again for review.

**Comment by LucyGwilliamAdmin** [comment]
I have just rebuilt: http://sdgdev-813006012.eu-west-1.elb.amazonaws.com/config-form-accessibility-fixes/config/

**Comment by brockfanning** [comment]
@LucyGwilliamAdmin There's still an issue with the date formats setting. I'll work on that. It might be OK to send to DAC anyway if you want to avoid delays (and if you're tired of making feature branches :).

**Comment by LucyGwilliamAdmin** [comment]
@brockfanning I drafted the email ready to send earlier but I ended up sending by accident so I've already got some feedback from them...

These comments are from having a brief look at page - I think once the additional feedback has been looked at/resolved, we will go back for a fuller review. However I will book in that time now as they like to know in advance - do you have any thoughts on when maybe it should be?

re. 4 from DAC: 

> No I wouldn’t remove them, but without a proper look I am not sure why they weren’t working with screen reading software to offer a fuller suggestion.  I tested the standard components on a different site and they did seem to work with JAWS so I would imagine that there must be something within the mark-up causing this issue. Apologies that was all the digging I was able to do within that space of time. If you would like me to book some time in to take a more thorough look, please let me know. If these don’t work with screen reading software and there is no alternative, then this could be a high level fail. I think I would probably advise including an additional alternative way for users to enter the hexadecimal colour code manually via a text input component with a clear label and instructions. This would mean that users could quickly enter the code without using this component if they knew it offhand. 

Other feedback from DAC:
> You have multiple links with the same link text ‘more information’ but different purposes. I would advise you to keep the link text fully descriptive, for example, ‘More information on Goals page (opens in a new tab)’. At the moment the text ‘(opens in a new tab)’ is visually hidden and only presented to screen reader users, but this is actually something that a wide range of users bring up as an issue so I would suggest this information be presented visually on the page to all users. I would consider this a AAA non-conformance.

> It appears that headings are not marked-up on this page either now. This would be a A fail (information and relationships). 

> One issue I would also identify which is more of a usability issue is that instructional text is included under the fields to which they correspond, and they are not referenced with an ‘aria-describedby’ as recommended by the GOV.UK Design System. 

> One thing that I would probably also want to look further at would be how required fields are indicated for form groups within tables, such as ‘Main menu’, as the text ‘required’ is not programmatically associated with the fields, users may not be able to identify which fields are required. I believe the GOV.UK Design System recommends indicating instead when fields are optional, and this being a part of the labels or legend for form groups.

**Comment by brockfanning** [comment]
That was fast!

Regarding the color fields, I really don't want to complicate things with duplicating them. I would vote that we either leave it as is, or turn them all into plain text fields. Do you agree and/or have a preference? Personally I'm fine either way. I'd be a bit surprised if screenreaders don't support this HTML5 field, but stranger things have happened, and these color widgets are not critical to the overall feature.

Regarding this feedback -- "You have multiple links with the same link text ‘more information’ but different purposes." -- I thought I had already added specifics on each link. I may well have missed some though. A specific example would be helpful.

Regarding this feedback -- "I would suggest this information be presented visually on the page to all users" -- this should now be fixed.

Regarding this feedback -- "It appears that headings are not marked-up on this page either now." -- I will need to understand this better. Is the problem that the labels of the fields are large font and appear to be headings - and thus they need to actually be headings? Is there any way to satisfy this without making them headings? They were H3's before but I changed them to DIV to solve the hierarchy problem. Because of the recursive nature of this javascript library ("json-editor"), whatever element we choose will be repeated in a nested way.

Regarding this feedback -- "they are not referenced with an ‘aria-describedby’" -- In some cases they actually are. But I am not surprised if some are not. If it's easy to provide, a specific example would help me fix this.

The issues with "required" is certainly a complex issue, because of the way this javascript library works. The comment above about required fields seems a bit too vague for me to get started. I would prefer to have a clear description of the AA requirements there.

Stepping back a bit for an overall comment though: I'm not clear how much we need to fix before 1.2.0. I believe that every time we send this page to DAC, they are going to find more problems...

**Comment by LucyGwilliamAdmin** [comment]
@brockfanning 

I was thinking same for colour fields - doesn't make sense to duplicate - I do prefer it as it is now as users can preview and choose colour in one place. We are going to ask them to spend some more time on the forms so they might be able to suggest how to fix.

From what I can see all "more information..." have been updated

However there does seem to be a space missing between "more information..." and "(opens in a new tab)" 

I will clarify about hierarchies and headings

Just checked out the aria-described by issue. It looks like some of the nested item input fields are missing it:

- Create pages items
- Date formats items
- Footer menu items
- Frontpage cards items
- Map layers items
- Map options: weight, opacity and fill opacity
- Main menu items

**Comment by brockfanning** [comment]
@LucyGwilliamAdmin My latest commits here should fix the aria-describedby issues you listed, and also the missing space.

**Comment by LucyGwilliamAdmin** [comment]
@brockfanning great 👍 

Here's some more info about the headings/hierarchies from DAC:

A good resource on sematic mark-up is this one WebAIM: Semantic Structure: Regions, Headings, and Lists. Screen reader users rely on semantic mark-up to present the relationships and purpose of the information on the page. For example, heading mark-up allows screen reader users to identify the purpose of text as a heading, it also contextualises the section of content and is also a useful navigational tool as users are able to filter the page by headings and then navigate straight to the section they require. Heading levels shouldn’t be used for visual styling – they should represent hierarchical and structural relationships on the page.

In terms of this page: http://sdgdev-813006012.eu-west-1.elb.amazonaws.com/release-prep-and-config-forms/config/
image

It doesn’t make sense to jump from a `<h1>` to a `<h3>` because a `<h3>` is semantically a second level subheading and should belong under a `<h2>`. All the current `<h3>` introducing a section with a grey border should therefore be `<h2>` as they belong directly ‘under’ the main page `<h1>` heading.   

However, the headings which sit underneath these sections, should be a `<h3>` as this demonstrates that these belong to the greater section. For example:

image

**Comment by brockfanning** [comment]
@LucyGwilliamAdmin My response regarding the headers: I understand that an H1->H2->H3-etc hierarchy is ideal for headings. However my question is, what if the page does not use headings at all? Does that make it an accessibility failure? If so, AAA, AA, or A?

**Comment by brockfanning** [comment]
@LucyGwilliamAdmin Actually if you haven't already sent that to DAC, I've got a lead on a possible way to get the hierarchical headings working. I'm looking into that again.

**Comment by brockfanning** [comment]
@LucyGwilliamAdmin An update - we can definitely get hierarchical headings... eventually. However it depends on a change to a third-party library ([here is my PR in that project](https://github.com/json-editor/json-editor/pull/882)). If it is urgent, we can always fork that project and get the feature immediately. Otherwise we could wait and see if the feature gets accepted. So the options are:
1. Merge this PR as-is, and there will be no headings. When/if the json-editor project accepts my other PR, update this code to get hierarchical headings.
2. Fork the json-editor project and add that feature to our fork, then update this code to use our fork and get hierarchical headings.

I lean towards the first option for now, if that is OK with you, because it would be good to avoid forking another project if we can avoid it.

**Comment by LucyGwilliamAdmin** [comment]
@brockfanning I agree - I think let's do first option for now and I think we can get this in to 1.2 as is for now (subject to testing by us, not DAC - think we can leave going back to DAC on this one for now)

**Comment by LucyGwilliamAdmin** [comment]
@brockfanning I was just about to approve but have just checked and your PR in json-editor has been approved.

Do you want to get this into 1.2-beta as is or update the code to get hierarchal headings?

**Comment by brockfanning** [comment]
@LucyGwilliamAdmin Well, the PR has been approved by 1 reviewer, but they require 2 reviews, and then it will need to be merged and included in a release. So it still may be some time before it's ready to use.

**Comment by LucyGwilliamAdmin** [comment]
Ah - I see, will approve now

**Review by LucyGwilliamAdmin — APPROVED** [review]

**Pull request merged**
