### PR TITLE
Release notes for 0.5.0

### PR DESCRIPTION
**Pull request by brockfanning**
We can add to this if we're sneaking anything else into the release. Anything I've missed?

### CODE REVIEW

**Comment by brockfanning** [comment]
@SavvasStephanides @dougmet What else should we add to these notes? Feel free to review whenever you think we are at a stopping place for this release.

**Comment by Norric1Admin** [comment]
Hello Brock, the main consideration for us is to include the ‘N/A’ reporting status option for the NISR site. This issue is currently in progress on the UK site: https://github.com/ONSdigital/sdg-indicators/issues/2851

**Comment by brockfanning** [comment]
@Norric1Admin It depends on the changes and how quickly they can be reviewed and merged. So it's hard to say until they are up here as a PR.

I believe we wanted to get 0.5.0 released sooner rather than later, because 2 new countries are about to adopt the platform, and we thought it would be good for them to start with 0.5.0.

In terms of the PRs that are here already, I think this update to the changelogs is ready for review.

**Comment by Norric1Admin** [comment]
Survey header is expected to be tested this Wednesday, then we can send a PR soon after.

Doug says he has merged https://github.com/open-sdg/sdg-translations/pull/72 now so let me investigate and we might have this ready to test today.

Thanks for your patience!

**Pull request merged**
