### PR TITLE
Codeql test

### PR DESCRIPTION
**Pull request by LucyGwilliamAdmin**
Just want to see the output of the codeql workflow

### CODE REVIEW

**Comment by LucyGwilliamAdmin** [comment]
@brockfanning I can now see that *-dev branches are protected - does this mean they behave differently to other branches?

**Comment by brockfanning** [comment]
@LucyGwilliamAdmin Ah right, that was from when we were getting ready to release version 1.0.0 and needed a way to isolate it from ongoing development. We may want to use that approach again for 1.2.0. I need to wrap my head around it a bit.

**Comment by LucyGwilliamAdmin** [comment]
Is it an issue for this to be merged into the -dev branch I created?

**Comment by brockfanning** [comment]
@LucyGwilliamAdmin No issue that I know of.

**Comment by LucyGwilliamAdmin** [comment]
@brockfanning can you approve then please?

**Review by brockfanning — APPROVED** [review]

**Pull request merged**
