### PR TITLE
Hide single units of measurement

### LINKED ISSUE #1204: Single unit of measurement
**Finding**: 'Unit of measurement' is displayed as an option in the dis-aggregation filters filters even if there is only one measure available (for example see: https://sdgdata.gov.uk/15-4-2/)

**Recommendation:**
If there is only one 'Unit of measurement', do not display it in the disaggregation controls. The unit of measurement is able to be interpreted by the users from the graph axis, footnote and graph title.

### PR DESCRIPTION
**Pull request by brockfanning**
Q | A
--- | ---
Feature branch/test site URL | [Link (show both)](http://uk-sdg-feature-branches.s3-website.eu-west-2.amazonaws.com/feature-site-hide-single-unit/17-3-2/)<br>[Link (hide just units)](http://uk-sdg-feature-branches.s3-website.eu-west-2.amazonaws.com/feature-site-hide-single-unit-hide-units/17-3-2/)<br>[Link (hide just series)](http://uk-sdg-feature-branches.s3-website.eu-west-2.amazonaws.com/feature-site-hide-single-unit-hide-series/17-3-2/)<br>[Link (hide both)](http://uk-sdg-feature-branches.s3-website.eu-west-2.amazonaws.com/feature-site-hide-single-unit-hide-both/17-3-2/)
Fixed issues | Fixes #1204
Related version | 1.5.0-dev
Bugfix, feature or docs? |
* [x] Keeps backward-compatibility
* [ ] Includes tests
* [x] Updated docs
* [x] Updated config forms
* [ ] Added CHANGELOG entry

### CODE REVIEW

**Comment by LucyGwilliamAdmin** [comment]
@brockfanning it isn't documented but I think we discussed doing same to series - can you remember?

If so, would it take long to add that?

**Comment by LucyGwilliamAdmin** [comment]
Make unit measure displaying optional and also for series

**Comment by brockfanning** [comment]
@LucyGwilliamAdmin I've done a quick update of this that hopefully works for series as well.

**Review by LucyGwilliamAdmin — APPROVED** [review]
Tested all scenarios and looks good!

**Pull request merged**
