### PR TITLE
Redesign indicator page tabs

### PR DESCRIPTION
**Pull request by SavvasStephanides**
[UK feature branch](http://sdgdev-813006012.eu-west-1.elb.amazonaws.com/opensdg1-tabs/1-2-1/)

### CODE REVIEW

**Comment by brockfanning** [comment]
Looks like another unrelated test failure. I'll look into adding a "And I wait 2 seconds" before that line. In the meantime I've re-run the tests to see if that works.

**Comment by SavvasStephanides** [comment]
@brockfanning Thanks Brock. Removed the spacers here as well

**Comment by brockfanning** [comment]
@SavvasStephanides That helps - though I also think that the CSS should be in the Sass code, instead of as inline styles.

Speaking visually, a couple of comments:
1. I feel like the borders need to be darker. Just my opinion, but they're a bit hard to see. I like the understated look though... I guess, to keep it objective, maybe do whatever the accessibility guidelines require? According to [this](https://webaim.org/resources/contrastchecker/) it needs to be #888 before it starts passing.
2. When hovering over the active tab, the bottom border appears again, which is a bit confusing to me. What do you think? Should the bottom border stay hidden for the active tab?

**Comment by SavvasStephanides** [comment]
@brockfanning 

> 1. I feel like the borders need to be darker. Just my opinion, but they're a bit hard to see. I like the understated look though... I guess, to keep it objective, maybe do whatever the accessibility guidelines require? According to [this](https://webaim.org/resources/contrastchecker/) it needs to be #888 before it starts passing.

I agree. I'll change the borders to a darker colour

> 2. When hovering over the active tab, the bottom border appears again, which is a bit confusing to me. What do you think? Should the bottom border stay hidden for the active tab?

I haven't realised that until you mentioned it. I think it should disappear. I'll get to it

**Comment by SavvasStephanides** [comment]
Done all the changes, ready for re-review. [Updated feature branch](http://sdgdev-813006012.eu-west-1.elb.amazonaws.com/opensdg1-tabs/3-1-2/)

**Comment by SavvasStephanides** [comment]
From Phill's comments:

* Centre the tab labels
*  Change inactive tab styling

Please hold off the review for now.

**Comment by SavvasStephanides** [comment]
Done. Ready for review

**Comment by brockfanning** [comment]
@SavvasStephanides It's looking good to me. I have a couple of nitpicks:
1. The top border of the content area isn't the same as the other sides. I think I see the issue, which is the need to hide the border under the active tab. Maybe try showing the same border on all sides, but give the tabs a "top: 1px" so that they sit in front of the top border?
2. The focus outline of the active tab has a bottom border that kind of ruins the visual effect. Could the bottom border of the active tab's focus be hidden without messing up accessibility? If not, it's OK.

**Comment by SavvasStephanides** [comment]
Thanks @brockfanning !

> 1. The top border of the content area isn't the same as the other sides. I think I see the issue, which is the need to hide the border under the active tab. Maybe try showing the same border on all sides, but give the tabs a "top: 1px" so that they sit in front of the top border?

I've changed it to a darker grey to match the rest.

> 2. The focus outline of the active tab has a bottom border that kind of ruins the visual effect. Could the bottom border of the active tab's focus be hidden without messing up accessibility? If not, it's OK.

Good eye! It seems to have disappeared though after the latest changes. Hopefully it is gone on your tests also.

I've updated the feature branch as well.

Screenshot of indicator page with redesigned tabs

**Comment by brockfanning** [comment]
@SavvasStephanides The top border change looks great to me. I'm still seeing the bottom border on the focus outline. In case we're talking about different things, here's a screenshot - see the dashed bottom border under "Chart":
Screenshot from 2020-02-06 10-24-11

I know focus outlines are important for accessibility, it's just unfortunate that it messes up the visual effect of the tab, and wondered if maybe it could be removed.

**Comment by SavvasStephanides** [comment]
@brockfanning That seems like a browser thing

**Comment by brockfanning** [comment]
@SavvasStephanides Yep - I took that screenshot in Firefox.

**Comment by brockfanning** [comment]
@SavvasStephanides Other than the annoyance in Firefox, I'm happy with it. I can go ahead and approve, but @LucyGwilliamAdmin did you want to give feedback?

**Comment by phillipgardiner** [comment]
Excellent, that's looking so much better - great :). Tiny bit of feedback (sorry!) could we consider underlining the text when you hover over the unselected tabs? Usually links are underlined, bit it looks like on your site the standard is to underline links once hoovered over, so or consistency this should potentially be applied to the other tabs - happy to be corrected though.

**Comment by brockfanning** [comment]
I like the idea of underlined links in these tabs. :+1:

**Comment by brockfanning** [comment]
Tech note - I think it would need to be hovering over the <li> element that triggers the underlining of the <a> element.

**Comment by SavvasStephanides** [comment]
Thanks for the suggestion @phillipgardiner. I've updated it. I've also updated the [UK feature branch](http://sdgdev-813006012.eu-west-1.elb.amazonaws.com/opensdg1-tabs/3-1-2/) for you to check.

**Pull request merged**
