### PR TITLE
Alternate frontpage layout

### LINKED ISSUE #634: Add configurable home page
So doesn't just start with the goals page. See Phill's mockup.

### PR DESCRIPTION
**Pull request by brockfanning**
Fixes #634 

This adds a new layout call `frontpage-alt`. It also adds another layout called `goals` which is simply a duplicate of the current `frontpage` layout. For backwards compatibility we have to keep the `frontpage` layout in place, but we can eventually remove it when we get to 2.0.0.

In order to switch over to the alternate homepage with a separate goals page, it's necessary to explicitly control the automatic pages created in the `create_pages` setting. This would be the necessary settings in most cases:
```
create_pages:
  pages:
    - folder: /
      layout: frontpage-alt
    - folder: /goals
      layout: goals
    - folder: /reporting-status
      layout: reportingstatus
    - filename: indicators.json
      folder: /
      layout: indicator-json
    - folder: /search
      layout: search
```

The above replaces the `create_pages: true` which is probably already there.

Here are examples of the relevant configuration settings for _config.yml:

```
# This is the same as what is used on the current frontpage.
frontpage_introduction_banner:
  title: My frontpage introduction banner title
  description: My frontpage introduction banner description

# This controls the text that appears above the goals grid.
frontpage_goals_grid:
  title: The Sustainable Development Goals
  description: Click on each [goal](../goals) for data for Sustainable Development Goal global indicators.

# This controls the three-column "cards" that appear below the goals grid.
frontpage_cards:
  - title: Download all data
    # This "feature" is used for baked-in stuff like "bulk_download".
    include: components/download-all-data.html
    # Optionally control the color of the line above the card title.
    rule_color: green
  - title: Useful resources
    rule_color: blue
    # Control the content of the card - can use Markdown.
    content: |
      * [Useful resource](https://example.com)
      * [Useful resource](https://example.com)
      * [Useful resource](https://example.com)
      * [Useful resource](https://example.com)
      * [Useful resource](https://example.com)
  - title: Publications
    rule_color: orange
    content: |
      * [Publication](https://example.com)
      * [Publication](https://example.com)
      * [Publication](https://example.com)
    # Optionally add a button at the bottom of the card.
    button_label: View more publications
    button_link: https://example.com
```

### CODE REVIEW

**Comment by LucyGwilliamAdmin** [comment]
@brockfanning I've started having a look at this and playing around with the functionality on this feature branch:
http://sdgdev-813006012.eu-west-1.elb.amazonaws.com/alternate-frontpage/

I think it looks good - my main concern is that buttons can be unlimited in length - I'm wondering if it's worth adding a `max-width: 100%` attribute for the customisable buttons, along with something in docs about length in characters?

I'm also wondering if there's a way for any images that may be added in the sections to be given a `max-width: 100%` attribute so that by default, the width of the image is the width of the column, rather than the width of the page.

@phillipgardiner's also taken a look and has some comments on the spacing:
1. The spacing between the these grid line and their related title needs increasing slightly (padding currently 5, change to 7 should do it)
2. The spacing between the bullet points contained in each grid section needs increasing

**Comment by LucyGwilliamAdmin** [comment]
@brockfanning also one other thing from me.

The internal links seem to be working differently in this section - the goal link and the button in the publications section are only taking into account the first part of the url

**Comment by LucyGwilliamAdmin** [comment]
In this line
`description: Click on each [goal](../goals) for data for Sustainable Development Goal global indicators.`
I changed `../goals` to `./goals` and that fixed my link problem

**Comment by brockfanning** [comment]
@LucyGwilliamAdmin I've pushed up fixes for the long buttons and large images. I've also added better support of relative paths in the button links. Links in the config markdown is a bit more tricky, so I've just added some documentation about that.

@phillipgardiner I've upped the spacing above the card titles to 7px. Regarding the spacing in the bullet lists, I imagine that this is something you would recommend throughout the site. In that case I would suggest making a separate ticket like "Increase spacing in bullet lists".

**Comment by phillipgardiner** [comment]
@brockfanning @LucyGwilliamAdmin Hey Both, there is something that's been bugging me about this page. Despite what I've been saying about the bullet points spacing etc, I just checked my design and the bullets actually should not be there at all - just the links. Is there a reason they now exist or can they be removed?

**Comment by brockfanning** [comment]
@phillipgardiner The content of the sections is fully configurable - countries can fill it with Markdown or even HTML. So they can have bullet lists, numbered lists, paragraphs, or just a series of line breaks if they prefer. For example this is some config from Lucy's feature branch now:
```
    content: |
      * [Useful resource](https://example.com)
      * [Useful resource](https://example.com)
      * [Useful resource](https://example.com)
      * [Useful resource](https://example.com)
      * [Useful resource](https://example.com)
```

The asterisks are Markdown for bullet lists. To make that into a series of line breaks with no bullets, the country might change it to:

```
    content: |
      [Useful resource](https://example.com)<br>
      [Useful resource](https://example.com)<br>
      [Useful resource](https://example.com)<br>
      [Useful resource](https://example.com)<br>
      [Useful resource](https://example.com)
```

**Comment by phillipgardiner** [comment]
@brockfanning I see makes sense - thank you

**Comment by LucyGwilliamAdmin** [comment]
@brockfanning I've just approved as all looks and works fine - everything is configurable as it should be. 

We did discuss about adding something to docs about what colours can be used though

**Comment by phillipgardiner** [comment]
@brockfanning @LucyGwilliamAdmin sorry the only thing i have noticed is when you view it on mobile, the goals icons text is very hard to read, especially on high contrast mode. Can we do anything about this? Can we make them bigger?

**Comment by brockfanning** [comment]
@LucyGwilliamAdmin @phillipgardiner I've added more responsiveness to the goals grid. Roughly it should now behave like this:
* Desktop: 9 icons per row
* Tablet: 6 icons per row
* Phone: 4 icons per row

**Comment by LucyGwilliamAdmin** [comment]
Thanks @brockfanning 

@phillipgardiner I've just rebuilt the feature branch if you want to see how this looks:
http://sdgdev-813006012.eu-west-1.elb.amazonaws.com/alternate-frontpage-uk-example/

**Comment by phillipgardiner** [comment]
@brockfanning @LucyGwilliamAdmin Thanks both. What do you guys think. Is the 4 goals per row on mobile readable to you? Or should we consider going to 3 in a row (if possible). I think for me it depends on the background colour (for instance goal 7 is quite hard to read at this size, whereas goal 17 is clear).

**Comment by brockfanning** [comment]
I think it is a bit hard to read, though to be sure, the 9-per-row is just about as small at certain screen widths.

**Comment by brockfanning** [comment]
We'll change the mobile to 3 icons across.

**Comment by brockfanning** [comment]
@LucyGwilliamAdmin @phillipgardiner I've updated the mobile breakpoint to show 3 icons across. Did you want to take another look on a feature branch before I merge? Or should I go ahead and merge?

Also, I tweaked the documentation to make it more clear which frontpage-related configurations apply to which layouts. We've got several frontpage-related configurations now, some which are only for the `frontpage` layout, and some which are only for the new `frontpage-alt` layout, and one ("frontpage_introduction_banner") which applies to both.

**Comment by LucyGwilliamAdmin** [comment]
@brockfanning @phillipgardiner @AnnCorp here's the latest feature branch:
http://sdgdev-813006012.eu-west-1.elb.amazonaws.com/alternate-frontpage-uk-example/

**Comment by phillipgardiner** [comment]
@LucyGwilliamAdmin Sorry missed tech call. Will we have a final version to sign off on before the UK version is released?

**Comment by LucyGwilliamAdmin** [comment]
@phillipgardiner yes, we have the functionality to customise the page as needed 👍

**Comment by phillipgardiner** [comment]
@brockfanning @AnnCorp something I have just noticed (if I've interpreted it correctly) is that the grey colour used for the lines on the hompage etc (#CCC) would not pass the colour contrast test for [accessibility:.](https://webaim.org/resources/contrastchecker/) 
It looks like it would need to be #949494 as a minimum - thoughts? I'm assuming this is set on the OpenSDG side. I know countries can overwrite this but...

**Comment by brockfanning** [comment]
Is there any possibility those could be considered "decorative" and maybe exempted from the guidelines? I'm not sure offhand if that's even the way it works.

**Comment by LucyGwilliamAdmin** [comment]
@phillipgardiner @AnnCorp @brockfanning would they be considered incidental here:

https://www.w3.org/TR/UNDERSTANDING-WCAG20/visual-audio-contrast-contrast.html

**Comment by LucyGwilliamAdmin** [comment]
Also here for 2.1: https://www.w3.org/TR/WCAG21/#contrast-enhanced

**Comment by phillipgardiner** [comment]
@LucyGwilliamAdmin @brockfanning Good spot, Yes I would put them as Incidental
 👍 - No change required (few!)

**Pull request merged**
