### PR TITLE
Use darker text color and default to white text in high-contrast

### LINKED ISSUE #852: Make main text colour black
Low vision users struggled to read the font. Please consider implementing a heavier font with a greater contrast.

### PR DESCRIPTION
**Pull request by brockfanning**
Fixes #852

### CODE REVIEW

**Comment by brockfanning** [comment]
Use #0b0c0c

**Comment by brockfanning** [comment]
Default to white on high-contrast.

**Comment by brockfanning** [comment]
This is ready for review again.

**Review by jwestw — CHANGES_REQUESTED** [review]
I have tested this. In normal contrast mode it appears that the text is black (visual inspection) though when I inspect element, it doesn't show what colour it is. I see that #0b0c0c refers to a pure black though. 

In high contrast mode I see no greys any more, only black, yellow and white. However @brockfanning I have spotted a problem this has caused. In the high contrast mode if you try to search the search bar is white but so is the text, meaning it cannot be seen. Can we change that?

**Comment by brockfanning** [comment]
Thanks very much @jwestw. This is a good example of things that may result from the change of defaulting to white text in high-contrast mode. I've pushed a commit to deal with that one (search bars) but there may still be others.

**Comment by brockfanning** [comment]
@jwestw Is this on a feature branch? If so, maybe Phil could also help look for issues?

**Comment by LucyGwilliamAdmin** [comment]
@brockfanning @phillipgardiner James' feature branch: http://sdgdev-813006012.eu-west-1.elb.amazonaws.com/jw-black-text/

**Review by LucyGwilliamAdmin — APPROVED** [review]
I've also just looked through and can't see any other issues

**Comment by phillipgardiner** [comment]
@brockfanning @LucyGwilliamAdmin @jwestw 

The only additional thing I have spotted is the the alpha banner text is set to: #3D3D3D this would need changing to: #0b0c0c.

**Comment by brockfanning** [comment]
@phillipgardiner This PR has already been merged, but I made #883 to fix that issue.

**Comment by phillipgardiner** [comment]
@brockfanning OK, thanks

**Pull request merged**
