### PR TITLE
Map disaggregation: name the function and the flag differently

### LINKED ISSUE #1836: Map search function missing from multi layer maps
Just checked through the [beta1 feature branch](http://uk-sdg-feature-branches.s3-website.eu-west-2.amazonaws.com/feature-2.1.0-beta1/3-3-3/) and noticed that the map search function has disappeared from some of the maps. I've noticed it missing on 3-3-3 and 3-6-1. But it appears for me on 3-3-4. 

Lucy has also checked and noted that 3-3-4 only has one map layer while the other two have multiple. the below error also appears in the console.
80f71f00-2188-422e-bb29-cb8975b93a51

### PR DESCRIPTION
**Pull request by brockfanning**
Q | A
--- | ---
Feature branch/test site URL | [Link](http://uk-sdg-feature-branches.s3-website.eu-west-2.amazonaws.com/feature-site-map-disagg-function-fix)
Fixed issues | Fixes #1836 and #1838 
Related version | 2.1.0-dev
Bugfix, feature or docs? |
* [ ] Keeps backward-compatibility
* [ ] Includes tests
* [ ] Updated docs
* [ ] Updated config forms
* [ ] Added CHANGELOG entry

### CODE REVIEW

**Comment by brockfanning** [comment]
@otis-bath @sarah-beasley This is a quick guess at a fix for that map issue in #1836, based on the console error.

**Comment by sarah-beasley** [comment]
thanks Brock, I've just tested and the map search is appearing on the maps now. Not sure if this was discussed further while I was away last week, but are we still trying to get rid of the need for the button and just have the search box there permanently? At the moment, the hover label for 'search' when there is text typed in the box is redundant since it cannot actually perform a search.

image

**Comment by otis-bath** [comment]
@sarah-beasley is this on the beta tag branch or a separate FB?
@brockfanning have this on a FB [here](http://uk-sdg-feature-branches.s3-website.eu-west-2.amazonaws.com/feature-site-map-disagg-function-fix/) it works for the indicators identified previously with multiple layers like 3-3-3 and 3-6-1. That being said, it is not loading properly on [16-1-4](http://uk-sdg-feature-branches.s3-website.eu-west-2.amazonaws.com/feature-site-map-disagg-function-fix/16-1-4/) or [9-2-2](http://uk-sdg-feature-branches.s3-website.eu-west-2.amazonaws.com/feature-site-map-disagg-function-fix/9-2-2/) so wondering what is the root cause of this?

**Comment by LucyGwilliamAdmin** [comment]
@sarah-beasley we decided we would look at how the map search looks next release - sorry, should have said

**Comment by brockfanning** [comment]
@sarah-beasley @otis-bath This feature-branch can be refreshed - it should now fix both problems from #1836 and #1838.

**Review by otis-bath — APPROVED** [review]
Great thanks @brockfanning - this fixes the issues

**Pull request merged**
