### PR TITLE
Updates to the indicator progress on goal pages

### LINKED ISSUE #1747: 'Progress' updates to goal pages
A number of changes are required to the current progress MVP goals pages. Attached is mock up of how page should now be displayed. The changes are:

- Add title for progress statuses displayed 
- Add additional grey separator line
- Provide 5 reporting status levels (+2)

[Goals_page_update.pdf](https://github.com/open-sdg/open-sdg/files/9150070/Goals_page_update.pdf)

### PR DESCRIPTION
**Pull request by brockfanning**
This PR includes these changes:
1. When progress is used, the goals page includes a column header above the column of progress status. The text of this column header is configurable. This header does not display on mobile and will not be read by screenreaders.
2. The progress column on goal pages is twice as wide.
3. When progress is used, indicator and target names should be shorter so that they don't overlap into the progress column.

To test this PR, you will need to add a "status_help" property in your "progress_status" site configuration. For example:

This PR also includes 5 new images that can be used for progress status:
* 1-of-5.png
* 2-of-5.png
* 3-of-5.png
* 4-of-5.png
* 5-of-5.png

To get the full updates from #1747 you could use something like this example site configuration:

```
progress_status:
  status_heading: status.progress_status
  status_help: How is the UK doing against the 2030 targets?
  status_types:
    - value: status_1
      label: Very far from 2030 target
      image: assets/img/progress/1-of-5.png
      alt: Very far from 2030 target
    - value: status_2
      label: Far from 2030 target
      image: assets/img/progress/2-of-5.png
      alt: Far from 2030 target
    - value: status_3
      label: Moderate distance to 2030 target
      image: assets/img/progress/3-of-5.png
      alt: Moderate distance to 2030 target
    - value: status_4
      label: Close to 2030 target
      image: assets/img/progress/4-of-5.png
      alt: Close to 2030 target
    - value: status_5
      label: 2030 target achieved
      image: assets/img/progress/5-of-5.png
      alt: 2030 target achieved
    - value: not_measured
      label: Not measured
    - value: no_target
      label: No target exists
    - value: not_available
      label: No data available
```

You would need to also set some of these progress status types (eg, "status_1", "status_2", etc.) on some indicators.

Q | A
--- | ---
Feature branch/test site URL | [Link](http://uk-sdg-feature-branches.s3-website.eu-west-2.amazonaws.com/feature-indicator-progress-updates/1/)
Fixed issues | Fixes #1747 
Related version | 2.1.0-dev
Bugfix, feature or docs? |
* [ ] Keeps backward-compatibility
* [ ] Includes tests
* [ ] Updated docs
* [ ] Updated config forms
* [ ] Added CHANGELOG entry

### CODE REVIEW

**Review by otis-bath — COMMENTED** [review]
Thanks @brockfanning - have got this setup on the indicators of Goal 1, let me know what you think @phillipgardiner

**Comment by phillipgardiner** [comment]
@otis-bath @brockfanning Thanks for this, a couple of bits of feedback

1. No 'target exists' should be 'No 2030 target exists'
2. The first / new grey line below 'Targets and Indicators' is it possible for it to only be the same length as all the others? (e.g. start level with the others)
3. Within some indicators, the progress icon is a bit too close the target or indicator text. Is it possible to set a maximum line length or something so there is always a set gap between the two? For example 1.1.1 text is probably a bit too close to the progress icon etc. Ideally the maximum sentence length for all targets and indicators would come to where the final 'o' is in 'geographic location'

**Comment by brockfanning** [comment]
@otis-bath This is ready for a refresh.

**Review by phillipgardiner — APPROVED** [review]
Perfect :)

**Review by sarah-beasley — APPROVED** [review]

**Pull request merged**
