### PR TITLE
Use increased font size

### PR DESCRIPTION
**Pull request by brockfanning**

### CODE REVIEW

**Comment by brockfanning** [comment]
@SavvasStephanides Ok, made that change. I think we should follow up this PR with a Sass-wide update replacing all font-size rules with variables. Do you agree?

**Comment by brockfanning** [comment]
@LucyGwilliamAdmin This could definitely use a thorough visual test, if you have time to do a feature branch.

**Comment by SavvasStephanides** [comment]
Looks fine from my part.

> Ok, made that change. I think we should follow up this PR with a Sass-wide update replacing all font-size rules with variables. Do you agree?

I'd leave it to what's relevant for this ticket. This ticket is for setting the default font, plus it may be too much for a hotfix.

**Comment by brockfanning** [comment]
@SavvasStephanides Right, sorry, I meant in a follow-up PR.

**Comment by SavvasStephanides** [comment]
@brockfanning In that case, yes I agree.

**Pull request merged**
