### PR TITLE
Accessibility improvements for chart legends

### LINKED ISSUE #867: Change legend colour blocks from spans to buttons and use aria-describedby
image

Spoke to DAC about legend text placement this morning, and described issue with text being in downloaded image if text moved right by legend so they suggested this alternative:

Legend colour blocks are currently spans instead of buttons:
https://github.com/open-sdg/open-sdg/blob/master/_includes/assets/js/indicatorView.js#L388.

These should be buttons instead, and should use `aria-describedby="legend-help"` for the buttons.

They said this alternative could still be an issue for low-vision users as if they're really zoomed in they won't see the text, so would still need to move closer to legend, @AnnCorp suggested perhaps under footnote so not in capture area for downloaded image? @phillipgardiner what are your thoughts from a design p.o.v?

### PR DESCRIPTION
**Pull request by brockfanning**
Fixes #867 

Discussion in #867

### CODE REVIEW

**Comment by jwestw** [comment]
the file _includes/assets/js/indicatorView.js is in conflict. I see that's one of the files you have updated, but am unsure why that's in conflict, rather than it just being an update. I see the git commands to resolve this, but I don't want to overwrite anything I shouldn't. 
Would updating the _config.yaml automatically make my feature branch include the new version of indicatorView.js?

**Comment by brockfanning** [comment]
@jwestw Cool, actually it's the responsibility of the developer to resolve the conflict. I'll resolve it and let you know when it's ready for testing.

**Comment by brockfanning** [comment]
@jwestw Ok the conflict is resolved so this is ready for review again.

**Comment by jwestw** [comment]
Checking for:

1. Legend help text moved to just above the legend   **DONE**
2. Legend items wrapped in <button> elements **DONE**
3. Legend has aria-labelledby referring to the legend help  **DONE**
4. Legend items have aria-pressed which changes as user clicks  **DONE, can see the dynamic change when clicked**
5. Legend items have aria-label with "Press to hide the dataset x" (where "x" is the name of the dataset, eg "Rural", etc.)  **DONE**
6. Legend help is hidden from image download  **DONE, that's really cool!**

**Review by jwestw — APPROVED** [review]
All checked. All seem to be done.

**Comment by brockfanning** [comment]
Thanks @jwestw!

@phillipgardiner this has a minor visual change in that the legend text has been moved. Did you want to see a feature branch? Here is a screenshot:

screenshot-127 0 0 1_4000-2020 09 08-13_47_23

**Comment by phillipgardiner** [comment]
@brockfanning @jwestw Yes please to a feature branch, would like to check it from a design perspective if possible.

**Comment by jwestw** [comment]
Feature branch: http://sdgdev-813006012.eu-west-1.elb.amazonaws.com/jw-test-chart-legend-accessibility

**Pull request merged**
