### PR TITLE
Placeholder indicators

### LINKED ISSUE #1275: Add placeholder indicator e.g. for 11.2.1 (undefined indicator)
Discussed so far:
- could possibly use a new "placeholder" indicator configuration setting, which serves to prevent an indicator page from being generated, and on the goal pages display the contents of that setting rather than a link to an indicator page.
- can countries somehow control exclusion from reporting status counts?

Expected:
image

### PR DESCRIPTION
**Pull request by brockfanning**
Q | A
--- | ---
Feature branch/test site URL | [Link](http://uk-sdg-feature-branches.s3-website.eu-west-2.amazonaws.com/feature-placeholder-indicators/11/)
Fixed issues | Fixes #1275 
Related version | 1.5.0-dev
Bugfix, feature or docs? |
* [ ] Keeps backward-compatibility
* [ ] Includes tests
* [x] Updated docs
* [x] Updated config forms
* [ ] Added CHANGELOG entry

This PR is supported by two other PRs:
* https://github.com/open-sdg/sdg-build/pull/275
* https://github.com/open-sdg/jekyll-open-sdg-plugins/pull/108

### CODE REVIEW

**Comment by LucyGwilliamAdmin** [comment]
@brockfanning I've just tried this here: http://uk-sdg-feature-branches.s3-website.eu-west-2.amazonaws.com/feature-placeholder-indicators/11/

It doesn't seem to be working as expected - the indicator name seems to be being automatically populated from somewhere and is showing as a link rather than the placeholder text being shown.

Here is the metadata file: https://github.com/ONSdigital/sdg-data/blob/feature-placeholder-indicators/meta/11-c-1.md

**Comment by brockfanning** [comment]
@LucyGwilliamAdmin I can't remember offhand how the feature branch stuff works, but are you sure it is pointing to the right places? I tried it locally, and I had to adjust the remote_data_prefix and the remote_theme config settings. (But maybe the feature branch stuff does that for you?)

**Comment by LucyGwilliamAdmin** [comment]
@brockfanning Ahh I updated the Gemfile but not the remote theme - sorry!

**Comment by LucyGwilliamAdmin** [comment]
@brockfanning @phillipgardiner see 11.c.1 at bottom of page here: http://uk-sdg-feature-branches.s3-website.eu-west-2.amazonaws.com/feature-placeholder-indicators/11/

Brock - the indicator name seems to be being pulled through to the indicator page though
Both - should that text be the same as the placeholder text?

E.g. here: 
image

**Comment by brockfanning** [comment]
@LucyGwilliamAdmin Hi Lucy, my thinking was that nobody would ever get to the indicator page, since the link is gone. Did you type in the URL directly or is there a link somewhere that I missed?

**Comment by brockfanning** [comment]
@LucyGwilliamAdmin It is a quick fix if we want to prevent the indicator pages from being created at all. The only reason I left them in was so that admins could use the config forms. But if you think it's safer I'm happy to remove them entirely.

**Comment by LucyGwilliamAdmin** [comment]
@brockfanning I think fine to leave them in

**Comment by LucyGwilliamAdmin** [comment]
x-github-client://openRepo/https://github.com/open-sdg/open-sdg?branch=pr%2F1310&pr=1310

**Comment by phillipgardiner** [comment]
@brockfanning @LucyGwilliamAdmin Looks good to me. I'm assuming that countries are able to put whatever text they wish to there? or are we providing default text which can be overwritten (happy to provide text if the latter).

On a slightly different note. Have we changed something in regard to the fonts used for the indicator numbers? I ask as I've just spotted that the indicator numbers on the goals page seem to be a bigger font than the target numbers on the goals page. I'd have expected them to be the same size and the same size as the indicator text.

**Comment by brockfanning** [comment]
@phillipgardiner I don't remember changing that recently, no. But we can always tweak things that look wrong.

**Comment by brockfanning** [comment]
@phillipgardiner Also about the text, no we're not providing any default text. The mechanism for the feature is that if the country provides text, it will display, but otherwise it will be normal. So it's necessary that the country provide the placeholder text, per indicator.

**Comment by phillipgardiner** [comment]
> @phillipgardiner I don't remember changing that recently, no. But we can always tweak things that look wrong.

The indicator numbers should therefore be 16px so same size as text and will align better too.

**Review by LucyGwilliamAdmin — APPROVED** [review]

**Comment by brockfanning** [comment]
@LucyGwilliamAdmin @phillipgardiner Hope it's OK, I snuck that font-size tweak into this PR. Would you like to re-review this one or just wait and see in the next PR?

**Comment by phillipgardiner** [comment]
@brockfanning all good  :)

**Pull request merged**
