### PR TITLE
Site and indicator configuration forms

### PR DESCRIPTION
**Pull request by brockfanning**
This PR adds configuration forms for site configuration as well as indicator configuration.

Testing this PR requires two things:
1. Use the latest jekyll-open-sdg-plugins code: `gem "jekyll-open-sdg-plugins", "1.2.0.pre.beta3"`
2. Add this to your site config:
```
create_config_forms:
    layout: config-builder
```

To get to the site configuration, look for the link in the footer menu.

To get to the indicator configuration, go to an indicator, click on the "Edit" tab, and then click on "Edit configuration".

The idea behind these configuration forms is that you'll make some changes, click the "Download configuration" button, and then upload the file to Github, replacing whatever file was already there. For site configuration, this would be a site_config.yml file in your data folder. For indicator, this would be somewhere in your data repository where indicator config could be stored.

With this approach, it is best to keep this automated configuration totally separate from other stuff. So, the site configuration should no longer be put into the _config.yml file. And indicator configuration should not be included with actual metadata.

### CODE REVIEW

**Comment by brockfanning** [comment]
@LucyGwilliamAdmin @jwestw This is ready to test if you just want to try out the forms. But for the downloaded config to be useful, we still need to get this PR tested and approved: https://github.com/open-sdg/sdg-build/pull/172

**Comment by brockfanning** [comment]
@LucyGwilliamAdmin @jwestw Actually let me add to this PR an example of splitting out the indicator config before you review.

**Comment by brockfanning** [comment]
* Hardcode link to site config in footer on staging only
* Do not generate site config on production
* Fix error messages appearing down the page
* Add indication of required fields
* Check "content" not displaying in frontpage cards

**Comment by brockfanning** [comment]
Some updates on previous comments:

* Hardcode link to site config in footer on staging only: Should be fixed now
* Do not generate site config on production: I realized we actually need the site config forms on production, so that users can generate production-specific config. As a workaround, I've ensured that these pages do not appear in the site search.
* Fix error messages appearing down the page: I added a bit more of a hint in the popup alert
* Check "content" not displaying in frontpage cards: Should be fixed now

More things to do:
* Add indication of required fields
* High contrast fixes
* Accessibility audit

**Comment by brockfanning** [comment]
The indication of required fields, and the high-contrast fixes, have both been done.

A quick test using a screenreader shows a lot of problems. I think that it's going to be some significant effort to make these forms accessible. In fact, I would lean towards trying an alternative to json-editor (the library that is generating the form) that might be more accessible out of the box. Otherwise we're going to have to write a lot of javascript to make json-editor accessible.

@AnnCorp @LucyGwilliamAdmin @jwestw I don't think that we will have time to make this accessible if we want to get it into version 1.2. Also, given that making it accessible might involve a lot of changes to it, we might want to postpone it until version 1.3 or later.

Also just to be sure - this is an unusual feature in that the audience is the site administrators - not the general public. It is also an optional feature. However, I guess we're still obligated to keep it fully AA accessible, right?

**Comment by brockfanning** [comment]
I've made a bit of progress with the accessibility. I still don't think it would pass a DAC audit, but it is better than before. I've also made this an "opt in" feature, by requiring a site config setting:

```
create_config_forms:
    layout: config-builder
```

I could see adding this to release 1.2.0 as an optional experimental feature, and then continuing to improve the accessibility. @jwestw @LucyGwilliamAdmin I believe this could be tested if you're so inclined. I've added testing instructions to the first post.

**Comment by LucyGwilliamAdmin** [comment]
Made a feature branch:

- [Site config](http://sdgdev-813006012.eu-west-1.elb.amazonaws.com/release-prep-and-config-forms/config/)
- [Indicator config](http://sdgdev-813006012.eu-west-1.elb.amazonaws.com/release-prep-and-config-forms/config/1-1-1/)

@brockfanning I think I remember you saying about adding something in to ensure the URLs don't work on live site - is this right?

**Comment by brockfanning** [comment]
@LucyGwilliamAdmin Sorry I missed this. I added in code to make sure that these configuration pages do not appear in the site search. For example, see how this returns no results: http://sdgdev-813006012.eu-west-1.elb.amazonaws.com/release-prep-and-config-forms/search/?q=configuration

Also, the links to the configuration forms will not appear on production. Normally there are links to the indicator config forms in the "Edit" tab, and there is a link to the site config form in the footer on all pages. (I assume you've got an override of the footer.html file, which is why that footer link is not displaying in your feature branch).

**Comment by LucyGwilliamAdmin** [comment]
@brockfanning I'm looking at this now. I'm wondering if there's a way for that text in the box to be clearer? I don't suppose there's a way for the text to be human readable as it's separate from the site?

image

**Comment by LucyGwilliamAdmin** [comment]
I'm also not sure what's wrong with the default create pages part:
http://sdgdev-813006012.eu-west-1.elb.amazonaws.com/release-prep-and-config-forms/config/

**Comment by brockfanning** [comment]
@LucyGwilliamAdmin I believe there is more we could do to make that error message more user friendly, yes. We could make it a more styled popup instead of that default "alert" and we could also try and control the text to show the human-readable labels instead of those jsonschema paths. That would be a bit of work so I guess it could either be done now as part of this first iteration or later as part of a second iteration.

The problem with create_pages (and also with date_formats) is because the structure of that setting changed. The old structure still works in both cases, but it unfortunately confuses these pages. Here is the updated structure for those two:

```
create_pages:
  - folder: /
    layout: frontpage-alt
    title: 17 goals to transform our world
  - folder: /goals
    layout: goals
    title: UK data for the Sustainable Development Goals
  - folder: /reporting-status
    layout: reportingstatus
    title: Reporting Status
  - filename: indicators.json
    folder: /
    layout: indicator-json
  - folder: /search
    layout: search
    title: Search results

# Date format
date_formats:
  - type: standard
    language: en
    format: "%d %B %Y"
```

If you make these changes to your _config.yml manually, it should let the form render correctly. Before this feature is fully finished we will probably need to figure out a more graceful way to catch these types of issues.

**Comment by brockfanning** [comment]
@LucyGwilliamAdmin Also, I realized that the various title/description fields should not be required. I've updated the jekyll-open-sdg-plugins code. If you want to test this further I'd recommend switching your Gemfile to: `gem 'jekyll-open-sdg-plugins', git: 'https://github.com/open-sdg/jekyll-open-sdg-plugins.git', ref: 'master'`

**Comment by LucyGwilliamAdmin** [comment]
@brockfanning thanks - is baseurl still required - just asking as there's a test which requires it here:
https://github.com/open-sdg/open-sdg-site-starter/blob/develop/scripts/test/html_proofer_staging.sh#L8

**Comment by brockfanning** [comment]
@LucyGwilliamAdmin I don't have baseurl as part of this config, since it's normal Jekyll configuration, and not specific to Open SDG.

**Comment by LucyGwilliamAdmin** [comment]
Ah right - yes I remember you saying about that now. Where did you say that would go again, stay in _config.yml?

**Comment by brockfanning** [comment]
Yep that's right.

**Comment by LucyGwilliamAdmin** [comment]
@brockfanning I seem to get this error even though I have `remote_data_prefix` in [site_config.yml](https://github.com/ONSdigital/sdg-indicators/blob/release-prep-and-config-forms/site_config.yml#L208):

image
https://github.com/ONSdigital/sdg-indicators/runs/1452911351?check_suite_focus=true

**Comment by brockfanning** [comment]
@LucyGwilliamAdmin Try moving that site_config.yml file into the [data folder](https://github.com/ONSdigital/sdg-indicators/tree/release-prep-and-config-forms/data).

**Comment by LucyGwilliamAdmin** [comment]
@brockfanning tried moving that but seem to be having a big issue - I'm pretty sure I have everything in the _config.yml file now though:

https://github.com/ONSdigital/sdg-indicators/blob/release-prep-and-config-forms/_config.yml

**Comment by brockfanning** [comment]
@LucyGwilliamAdmin Thanks - yes there was an issue in the jekyll-open-sdg-plugins code. I've just pushed a commit there - so you could try updating the Gemfile to use "master" for jekyll-open-sdg-plugins.
```

**Comment by LucyGwilliamAdmin** [comment]
Ok - I've just rebuilt and the site is building now but I'm having a bit of a strange issue:
http://sdgdev-813006012.eu-west-1.elb.amazonaws.com/release-prep-and-config-forms/1-1-1/

This is showing when landing on the page even though only headline data is available for that indicator
image

**Comment by brockfanning** [comment]
@LucyGwilliamAdmin Thanks for continuing to catch these issues. That should be fixed, as well as an issue with the metadata tabs.

**Comment by LucyGwilliamAdmin** [comment]
@brockfanning that fixed the chart problem but there also seems to be an issue with the metadata tabs - no content is showing. I'm going to have a fuller test now so will let you know if there's any other issues

**Comment by brockfanning** [comment]
@LucyGwilliamAdmin Sorry, my fix for the metadata tabs was incomplete - the content should be displaying now.

**Comment by LucyGwilliamAdmin** [comment]
@brockfanning thanks - that worked

I seem to be having an issue with maps but not sure if it's to do with my configuration.

We've never set colours before so the config just chose the defaults:

```
map_options:
  minZoom: 4
  maxZoom: 12
  tileURL: >-
    https://api.tiles.mapbox.com/v4/{id}/{z}/{x}/{y}.png?access_token={accessToken}
  tileOptions:
    id: mapbox.light
    accessToken: >-
      pk.eyJ1IjoibHVjeWphbmVnd2lsbCIsImEiOiJjazAyZ2phaGMwajhzM2hxb2czZmdrZ2szIn0.tcj-n08CcU-7tKXFqB-WuQ
    attribution: >-
      <a href="https://www.mapbox.com">Mapbox</a> | <a
      href="http://geoportal.statistics.gov.uk/">ONS</a>
  colorRange: ''
  noValueColor: '#000000'
  styleNormal:
    weight: 0
    opacity: 0
    fillOpacity: 0
    color: '#000000'
    dashArray: ''
  styleHighlighted:
    weight: 0
    opacity: 0
    fillOpacity: 0
    color: '#000000'
    dashArray: ''
  styleStatic:
    weight: 0
    opacity: 0
    fillOpacity: 0
    color: '#000000'
    dashArray: ''
```

Although, that being said, what was set by default is different to what's listed in the [docs](https://open-sdg.readthedocs.io/en/latest/maps/#map_options)

Just changing the values to what's listed in the docs to see if that helps but currently looks like this:
http://sdgdev-813006012.eu-west-1.elb.amazonaws.com/release-prep-and-config-forms/3-a-1/

**Comment by LucyGwilliamAdmin** [comment]
@brockfanning changing those settings fixed it

**Comment by LucyGwilliamAdmin** [comment]
@brockfanning I can't see any other issues - I have sent the feature branch to DAC for accessibility testing - they're going to fit it in at the end of this week

**Comment by brockfanning** [comment]
@LucyGwilliamAdmin Sounds good. What do you recommend we change in regards to the map configuration?

**Comment by LucyGwilliamAdmin** [comment]
@brockfanning wondering if the defaults should be something more standard like green for fill and black for boundaries in the docs:

```
noValueColor: '#f0f0f0'
  styleNormal:
    weight: 1
    opacity: 1
    fillOpacity: 0.7
    color: '#000000'
    dashArray: ''
  styleHighlighted:
    weight: 1
    opacity: 1
    fillOpacity: 0.7
    color: '#000111'
    dashArray: ''
  styleStatic:
    weight: 2
    opacity: 1
    fillOpacity: 0
    color: '#000000'
    dashArray: '5,5'
```

And is there also a way to set a default in the config form if a country is moving to that approach but don't currently have colours set, as the defaults that were set during my test meant the maps weren't displaying

**Comment by brockfanning** [comment]
Sounds good. I'm happy to use those as defaults. We should:
1. Make sure those are the actual defaults used
2. Update the docs to reflect that
3. Update the config form to use those as defaults as well

**Comment by brockfanning** [comment]
@LucyGwilliamAdmin On second thought - I'm wary of changing the default colors, because that would change the colors for countries that are already using maps without setting those colors. Do you think it's OK to keep the existing default colors for now? Or should we change them and put a note about it in the release notes? For reference here are the actual defaults being used: https://github.com/open-sdg/open-sdg/blob/master/_includes/assets/js/plugins/jquery.sdgMap.js#L21-L46

I've made a few tweaks, and as far as I can tell, the map options are now consistent across the docs, maps, and config form defaults.

**Comment by LucyGwilliamAdmin** [comment]
@brockfanning I'm happy for them to stay as the current default colours

**Comment by brockfanning** [comment]
@LucyGwilliamAdmin Ok cool. Those conflicts are resolved here so this is ready to be tested again - maybe also by testing without actually enabling the config forms.

**Comment by LucyGwilliamAdmin** [comment]
Feature branch pointing at this branch but not turning on config forms:
http://sdgdev-813006012.eu-west-1.elb.amazonaws.com/config-test-no-config/

All looks good to me

Removed map colour settings from the other branch. This is how the map looks:
image

This is how the map looks if I don't have any colour settings set, open the config form, save the config form without making and changes and upload the config form:
image

So I'm wondering if there's a slight diff in the site default and the config form default?

**Comment by brockfanning** [comment]
@LucyGwilliamAdmin I'm having trouble recreating that - I have made some edits to jekyll-open-sdg-plugins today, so I'm wondering if maybe a feature-branch needed to be refreshed. Hate to ask but do you mind trying again? I think the version with the light-gray borders is what should display, whether with no config at all, or with config downloaded using only the defaults. (Though I'm starting to like those darker borders...)

**Comment by LucyGwilliamAdmin** [comment]
I have just rebuilt and checked and all good now

**Review by LucyGwilliamAdmin — APPROVED** [review]
Approving as all looks good for beta release

**Pull request merged**
