### PR TITLE
Translate page titles and content

### LINKED ISSUE #787: Allow translation keys to be used in title/content of "page" layout
**Is your feature request related to a problem? Please describe.**

Currently the translated titles of pages (ie, Jekyll documents using the "page" layout) need to maintained directly in the Jekyll files. This works fine, but some implementations may be using translation management systems (like Weblate or Transifex) and would prefer that all translations be managed in one place: the data repository. To support this, the Jekyll files would only have translation keys - and no actual translations.

**Describe the solution that you need**

Allow the title and content of pages to use translation keys. For example, this could be the "About" page:

```
---
title: custom.my-about-page-title
permalink: /about
layout: page
---
custom.my-about-page-content
```

**Why do you need this feature?**

To allow translations of pages to be managed entirely from the data repository.

**Describe alternatives you've considered**

The current workaround is to manage the translation of the title directly in the Jekyll file. The content can actually already refer to translation keys, but it requires the slightly-technical "Liquid" syntax. Example:

```
---
title: My translated title
permalink: /about
layout: page
---
{{ page.t.custom.my-about-page-content | markdownify }}
```

Because this workaround exists, this is not a high-priority issue.

### PR DESCRIPTION
**Pull request by brockfanning**
Fixes #787

### CODE REVIEW

**Comment by LucyGwilliamAdmin** [comment]
@jwestw can you take a look at this one please?

1. For this you will need a multilingual feature branch.
2. Once you have that up and running create a folder called translations in the root of your data branch.
3. In there create a file called custom.yml or custom.csv for each language, which contains the following fields along with their values (see the 2nd and 3rd files under the [files changed tab](https://github.com/open-sdg/open-sdg/pull/891/files) for example):

- about
- about content

4. See the [translation section in Brock's doc on data-configuration](https://github.com/open-sdg/open-sdg/blob/075a591e6b24ededc9d080c51e5defa52a8ff3a5/docs/data-configuration.md#translations) for how to point at a folder containing local translations.

5. Now go to the site branch for the feature branch and edit the about pages in each of language so that they use the translation keys instead (like in the 5th and 6th files in the files changed tab).

There's two ways to deal with pages on multilingual sites:

- like in the tests (the files under the File changes tabs) 
- using the subfolder approach (like in site starter: https://github.com/open-sdg/open-sdg-site-starter/tree/develop/_pages)

This isn't mean to be prescriptive but I know you haven't done much testing with multilingual yet - give me a shout if you have any questions though!

**Comment by jwestw** [comment]
Indicator feature branch: http://sdgdev-813006012.eu-west-1.elb.amazonaws.com/jw-translated-page-titles

**Comment by jwestw** [comment]
I have completed step 1. Will continue with the rest of the steps asap.

**Comment by jwestw** [comment]
Completed steps 2 & 3. Do not really understand the translation section in step 4. Could somebody explain please?

**Comment by LucyGwilliamAdmin** [comment]
That's guidance on the data config fields. Also now on read the docs: https://open-sdg.readthedocs.io/en/latest/data-configuration/ - will continue discussion offline

**Comment by jwestw** [comment]
You can see this working here: http://sdgdev-813006012.eu-west-1.elb.amazonaws.com/jw-translated-page-titles/es/about/

**Comment by LucyGwilliamAdmin** [comment]
@jwestw the title looks good :) But for some reason the content isn't being translated - see line below title ("custom.about_content)

**Comment by brockfanning** [comment]
That sounds like it would explain it. Basically the code looks to see if the _entirety_ of the content is a translation key, and if not, it shows whatever was there.

**Review by jwestw — APPROVED** [review]
Happy to approve this as all translations seem to be working now.

**Pull request merged**
