### PR TITLE
Add site title to page title

### PR DESCRIPTION
**Pull request by brockfanning**
Demonstration of adding site title to page title.

### CODE REVIEW

**Comment by LucyGwilliamAdmin** [comment]
Here's a feature branch showing how this would look on UK site:
http://sdgdev-813006012.eu-west-1.elb.amazonaws.com/dac2020/

@phillipgardiner I know you said you'll pick this up tomorrow - this is the PR about including site title in all page titles

**Comment by phillipgardiner** [comment]
@brockfanning @LucyGwilliamAdmin My thoughts on this (and i'm not expert!). The H1 should be followed by the site name.
Like you say we are probbaly best to discuss at tech call as I need to make sure I have understood the issue / potential solution correctly. The only thing I would add is I believe as a user may search using an acronym we should potentially add '(SDG)' at the end of the site name.

**Comment by phillipgardiner** [comment]
Also can we clarify on the call what the name of of site actually is?

**Comment by brockfanning** [comment]
We'll also add the site title to the goal and indicator pages.

**Comment by brockfanning** [comment]
@LucyGwilliamAdmin This is ready for review again. I thought it might make sense to split out the page title into its own include file, to make it easier for countries that might want to have more control.

**Review by LucyGwilliamAdmin — APPROVED** [review]
Looks good!

http://sdgdev-813006012.eu-west-1.elb.amazonaws.com/dac2020/

**Pull request merged**
