### PR TITLE
Adjust homepage whitespace

### PR DESCRIPTION
**Pull request by SavvasStephanides**
[UK Feature branch](http://sdgdev-813006012.eu-west-1.elb.amazonaws.com/opensdg1-whitespace/)

Done some basic whitespacing on the homepage for this change. Let me know if it looks good to you or if you'd like to see some changes. Feedback more than welcome.

### CODE REVIEW

**Comment by brockfanning** [comment]
@SavvasStephanides Is this not possible with CSS alone, rather than adding extra markup?

**Comment by SavvasStephanides** [comment]
The rationale of using spacers is to make the `html` more modular by adding a `<div>` whose sole purpose is to give whitespace rather than alter the existing elements. But you might be right, it's probably unnecessary. I'll change it.

**Comment by brockfanning** [comment]
@SavvasStephanides I've always been of the opinion that visual stuff should be in CSS, and semantic content should be in HTML. I do like modularity, but would prefer modular CSS - like a class that can be added to something to give it margin-top, for example - over the practice of using spacer divs.

**Comment by SavvasStephanides** [comment]
@brockfanning Thanks for the feedback. Removed the empty `<div>`s and added the classes to existing elements instead

**Comment by brockfanning** [comment]
@SavvasStephanides I think the spacer divs got left in there.

**Pull request merged**
