### PR TITLE
Line-breaks for Khmer and Lao

### PR DESCRIPTION
**Pull request by brockfanning**
Q | A
--- | ---
Feature branch/test site URL | [Link](add link here)
Fixed issues | NA
Related version | 1.4.0-dev
Bugfix, feature or docs? | Feature
Keeps backward-compatibility? |✔️
Includes tests? |❌
Updated docs? |❌
Updated config forms? | NA
Added CHANGELOG entry? |❌

### CODE REVIEW

**Comment by LucyGwilliamAdmin** [comment]
@brockfanning are any config options required for this?

**Comment by brockfanning** [comment]
@LucyGwilliamAdmin No there's no config - my thinking was thinking was that any site using these languages would want the behavior. I have yet to get confirmation that this behavior is wanted though. In the meantime, I've added Lao as well.

**Comment by LucyGwilliamAdmin** [comment]
@brockfanning is this already being used on Cambodia and Lao sites?

**Comment by brockfanning** [comment]
Yes, though I need to make a tweak. It's not catching the goal titles, as you can see here: https://sdg-cambodia.github.io/site/2/

I did get confirmation from native Lao speakers that this approach is acceptable.

**Comment by brockfanning** [comment]
@LucyGwilliamAdmin That's done, I think this is ready for review. There may be more bits and pieces throughout the site that need to be targeted in CSS, so let me know if you notice any line-break issues in the Lao or Cambodia sites.

**Comment by LucyGwilliamAdmin** [comment]
@brockfanning not sure if it's related but 138 in the overall reporting status is wrapping:
https://sdg-cambodia.github.io/site/reporting-status/

image

**Comment by LucyGwilliamAdmin** [comment]
Also is the national metadata tab as expected i.e. first column width:
https://sdg-cambodia.github.io/site/1-2-1/

**Comment by brockfanning** [comment]
@LucyGwilliamAdmin Thanks, those were both related, and I've added some exceptions to catch those cases.

**Review by LucyGwilliamAdmin — APPROVED** [review]

**Pull request merged**
