### PR TITLE
Use 0.7 opacity on tooltips

### LINKED ISSUE #1063: Transparent chart tooltip background
Adjust the transparency of the tool tip to enable easier viewing of the graph underneath (particularly important when long unit names and dissagregation names are present. 

The background color is currently set at 0.8 opacity. 

@brockfanning and @phillipgardiner to 'turn the dials' to decide on optimum opacity.  

Suggest 0.6 opacity as a starting point.

### PR DESCRIPTION
**Pull request by brockfanning**
Q | A
--- | ---
Feature branch/test site URL | [Link](http://uk-sdg-feature-branches.s3-website.eu-west-2.amazonaws.com/feature-site-lower-tooltip-opacity)
Fixed issues | Fixes #1063 
Related version | 1.5.0-dev
Bugfix, feature or docs? | feature
* [x] Keeps backward-compatibility
* [ ] Includes tests
* [ ] Updated docs
* [ ] Updated config forms
* [ ] Added CHANGELOG entry

### CODE REVIEW

**Comment by LucyGwilliamAdmin** [comment]
@phillipgardiner can you take a look at this one please?

**Comment by brockfanning** [comment]
@phillipgardiner @LucyGwilliamAdmin Is it just me or is 0.6 a little too transparent?

**Comment by phillipgardiner** [comment]
@brockfanning @LucyGwilliamAdmin happy to look at alternatives (I guess 0.7 is the obvious). The important bit is that on some graphs the tool tip end up quite big due to the words so its important that users can still roughly see the points underneath - trying to find a good example but cant find it now!

**Comment by LucyGwilliamAdmin** [comment]
@brockfanning could you change to 0.7 when you have chance please?

**Comment by brockfanning** [comment]
@LucyGwilliamAdmin Ok, it's ready for a refresh.

**Comment by LucyGwilliamAdmin** [comment]
Feature branch has been refreshed: http://uk-sdg-feature-branches.s3-website.eu-west-2.amazonaws.com/feature-site-lower-tooltip-opacity/1-1-1/

Also here is 0.6 for comparison: http://uk-sdg-feature-branches.s3-website.eu-west-2.amazonaws.com/feature-site-tooltip-opacity-0.6/1-1-1/

**Comment by phillipgardiner** [comment]
@brockfanning @LucyGwilliamAdmin I'd say based on the examples, lets go with 0.7 as seems to strike the right balance.

**Review by LucyGwilliamAdmin — APPROVED** [review]

**Pull request merged**
