### PR TITLE
Consider hierarchy when sorting fields

### LINKED ISSUE #817: Subcategories are sorted alphabetically even when there is a hierarchy
Site repository URL: https://onsdigital.github.io/sdg-indicators
Open SDG version: 1.1.0

**Describe the bug**

The subcategories (disaggregations) are sorted alphabetically, even when there is supposed to be a hierarchy. This ruins the effect of the hierarchical indentation. CORRECTION: They aren't being sorted alphabetically, it turns out. But still they are not being sorted hierarchically.

**To Reproduce**
1. Go to https://onsdigital.github.io/sdg-indicators/2-2-2/
2. See how "BMI" is showing above "Country"

**Expected behavior**
In the example above, "BMI" should be below "Country". Each indentation should start the alphabetic sorting over.

**Screenshots**

screenshot-onsdigital github io-2020 08 20-14_20_41

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Firefox
 - Version 79.0

This issue was split off from #390

### PR DESCRIPTION
**Pull request by brockfanning**
Fixes #817

### CODE REVIEW

**Comment by jwestw** [comment]
Feature branch: http://sdgdev-813006012.eu-west-1.elb.amazonaws.com/jw-test-fix-hierarchical-field-sorting

**Comment by jwestw** [comment]
I notice that the icons are not loading even after a hard refresh. They do appear when hovering over them with the mouse pointer however. 

**This is in Chrome:**
image

**This is in IE:**
image


I have double checked my update to _cofig.yml but it seems to be correct. What else could be causing this?

**Comment by jwestw** [comment]
The subcategories appear to be in the correct order on indicator 2-2-2. 

image

**Comment by LucyGwilliamAdmin** [comment]
> I notice that the icons are not loading even after a hard refresh. They do appear when hovering over them with the mouse pointer however.

> I have double checked my update to _cofig.yml but it seems to be correct. What else could be causing this?

@jwestw it's because Brock's branch was created before some of the accessibility fixes - try to ignore the fact that the icons aren't showing.

**Comment by jwestw** [comment]
Then the problem seems to be fixed. @brockfanning okay to merge

**Review by jwestw — APPROVED** [review]
Approving according to my last comments and Brock's request.

**Pull request merged**
