### PR TITLE
Remove Google Webfont and document how to add them

### PR DESCRIPTION
**Pull request by brockfanning**
Q | A
--- | ---
Feature branch/test site URL | [Link](http://uk-sdg-feature-branches.s3-website.eu-west-2.amazonaws.com/feature-site-remove-webfonts/goals/)
Fixed issues | Fixes #ISSUENUMBER
Related version | 1.4.0-dev
Bugfix, feature or docs? |
Keeps backward-compatibility? |❌ (breaking change will need documentation in changelog)
Includes tests? |NA
Updated docs? |✔️
Updated config forms? |NA
Added CHANGELOG entry? |❌

### CODE REVIEW

**Comment by LucyGwilliamAdmin** [comment]
@brockfanning @phillipgardiner link added - main changes are that headings are bolder

**Comment by phillipgardiner** [comment]
@LucyGwilliamAdmin @brockfanning Sorry can I just check, we are removing open-sans and defaulting to Helvetica then Arial? When I click inspect I still see references to open-sans - is that normal (please excuse my lack of tech knowhow!)

I think I may have spotted one things but needs double checking. I think we have lost the grey on the main navigation, the main navigation should be #595959.

@AnnCorp @LucyGwilliamAdmin @brockfanning on a personal level I'm not sure I like the change. I can't put my finger on it though. The writing seems more blurry, I think this could be due to the new fonts being naturally smaller (e.g. both 16px but one naturally smaller) and less spaced. Like I say though more a personal opinion.

**Comment by LucyGwilliamAdmin** [comment]
What if we change font weight to 400 - it then looks very similar to what we currently have:
image

**Comment by phillipgardiner** [comment]
@LucyGwilliamAdmin that does look better to me, is there anyway of updating the link to show that as I'm struggling to amke that change my end to view it in aciton.

**Comment by LucyGwilliamAdmin** [comment]
@phillipgardiner here you go - with 400: http://uk-sdg-feature-branches.s3-website.eu-west-2.amazonaws.com/feature-site-remove-webfonts-400/

**Comment by phillipgardiner** [comment]
@brockfanning @LucyGwilliamAdmin Ignore my comment above about the colour of the main navigation. I was having a moment! We changed it to black (https://github.com/open-sdg/open-sdg/issues/1058). 

I think looks better with that weight of 400 :)

**Comment by brockfanning** [comment]
@phillipgardiner Regarding the "Open Sans" still being there - I did leave that on purpose, to make it easier for people to continue using it. If it's missing, browsers will fallback to the next one in line: Helvetica. By leaving it in, if a country wants to continue using it, they just need to change one thing (adding the call to Google Webfonts).

Also just wanted to reference the issue I made to discuss this change, in general (and give folks a chance to raise objections): https://github.com/open-sdg/open-sdg/issues/1243

Let me also call attention to the note in that issue about the possibility of self-hosting the Open Sans font, which may be an alternative to dropping it.

Finally a UK-specific note on the subject of fonts - in the cookies PR I'm trying out the GDS Transport font, in case you're curious what that looks like.

**Pull request closed without merging**
