### PR TITLE
Make the configuration documentation alphabetical

### PR DESCRIPTION
**Pull request by brockfanning**
This PR includes:
1. Make the configuration settings listed in alphabetical order
2. Instead of separate sections for optional/required, indicate optional/required at the beginning of descriptions.

### CODE REVIEW

**Comment by SavvasStephanides** [comment]
Consideration: should these configurations really be laid out alphabetically, or should they be in the order of most important/popular?

**Comment by brockfanning** [comment]
@SavvasStephanides My opinion is that, as a reference document, the list needs to be geared towards looking things up. I use it myself quite a bit, and always wish that it was alphabetical so that I could scan right to what I'm looking for, instead of having to scan the whole list each time.

**Comment by SavvasStephanides** [comment]
@brockfanning Cool. Fair enough then!

**Comment by LucyGwilliamAdmin** [comment]
@brockfanning I'm just looking at this now - just have a question about one of the fields `graph_color_number` - does this correspond to the maximum number of lines allowed on a graph before the warning displays? i.e:
image

**Comment by LucyGwilliamAdmin** [comment]
@brockfanning also a little confused about `non_global_metadata` - couldn't the same result be achieved by using the `metadata_tabs` field?

**Comment by brockfanning** [comment]
> @brockfanning I'm just looking at this now - just have a question about one of the fields `graph_color_number` - does this correspond to the maximum number of lines allowed on a graph before the warning displays? i.e:

Yes, that's my understanding.

> @brockfanning also a little confused about `non_global_metadata` - couldn't the same result be achieved by using the `metadata_tabs` field?

Yes I think that's true. I guess we implemented `non_global_metadata` first and then later implemented `metadata_tabs`.

**Comment by LucyGwilliamAdmin** [comment]
@brockfanning thanks for the clarification.
re. `graph_color_number` do you know what the default maximum number is - just thinking we could include it here.

Could `non_global_metadata` be removed or do we need to keep it for backwards compatability?

**Comment by brockfanning** [comment]
@LucyGwilliamAdmin Maybe we leave it in but note that it's deprecated? I just pushed up a commit with some clarifications on `non_global_metadata` and `graph_color_number`. What do you think?

**Pull request merged**
