### PR TITLE
Another disaggregation control hierarchy sorting fix

### PR DESCRIPTION
**Pull request by brockfanning**
Q | A
--- | ---
Feature branch/test site URL | [Link](http://sdgdev-813006012.eu-west-1.elb.amazonaws.com/hierarchy-sorting-fix-3)
Fixed issues | Not reported - see below
Related version | 1.3.0-dev
Bugfix, feature or docs? | Bugfix
Keeps backward-compatibility? |✔️
Includes tests? |❌
Updated docs? |NA
Updated config forms? |NA
Added CHANGELOG entry? |❌

This is a work in progress - and may eventually be closed. I am not able to recreate an actual need for this, but I wanted to document this as a potentially being needed. If any problems arise with the disaggregation control sorting, this may be related.

### CODE REVIEW

**Comment by LucyGwilliamAdmin** [comment]
@brockfanning @emmawoodons I've just done super quick check and it seems this resolves the issue with 3.4.1:

http://sdgdev-813006012.eu-west-1.elb.amazonaws.com/hierarchy-sorting-fix-3/3-4-1/

**Comment by brockfanning** [comment]
Great, thanks for testing!

**Comment by EmmaWoodONS** [comment]
> @brockfanning @EmmaWoodONS I've just done super quick check and it seems this resolves the issue with 3.4.1:
> 
> http://sdgdev-813006012.eu-west-1.elb.amazonaws.com/hierarchy-sorting-fix-3/3-4-1/

This looks good to me! Thank you :)

**Comment by LucyGwilliamAdmin** [comment]
@brockfanning do you think we need to go through other indicators and see if it's changed any other disaggregations unexpectedly?

**Comment by brockfanning** [comment]
@LucyGwilliamAdmin Yes I think that would be a good idea.

**Review by LucyGwilliamAdmin — APPROVED** [review]
UK data team have looked at all indicators and didn't see any issues

**Pull request merged**
