### PR TITLE
Breadcrumbs on all pages

### LINKED ISSUE #1625: Add breadcrumb navigation to all non goal and indicator pages
Breadcrumb navigation is missing from all non goal and indicator pages. Add breadcrumbs following the GDS standard to the following pages:

- Goals (https://sdgdata.gov.uk/goals/)
- Reporting status (https://sdgdata.gov.uk/reporting-status/
- About (https://sdgdata.gov.uk/about/
- Publications (https://sdgdata.gov.uk/publications/
- FAQ (https://sdgdata.gov.uk/faq/
- Updates (https://sdgdata.gov.uk/updates/)

GDS standard: https://design-system.service.gov.uk/components/breadcrumbs/

### PR DESCRIPTION
**Pull request by brockfanning**
Q | A
--- | ---
Feature branch/test site URL | [Link](http://uk-sdg-feature-branches.s3-website.eu-west-2.amazonaws.com/feature-site-page-breadcrumbs/)
Fixed issues | Fixes #1625 
Related version | 2.0.0-dev
Bugfix, feature or docs? |
* [ ] Keeps backward-compatibility
* [ ] Includes tests
* [ ] Updated docs
* [ ] Updated config forms
* [ ] Added CHANGELOG entry

### CODE REVIEW

**Review by otis-bath — APPROVED** [review]
From a functionality point of view this is all working as planned - should this also be on the updates page by default or is that something we would set in the UK? What are your thoughts @phillipgardiner?

**Comment by brockfanning** [comment]
@otis-bath Makes sense - I just added it to that layout as well.

**Comment by brockfanning** [comment]
@phillipgardiner I think @otis-bath needs to refresh the feature branch to get it to show up on the Updates page. I forgot about those others, but I've added them now too. So they should all show breadcrumbs once the feature branch is refreshed. I also added it to a few more (lesser-used) layouts that we have, including the search results page.

So the PR now adds these simple "Home" breadcrumbs to all of the following layouts:
* page
* news
* goals
* reportingstatus
* initiative
* initiatives
* search
* categories
* standalone-indicators

**Comment by otis-bath** [comment]
HI @brockfanning - have just refreshed this seems like the page no longer builds. I am pointing at the 2.0.0-dev branch in the Gemfile still - do you know why this would be?

**Comment by brockfanning** [comment]
I believe I broke something with a commit to jekyll-open-sdg-plugins. I will figure that out.

In the meantime @otis-bath @phillipgardiner you can review this ticket still by avoiding the homepage. For example interior pages should work: http://uk-sdg-feature-branches.s3-website.eu-west-2.amazonaws.com/feature-site-page-breadcrumbs/about/

**Comment by brockfanning** [comment]
@otis-bath The issue with jekyll-open-sdg-plugins should also be fixed, so I think if you refresh the homepage will start working again.

**Review by phillipgardiner — APPROVED** [review]
Looks good to me

**Pull request merged**
