### PR TITLE
Add gutter to sources tab

### PR DESCRIPTION
**Pull request by brockfanning**
This is an attempt to address one issue mentioned in #504

### CODE REVIEW

**Comment by brockfanning** [comment]
Here's a screenshot:

screenshot-127 0 0 1_4000-2021 02 17-11_07_07

**Comment by phillipgardiner** [comment]
@brockfanning thanks for the screenshot. I definitely think that helps :). I believe it is probably now a decision for @AnnCorp on weather any further time is spent addressing this (as per the slack conversation).

**Comment by LucyGwilliamAdmin** [comment]
@brockfanning @phillipgardiner does this require anything from James or I?

**Comment by brockfanning** [comment]
I'm not sure if this needs a feature branch, since it's straightforward enough that a screenshot is good. But I'll defer to @phillipgardiner.

**Comment by AnnCorp** [comment]
@brockfanning @phillipgardiner I think this makes a big improvement - happy that this is good enough for now.

**Comment by phillipgardiner** [comment]
@brockfanning @LucyGwilliamAdmin I'm happy don't think any need for a feature branch on this one.

**Review by LucyGwilliamAdmin — APPROVED** [review]
Approving based on comments

**Pull request merged**
