### PR TITLE
Styles updates for data notices

### LINKED ISSUE #1545: Update styling of data notice
### Discussed in https://github.com/open-sdg/open-sdg/discussions/1540

<div type='discussions-op-text'>

<sup>Originally posted by **LucyGwilliamAdmin** January 17, 2022</sup>
Currently in Open SDG, data notices are styled like this:
image

UK are customising so the look like this:
image

Let's discuss if we should implement the changes on Open SDG

I think we should also consider (for 2.0.0) removing the [option for different colours](https://open-sdg.readthedocs.io/en/latest/indicator-configuration/#data_notice_class) as it's difficult to ensure accessibility</div>

### PR DESCRIPTION
**Pull request by brockfanning**
Q | A
--- | ---
Feature branch/test site URL | [Link](http://uk-sdg-feature-branches.s3-website.eu-west-2.amazonaws.com/feature-site-data-notice-style-updates/archived-indicators/1-a-1-archived/)
Fixed issues | Fixes #1545 
Related version | 1.8.0-dev
Bugfix, feature or docs? |
* [ ] Keeps backward-compatibility
* [ ] Includes tests
* [ ] Updated docs
* [ ] Updated config forms
* [ ] Added CHANGELOG entry

### CODE REVIEW

**Comment by LucyGwilliamAdmin** [comment]
@brockfanning @phillipgardiner @otis-bath feature branch added to description

Looks good on desktop but doesn't look quite right on mobile - the icon isn't quite in the right place:

**Comment by brockfanning** [comment]
@LucyGwilliamAdmin This is ready for a refresh - I've added some fixes for the placement of that icon (giving it the same margin-left as the heading and text).

Note that you could update some of your custom CSS:
* This can be removed because it's part of this PR: https://github.com/ONSdigital/sdg-indicators/blob/develop/_sass/custom.scss#L84-L87
* I don't know the purpose of this, but at first glance it seems like it should be removed: https://github.com/ONSdigital/sdg-indicators/blob/develop/_sass/custom.scss#L80-L82
* This can be remove because it's part of this PR: https://github.com/ONSdigital/sdg-indicators/blob/develop/_sass/custom.scss#L97-L99

**Comment by LucyGwilliamAdmin** [comment]
@phillipgardiner apologies - I meant on mobile version. Design system shows it like this: 
image

**Comment by brockfanning** [comment]
@LucyGwilliamAdmin @phillipgardiner Ok, I'll try to make the icon stay aligned to the left, regardless of how narrow the screen is.

**Comment by brockfanning** [comment]
@LucyGwilliamAdmin Can you try a refresh of this one? I've tried a different approach using the grid system to accomplish positioning.

**Comment by LucyGwilliamAdmin** [comment]
@brockfanning this has been refreshed
@phillipgardiner - this is ready for your review. can you check desktop and mobile please?

**Comment by phillipgardiner** [comment]
@brockfanning @LucyGwilliamAdmin Looks good to me :)

**Review by LucyGwilliamAdmin — APPROVED** [review]

**Pull request merged**
