### PR TITLE
Fix focus color on dropdowns in high-contrast

### PR DESCRIPTION
**Pull request by brockfanning**
Q | A
--- | ---
Feature branch/test site URL | [Link](http://sdgdev-813006012.eu-west-1.elb.amazonaws.com/high-contrast-dropdown-focus-color)
Fixed issues | #1107
Related version | 1.3.0-dev
Bugfix, feature or docs? | Bugfix
Keeps backward-compatibility? |✔️
Updated docs/config-forms? |NA
Added CHANGELOG entry? |❌

### CODE REVIEW

**Comment by LucyGwilliamAdmin** [comment]
@brockfanning @phillipgardiner link to feature branch added. Looks good to me - text in now black in focus on high contrast mode except for in these cases but I assume the yellow here will change?

image

image

image

**Comment by brockfanning** [comment]
@LucyGwilliamAdmin I think #1120 may fix those cases, but we should confirm when testing that one.

**Comment by phillipgardiner** [comment]
@brockfanning @LucyGwilliamAdmin I don't think this one is correct yet? The text needs to be black when it first appears, not just when it is in focus.

**Comment by LucyGwilliamAdmin** [comment]
@phillipgardiner I'm not too sure what you mean? if text is black won't it be same colour as background? Perhaps I'm looking in wrong place

**Comment by phillipgardiner** [comment]
@LucyGwilliamAdmin Sorry, my fault, I was looking at the wrong ticket / feature branch combination!

**Comment by LucyGwilliamAdmin** [comment]
@phillipgardiner ah no probs - #1120 does fix the highlight issue so think this one's ready?

**Review by LucyGwilliamAdmin — APPROVED** [review]
Looks good, text is black when dropdown is focussed on

**Pull request merged**
