### PR TITLE
Searchbtn fix

### LINKED ISSUE #259: Search bar isn't right on IE
image

### PR DESCRIPTION
**Pull request by LucyGwilliamAdmin**
Fixes #259 - the sizing at least.

Still have issue with font awesome icon (or at least I am @brockfanning can you confirm whether you can see the search icon on IE)

https://sdg.mango-solutions.com/search-button/

### CODE REVIEW

**Comment by LucyGwilliamAdmin** [comment]
From #152:

Works on personal laptop bur not on work laptop. I have come across this post which says:

'Font downloads are disabled in IE, under Internet Options / Security / Custom Level / Font Downloads enable /disable. They might be disabled by your network admin, in which case you would not be able to see nor change this setting.'

Unfortunately, these security settings are disabled for us so I cannot try this.

**Comment by LucyGwilliamAdmin** [comment]
@brockfanning could you take a look at this please?

Also once merged - is there a way for it be added to the 0.7.0 release as it's a bug fix rather than a new feature, or would a new release (0.7.1) have to be made?

**Comment by LucyGwilliamAdmin** [comment]
@brockfanning - thanks for testing.

When I remove the `style="height: 34px;"` attribute from the button, it looks like this on IE:
image
compared to having the style attribute:
image


Agree with you on having `right: 20px` so have changed that.

**Comment by LucyGwilliamAdmin** [comment]
@brockfanning do you think this is ready to be merged in?

**Comment by brockfanning** [comment]
My mistake, I see that the `height: 34px` that's in the CSS now is only applied to the `input` element. Could we add CSS to apply that height to the `button` element? Like maybe:
```
#search-btn {
  height: 34px;
}
```
It's usually a good idea to avoid putting style directly in the HTML, because it can confusing things for developers who are trying to tweak things later.

**Pull request closed without merging**
