### PR TITLE
Switch to Lodash instead of Underscrore

### LINKED ISSUE #943: Use Lodash instead of Underscore
**Is your feature request related to a problem? Please describe.**

This is not related to any particular problem, just a potential for a slight performance increase and dev experience improvement.

**Describe the solution that you need**

The library [Lodash](https://lodash.com/) is a superset of [Underscore](https://underscorejs.org/) (which we already use) and Lodash is reportedly faster. Being a superset it also has some additional utility functions. In theory we could replace Underscore with Lodash and nothing would change (except a slight speed increase and more utility functions).

**Why do you need this feature?**

No particular reason other than the need for faster rendering on the indicator pages.

**Describe alternatives you've considered**

We could always leave things as-is, so this is not a high priority.

### PR DESCRIPTION
**Pull request by brockfanning**
Fixes #943 

To test this, we should mainly focus on indicator pages, and making sure that everything still works.

EDIT: [Feature Branch](http://sdgdev-813006012.eu-west-1.elb.amazonaws.com/underscore-to-lodash/)

### CODE REVIEW

**Comment by jwestw** [comment]
I have looked at indicators on the [feature branch](http://sdgdev-813006012.eu-west-1.elb.amazonaws.com/underscore-to-lodash/). I can't see anything that is not working. 

@brockfanning Is there anything in particular that you think might break?

**Comment by brockfanning** [comment]
@jwestw Not really, just indicator pages in general - the more complex the better. FYI, I just noticed there was a conflict that I had to resolve in the PR.

**Comment by jwestw** [comment]
I rebuilt it after the conflict resolution. All seems good still.

**Review by jwestw — APPROVED** [review]
Approving. Looks good.

**Pull request merged**
