### PR TITLE
Expert review: Underline menu items on hover

### PR DESCRIPTION
**Pull request by SavvasStephanides**
An update to the `scss` file to underline inactive menu items on hover.

Since Brock is currently refactoring the style sheets, we'll deal with them when the merge conflicts arise.

Test: http://sdgdev-813006012.eu-west-1.elb.amazonaws.com/opensdg_menu_underline/

### CODE REVIEW

**Comment by SavvasStephanides** [comment]
@brockfanning Can you please assist with the failing CircleCI checks?

**Comment by brockfanning** [comment]
@SavvasStephanides Will do - I feel like this has happened before. I'll look into it.

**Comment by brockfanning** [comment]
@SavvasStephanides I think your branch might be out of date. The most recent commit is from November. I'd recommend pulling the latest code from master and making a new branch from that.

**Comment by SavvasStephanides** [comment]
Thanks @brockfanning. I pulled from the latest release `0.10.0`. Probably best if I pull from master but not sure if it will be affected by any breaking changes.

**Comment by brockfanning** [comment]
Ok cool. Yeah in general, all PRs should start from the latest master branch.

**Pull request closed without merging**
