### PR TITLE
move data acquisition to top of layout fixes #64

### LINKED ISSUE #64: title text not finding goal info
As shown in the UK version the title text is pulling through the wrong goal information:

image

Here the short text is for goal 1 not goal 2.

The reason is that on line https://github.com/open-sdg/open-sdg/blob/2d04ac1dad5af4e2fd0925dc9259149e720d6169/_includes/head.html#L17 where we assign the goal information, it uses `page.sdg_goal` which no longer exists at the page level. The page only knows:

```yaml
indicator: 2.3.2
layout: indicator
permalink: /2-3-2/
```

And the rest comes from the meta data which first appears below the `head.html` include https://github.com/open-sdg/open-sdg/blob/2d04ac1dad5af4e2fd0925dc9259149e720d6169/_layouts/indicator.html#L8

So we either need to remove the goal info or pull in the meta data higher up so that the `head.html` include can use it too.

### PR DESCRIPTION
**Pull request by dougmet**
The indicator page has to get a lot of data that's been imported from the data sets and the metadata. This PR loads that data earlier so that the metadata about goals can be pulled through to the page head.

### CODE REVIEW

**Comment by dougmet** [comment]
This will need a little testing. It fixed the issue in my local build.

**Comment by dougmet** [comment]
Yes good point. I'm not sure I totally like how global variables pass around the various includes.

I do like the idea of the variables include. Should make the layout more readable too.

**Comment by brockfanning** [comment]
Agreed, the global variables are not great developer experience. Maybe we call it "global_variables.html" to make it very clear what it is? They could probably also have a naming convention, like maybe starting them with "_" (like, _meta and _t). Meanwhile we can start thinking about whether there is a possible way to avoid using them.

**Comment by brockfanning** [comment]
@dougmet Are you leaning towards waiting for the more involved fix we're discussing, or starting now with the quick fix in this PR?

**Comment by dougmet** [comment]
Yes I think so. But it doesn't need to be too involved. At the very least I'll move things to that `global_variables.html` file and that will make things more readable. As this bug is live I should probably get you something asap.

I vaguely recall there's a way to "pass" variables into include files. I'll double check, that might be one way around this.

**Comment by dougmet** [comment]
Yep. I noticed that as soon as I'd done it. Yes OK, then that would go in `default.html` and then in `indicator.html` it would go:

```
{% include global-variables.html %}
{% include indicator-variables.html %}
```

**Comment by dougmet** [comment]
OR

We could just have global variables and then some control logic. I think I prefer the first one.

**Comment by brockfanning** [comment]
@dougmet I agree with your preference there.

**Comment by brockfanning** [comment]
@dougmet One note though - I don't think that just putting it in default.html would be enough. I think it would need to be added to the top of all the layouts.

**Comment by dougmet** [comment]
hi, ignore commits and future builds until I say so. My testing system currently involves pushing to this branch and then building the site from it. If necessary I can close the PR and reopen when ready.

**Comment by brockfanning** [comment]
Cool, no need to close/reopen.

**Comment by dougmet** [comment]
ok good. I need a better flow for this.

**Comment by dougmet** [comment]
Closing for #76

**Pull request closed without merging**
