### PR TITLE
Deprecations for 2.0.0

### LINKED ISSUE #1592: Remove deprecated code and backwards compatibility for 2.0.0
This ticket is to make all of the v2 stuff that was introduced in 1.8.0 as optional into mandatory functionality

### PR DESCRIPTION
**Pull request by brockfanning**
Fixes #1592 

A large work-in-progress for moving to 2.0.0 and removing deprecated code. This will depend on corresponding "remove-deprecated-code" branches in both sdg-build and jekyll-open-sdg-plugins.

Here are the changes included in this PR. For each of these, there should be:
1. The change made in the codebases
2. Documentation of the change in the 2.0.0 upgrade notes
3. Documentation updated according to the change (eg, a deprecated site config should be removed from our documentation)
4. Builds should abort if required things are not met, with a helpful error message

* [x] data build: indicator_number instead of indicator
* [x] data build: target_number instead of target_id
* [x] data build: goal_number instead of sdg_goal
* [x] languages: required
* [x] languages in data build: required
* [x] accessible_charts: remove and make it automatic
* [x] accessible_tabs: remove and make it automatic
* [x] bootstrap_5: remove and make it automatic
* [x] chartjs_3: remove and make it automatic
* [x] contrast_type: remove and assume single
* [x] create_goals.layout: remove and always use “goal”
* [x] favicons: remove and make automatic
* [x] frontpage_heading: remove
* [x] frontpage_instructions: remove
* [x] header removed
* [x] non_global_metadata: remove and rely on metadata_tabs
* [x] series_toggle: remove and make automatic
* [x] create_pages.pages: no longer supported, just use create_pages
* [x] date formats old structure no longer supported
* [x] datapackage.sorting - default to “default” instead of “alphabetical”
* [x] create_pages: automatically create frontpage and indicator-json
* [x] non-translated builds removed

### CODE REVIEW

**Comment by brockfanning** [comment]
@otis-bath I believe this is ready for an initial test. Note that you will need to point to different branches for both jekyll-open-sdg-plugins and sdg-build. In all cases the branch is called "remove-deprecated-code".

I believe you should expect for the builds to fail and for (hopefully) helpful error messages to appear in the Github Actions logs.

**Comment by otis-bath** [comment]
Hi @brockfanning, apologies this has taken a bit of time to look at but should have more availability for testing this week. So have set the branch up and am pointing at the branches in sdg-build and  jekyll-open-sdg-plugins. The site build failed because of the create_pages setting and has the correct deprication notice. The data build still completed and wasn't getting the deprecation notices, I will go back and put all these site and data config options on and reply with what notices appear

**Comment by otis-bath** [comment]
Hi @brockfanning, an update on this - I have pointed the FB I created for the docs review towards your deprecated code branch as this had almost all the site, data and indicator config settings set so can properly review.

The site build is failing because of the create_pages using an invalid format (working correctly). Elsewhere I can see the deprecation notices for contrast_type, create_goals.layout, favicons, frontpage_heading, frontpage_instructions, non_global_metadata, series_toggle which is great. 

I have set accessible_charts and accessible_tabs as true, the header is also set (not the custom BS5 header) and I am using a custom date format (Month/Year/Day) however these are not generating deprecation warnings - should they be?

**Comment by otis-bath** [comment]
> @otis-bath Can you link me to to the feature branch so I can take a look at the configuration?

@brockfanning it is called feature-docs-review-bs5-cjs3 and is here in [sdg-indicators](https://github.com/ONSdigital/sdg-indicators/tree/feature-docs-review-bs5-cjs3) and [sdg-data](https://github.com/ONSdigital/sdg-data/tree/feature-docs-review-bs5-cjs3) there are a lot of configurations but the ones I am referring to are [accessibility](https://github.com/ONSdigital/sdg-indicators/blob/865ecf4d426d7dbdfd5b8e4343e2b5ae80437fa7/_config.yml#L111), [header](https://github.com/ONSdigital/sdg-indicators/blob/865ecf4d426d7dbdfd5b8e4343e2b5ae80437fa7/_config.yml#L122), [dates](https://github.com/ONSdigital/sdg-indicators/blob/865ecf4d426d7dbdfd5b8e4343e2b5ae80437fa7/_config.yml#L74)

**Comment by brockfanning** [comment]
@otis-bath The accessibility and header configurations are fine - we don't need to have a failure with those, because they are harmless and no longer used. But the date_formats config should have caused a failure. I've just made a change to try and fix that - can you give it another try?

**Comment by otis-bath** [comment]
Hi @brockfanning refreshed this, the build failure seems to be caused by the create_pages format still as opposed to anything else so cannot tell if the dates would cause a build failure - why is it that the create_pages is causing the failure as the same as the live site at the moment? Is there a way I can isolate the testing on the date format?

**Comment by brockfanning** [comment]
@otis-bath I think that in order to get past the create_pages failure you'll need to fix that issue. The format of the create_pages on the live site is actually incorrect -- using an outdated structure. See the [docs for create_pages](https://open-sdg.readthedocs.io/en/latest/configuration/#create_pages) and adjust the structure accordingly. In a nutshell, you need to remove the 'pages' part. I think that once that is fixed, it will get further in the build, but then fail on the date_formats part.

**Comment by otis-bath** [comment]
@brockfanning perfect thank you - have just set the create_pages to true and now the build it failing because of the date format as required

**Comment by brockfanning** [comment]
@otis-bath Once this is approved I can go ahead and merge.

**Pull request merged**
