### PR TITLE
Docs and testing for subfolder translation

### LINKED ISSUE #518: Reintroduce sub-folder approach for translations
Earlier on in the v1 project, the sub-folder approach was removed as it was causing complications in the code.

We will look into re-adding at as it's quite a useful feature and is/will be used extensively by countries

### PR DESCRIPTION
**Pull request by brockfanning**
Fixes #518 

Though this shows that subfolder translation works with translated builds (because that's what our automated tests use), it doesn't test untranslated builds. But I tried that out locally and it worked fine.

The actual code changes that brought back support for the subfolder approach were in these 2 pull-requests:
* https://github.com/open-sdg/sdg-build/pull/114
* https://github.com/open-sdg/jekyll-open-sdg-plugins/pull/34

If you want to test subfolder translation outside of these automated tests, note that it depends on:
* sdg-build 1.0.0-rc5
* jekyll-open-sdg-plugins 1.0.0.rc23

### CODE REVIEW

**Comment by brockfanning** [comment]
@LucyGwilliamAdmin Ok, subfolder translation should be ready to go, with the latest versions of sdg-build and jekyll-open-sdg-plugins (see the description of this PR for details). This PR is just confirming that it works with automated tests, and also adjusting the documentation.

**Comment by LucyGwilliamAdmin** [comment]
@brockfanning I've just tried this and I'm getting an error: 
https://github.com/sdg-kyrgyzstan/open-sdg-site-starter/runs/472221275?check_suite_focus=true

**Comment by brockfanning** [comment]
@LucyGwilliamAdmin It looks like you're already upgrading the sdg-build stuff, which I think is correct. It's failing because it can't find the zip file, which sdg-build should be creating - though that was added recently.

**Comment by LucyGwilliamAdmin** [comment]
@brockfanning I think it might have been something to do with my sdg-build branch. I've just created it and now the site build has passed :)

**Comment by brockfanning** [comment]
@LucyGwilliamAdmin Good to hear - does it appear the subfolders are being used?

**Comment by LucyGwilliamAdmin** [comment]
Yeah

**Pull request merged**
