### PR TITLE
Update about.md

### PR DESCRIPTION
**Pull request by AnnCorp**
Revamped to include initial info on organisations behind Open SDG, remove some details that will be incorporated into FAQ page and lessen focus on 'national' reporting platforms given sub-national use.

### CODE REVIEW

**Comment by LucyGwilliamAdmin** [comment]
@AnnCorp just realised you had requested Brock's review on this - sorry!

**Comment by AnnCorp** [comment]
@LucyGwilliamAdmin the more the merrier!

**Comment by LucyGwilliamAdmin** [comment]
@AnnCorp I also merged it though

**Comment by brockfanning** [comment]
@AnnCorp @LucyGwilliamAdmin I think it looked good. The only thing I might add is, instead of:

> Open SDG is the result of collaboration between the UK [Office for National Statistics](https://www.ons.gov.uk/aboutus) (ONS), US government and the nonprofit [Center for Open Data Enterprise](https://www.opendataenterprise.org/) (CODE).

Maybe this?

> Open SDG is the result of collaboration between the UK [Office for National Statistics](https://www.ons.gov.uk/aboutus) (ONS), US government, the nonprofit [Center for Open Data Enterprise](https://www.opendataenterprise.org/) (CODE), and members of the Open SDG community.

**Comment by AnnCorp** [comment]
@brockfanning great point! Happy to add that.

**Pull request merged**
