### PR TITLE
Accessibility: update footer as unordered list

### PR DESCRIPTION
**Pull request by SavvasStephanides**
The links at the footer are now an unordered list (`<ul>`). I will also make a pull request on `sdg-indicators` for the `scss` updates.

### CODE REVIEW

**Comment by Norric1Admin** [comment]
@brockfanning Many of the existing fields use `!important` (24 uses in default.scss). Do you recommend removing them all, or only the new ones that Savvas added?

**Comment by SavvasStephanides** [comment]
@brockfanning I like the idea of restricting the use of `!important` as much as possible but it's already being used quite heavily in `default.scss`. As this seems like a complex issue (but an important one), I think we should tackle it as its own issue altogether, as a "refactoring" ticket.

**Comment by brockfanning** [comment]
Ok, sounds like a plan.

**Comment by SavvasStephanides** [comment]
Thanks for the suggestion @brockfanning. Just updated the branch.

**Pull request merged**
