### PR TITLE
Use normal color for search button in high-contrast mode

### LINKED ISSUE #1123: Search button not correct colour in high contrast
http://sdgdev-813006012.eu-west-1.elb.amazonaws.com/1.3.0-dev:

image

### PR DESCRIPTION
**Pull request by brockfanning**
Q | A
--- | ---
Feature branch/test site URL | [Link](add link here)
Fixed issues | Fixes #1123
Related version | 1.3.0-dev
Bugfix, feature or docs? | Bugfix
Keeps backward-compatibility? |✔️
Includes tests? |NA
Updated docs? |NA
Updated config forms? |NA
Added CHANGELOG entry? |NA (bug is in same release)

### CODE REVIEW

**Review by jwestw — APPROVED** [review]
Approving according to last comment

**Comment by brockfanning** [comment]
@jwestw I think the comment got lost. I think it would be useful for @phillipgardiner to see the feature branch.

**Comment by phillipgardiner** [comment]
@brockfanning @jwestw @LucyGwilliamAdmin I think perhaps this ties in with a ticket in our issues list (open): https://github.com/open-sdg/open-sdg/issues/1114. This promotes the use of 2 greys for the buttons on the graph page in high contrast mode. Perhaps the same colours should be applied to the search button in high constrast mode? but this would also involve changing the magnifying glass from white to black in high contrast. @brockfanning thoughts on this? It does seem a bit odd keeping a green button tbh.

**Comment by brockfanning** [comment]
@jwestw @phillipgardiner @LucyGwilliamAdmin 
I like the idea of consistency, yes, so whatever gets us there sounds good to me. CSS changes are easy so no technical concerns.

**Comment by brockfanning** [comment]
@jwestw @phillipgardiner @LucyGwilliamAdmin I'll go ahead and close this PR and put a note in #1114.

**Pull request closed without merging**
