### PR TITLE
1.5.0-beta1 upgrade instructions

### PR DESCRIPTION
**Pull request by brockfanning**
This is not intended to be reviewed/merged yet, but is here to provide upgrade instructions as we release beta versions.

### CODE REVIEW

**Comment by LucyGwilliamAdmin** [comment]
@brockfanning I think there may be a breaking change from https://github.com/open-sdg/open-sdg/pull/1295. I'm testing now and needed to change the favicons so that our custom one shows

**Comment by brockfanning** [comment]
@LucyGwilliamAdmin Thank you for flagging that - what was the change you needed to make?

**Comment by LucyGwilliamAdmin** [comment]
@brockfanning I deleted everything that was in the favicons folder (see [commit](https://github.com/ONSdigital/sdg-indicators/commit/9a607de478cc69eecd71322dbcca70ead5936829#diff-98085b6004acaffa9a1a6f1f8777a00ec87e9d94835faa2e62016f82e24aa9ad)) and then followed the instructions to convert the image with favicon.io and upload the new files

**Comment by brockfanning** [comment]
@LucyGwilliamAdmin Ah ok - I hate to cause a breaking change for something so trivial.... Unfortunately though, if we standardize around the favicon.io files, they are named differently from the old files.

One way around it is to have a `favicons` config setting, with the options of "classic" and "favicon.io". And depending on which is chosen, the favicon images will be named differently. And it would default to "classic". What do you think?

**Comment by LucyGwilliamAdmin** [comment]
@brockfanning yeah I guess that could work, but I think def would be something to add to the list to deprecate in 2.0.0

**Comment by brockfanning** [comment]
@LucyGwilliamAdmin Ok, I've got a PR up for that: #1330

**Pull request merged**
